-- FTC-GUID: 557337,3b8ca3,dc50bb
    -- TO CHANGE THE SIZE OF THE AREA FOR THE MAP LOADING/DELETING, READ THIS
    -- Change the zoneScale size to match a zone you create in game (as reference)
    -- Be sure the zone extends below the table too
    -- This should be the same as the Saving Tool for your table.
    -------------------------------------------------------------
    zoneScale = {x=60.12, y=73, z=44.04} --60x44 Strike Force
    -------------------------------------------------------------
    function onLoad()
        self.createButton({
            label = "Load Map",
            font_size = 115,
            color = {0, 1, 0,},
            position = {-0.96, 0.5, 0},
            rotation = {0, 90, 0},
            scale = {1.3, 1, .7},
            width = 570,
            height = 160,
            click_function = "loadMap",
            function_owner = self,
        })	
    
        self.createButton({
            label = "Clear Map",
            font_size = 100,
            position = {1, 0.5, 0},
            rotation = {0, 90, 0},
            scale = {.6, .6, .4},
            width = 530,
            height = 130,
            color = {1, 0, 0},
            click_function = "clearMap",
            function_owner = self,
        })
    end
    
    -------------------
    -- Prepares the terrain saved into the card from Map Saver tool
    string.split = function(s, delimiter)
        local result = { }
        local from  = 1
        local delim_from, delim_to = string.find( s, delimiter, from  )
        while delim_from do
            table.insert( result, string.sub( s, from , delim_from-1 ) )
            from  = delim_to + 1
            delim_from, delim_to = string.find( s, delimiter, from  )
        end
        table.insert( result, string.sub( s, from  ) )
        return result
    end
	
	function scriptzoneCallback(zone) --This deletes everything except the things listed, when the scripting zone is briefly spawned.
	
        local objects = zone.getObjects()
        
        for i, obj in ipairs(objects) do
            ----------------------------------------------
             --IMPORTANT! Keep the map card from deleting speficic stuff here
            ----------------------------------------------
            if obj.getGMNotes() ~= "MapExclude" -- As black player, right click and add "MapExclude" to anything you dont want deleted. You may have to temporarily make your table interactable to do this, with its scripting.
                and
                obj.getGUID() ~= "e7ca6e" --Exclude Map Buidler Table
                and 
                obj.getGUID() ~= "6012bf" --...and ForceOrg Table...
                and 
                obj.getGUID() ~= "4ee1f2" --...and FTC board matObjSurface
                and
                obj.getGUID() ~= "948ce5" --...and FTC Table
                and
                obj.getGUID() ~= "28865a" --...and FTC Felt Surface
                then 
                obj.destruct()
            end  
        end
        zone.destruct()
    end
    function loadMap(objectClicked, clickerColor, altClickUsed)
        ----------
        -- Spawn the scripting zone, which uses the callback above that deletes everything then deletes itself.
        local scriptzoneParams = {                  -- Define the parameters for the scripting zone
            position = {x=0, y=26, z=0},
            scale = zoneScale,
            type = 'ScriptingTrigger',              -- Use the ScriptingTrigger type to spawn a Scripting Zone
            callback_function = scriptzoneCallback, -- Specify the function to call when the zone is created
            callback_owner = self,
            }

		spawnObject(scriptzoneParams)
		-- Then Sspawn the objects stored in the card
		
        Wait.time(
        function()
            for _, objectJSON in ipairs(objectJSONs) do 
                -- Spawn the map from the JSON data
                spawnObjectJSON({
                    json = objectJSON
                })
            end
        end, .5)
    end
    
    -----------------------------
    -- This function runs when the Clear Map button is clicked on the Map Card
    function clearMap(objectClicked, clickerColor, altClickUsed)

        local scriptzoneParams = {                  -- Define the parameters for the scripting zone
            position = {x=0, y=26, z=0},
            scale = zoneScale,
            type = 'ScriptingTrigger',              -- Use the ScriptingTrigger type to spawn a Scripting Zone
            callback_function = scriptzoneCallback, -- Specify the function to call when the zone is created
            callback_owner = self,
            }

    spawnObject(scriptzoneParams)
    
    end
        

objectJSONs = {
  [[{
  "GUID": "01cd69",
  "Name": "BlockSquare",
  "Transform": {
    "posX": 20.42862,
    "posY": 1.03038812,
    "posZ": -13.0175657,
    "rotX": 1.09965477E-07,
    "rotY": 143.031433,
    "rotZ": 3.28951955E-07,
    "scaleX": 10.0042038,
    "scaleY": 0.1,
    "scaleZ": 5.00000048
  },
  "Nickname": "Ruin (9\")  [sup]Barricade parts of this terrain feature are considered as 2\" high. Models may only be placed on the bottom level of this terrain feature[/sup]",
  "Description": "",
  "GMNotes": "",
  "AltLookAngle": {
    "x": 0.0,
    "y": 0.0,
    "z": 0.0
  },
  "ColorDiffuse": {
    "r": 0.232399523,
    "g": 0.2239995,
    "b": 0.349999517
  },
  "LayoutGroupSortIndex": 0,
  "Value": 0,
  "Locked": true,
  "Grid": true,
  "Snap": true,
  "IgnoreFoW": false,
  "MeasureMovement": false,
  "DragSelectable": true,
  "Autoraise": true,
  "Sticky": true,
  "Tooltip": true,
  "GridProjection": false,
  "HideWhenFaceDown": false,
  "Hands": false,
  "LuaScript": "\nBCBtype = \"terrain\"\n",
  "LuaScriptState": "",
  "XmlUI": "",
  "ChildObjects": [
    {
      "GUID": "b21c07",
      "Name": "Custom_Model",
      "Transform": {
        "posX": -0.316768825,
        "posY": 0.464860469,
        "posZ": -0.15316163,
        "rotX": -0.0003899341,
        "rotY": 231.968582,
        "rotZ": -6.56546254E-05,
        "scaleX": 0.265397877,
        "scaleY": 18.3109741,
        "scaleZ": 0.109541483
      },
      "Nickname": "",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 0.444141835,
        "g": 0.444141835,
        "b": 0.444141835
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomMesh": {
        "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009293027/95A2286D63E1AF7BB7CE9B8E33B5F27F9E975DDA/",
        "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009292144/9153E2B34BFF806C0F4E7EEFCD0594B21623FDC3/",
        "NormalURL": "",
        "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009293027/95A2286D63E1AF7BB7CE9B8E33B5F27F9E975DDA/",
        "Convex": false,
        "MaterialIndex": 3,
        "TypeIndex": 0,
        "CustomShader": {
          "SpecularColor": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "SpecularIntensity": 0.0,
          "SpecularSharpness": 2.0,
          "FresnelStrength": 0.0
        },
        "CastShadows": true
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": ""
    },
    {
      "GUID": "648368",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": -0.124679588,
        "posY": 0.8105263,
        "posZ": -0.411790818,
        "rotX": -0.00103296014,
        "rotY": 0.239548579,
        "rotZ": -0.000209828882,
        "scaleX": 0.07996709,
        "scaleY": 35.0,
        "scaleZ": 0.159997225
      },
      "Nickname": "Ruin",
      "Description": "You can NOT draw line of sight between the gaps in walls",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": ""
    },
    {
      "GUID": "84487a",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": 0.159674555,
        "posY": 0.499377072,
        "posZ": -0.408205539,
        "rotX": 0.00151213643,
        "rotY": 180.235367,
        "rotZ": -0.000844277267,
        "scaleX": 0.165282175,
        "scaleY": 35.0000534,
        "scaleZ": 0.200002775
      },
      "Nickname": "",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": ""
    },
    {
      "GUID": "f2a7d0",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": 0.453756124,
        "posY": 0.677646339,
        "posZ": -0.416630924,
        "rotX": -0.000813225459,
        "rotY": 90.2394943,
        "rotZ": -0.001244804,
        "scaleX": 0.159997225,
        "scaleY": 35.0,
        "scaleZ": 0.07996708
      },
      "Nickname": "Ruin",
      "Description": "You can NOT draw line of sight between the gaps in walls",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": ""
    },
    {
      "GUID": "fb9714",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": 0.460546046,
        "posY": 0.500269055,
        "posZ": 0.0111152763,
        "rotX": -0.000557691848,
        "rotY": 90.2380753,
        "rotZ": -0.00125915033,
        "scaleX": 0.220547646,
        "scaleY": 35.00006,
        "scaleZ": 0.09995994
      },
      "Nickname": "",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": ""
    },
    {
      "GUID": "1ec7ad",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": 0.455497265,
        "posY": 0.6785468,
        "posZ": 0.416397929,
        "rotX": -0.0008130619,
        "rotY": 90.2394943,
        "rotZ": -0.00124800159,
        "scaleX": 0.159997225,
        "scaleY": 35.0,
        "scaleZ": 0.07996708
      },
      "Nickname": "Ruin",
      "Description": "You can NOT draw line of sight between the gaps in walls",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": ""
    }
  ]
}]],
  [[{
  "GUID": "3dba30",
  "Name": "BlockSquare",
  "Transform": {
    "posX": 13.5129337,
    "posY": 1.04546666,
    "posZ": -4.02943039,
    "rotX": 359.8885,
    "rotY": 89.9989,
    "rotZ": 0.012135095,
    "scaleX": 10.00421,
    "scaleY": 0.09999991,
    "scaleZ": 5.00000668
  },
  "Nickname": "Ruin (9\")  [sup]Barricade parts of this terrain feature are considered as 2\" high. Models may only be placed on the bottom level of this terrain feature[/sup]",
  "Description": "",
  "GMNotes": "",
  "AltLookAngle": {
    "x": 0.0,
    "y": 0.0,
    "z": 0.0
  },
  "ColorDiffuse": {
    "r": 0.232399464,
    "g": 0.223999441,
    "b": 0.349999458
  },
  "LayoutGroupSortIndex": 0,
  "Value": 0,
  "Locked": true,
  "Grid": true,
  "Snap": true,
  "IgnoreFoW": false,
  "MeasureMovement": false,
  "DragSelectable": true,
  "Autoraise": true,
  "Sticky": true,
  "Tooltip": true,
  "GridProjection": false,
  "HideWhenFaceDown": false,
  "Hands": false,
  "LuaScript": "\nBCBtype = \"terrain\"\n",
  "LuaScriptState": "",
  "XmlUI": "",
  "ChildObjects": [
    {
      "GUID": "a811d0",
      "Name": "Custom_Model",
      "Transform": {
        "posX": 0.287939936,
        "posY": 0.4625298,
        "posZ": 0.05030344,
        "rotX": -0.0007553774,
        "rotY": 59.9928,
        "rotZ": 0.000143050667,
        "scaleX": 0.312212735,
        "scaleY": 19.51829,
        "scaleZ": 0.108120918
      },
      "Nickname": "",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 0.444141835,
        "g": 0.444141835,
        "b": 0.444141835
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomMesh": {
        "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009293027/95A2286D63E1AF7BB7CE9B8E33B5F27F9E975DDA/",
        "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009292144/9153E2B34BFF806C0F4E7EEFCD0594B21623FDC3/",
        "NormalURL": "",
        "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009293027/95A2286D63E1AF7BB7CE9B8E33B5F27F9E975DDA/",
        "Convex": false,
        "MaterialIndex": 3,
        "TypeIndex": 0,
        "CustomShader": {
          "SpecularColor": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "SpecularIntensity": 0.0,
          "SpecularSharpness": 2.0,
          "FresnelStrength": 0.0
        },
        "CastShadows": true
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": ""
    },
    {
      "GUID": "2ff768",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": 0.09407788,
        "posY": -0.294445038,
        "posZ": -0.4200653,
        "rotX": 8.7020986E-08,
        "rotY": 180.009827,
        "rotZ": 2.65682411E-05,
        "scaleX": 0.07996636,
        "scaleY": 35.0000076,
        "scaleZ": 0.159999922
      },
      "Nickname": "Ruin",
      "Description": "You can NOT draw line of sight between the gaps in walls",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": ""
    },
    {
      "GUID": "43121c",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": -0.452701449,
        "posY": -0.5861089,
        "posZ": -0.0028835258,
        "rotX": -2.65682429E-05,
        "rotY": 270.009827,
        "rotZ": 8.701101E-08,
        "scaleX": 0.229364187,
        "scaleY": 35.0000839,
        "scaleZ": 0.0999589339
      },
      "Nickname": "Ruin (9\")  [sup]Barricade parts of this terrain feature are considered as 2\" high. Models may only be placed on the bottom level of this terrain feature[/sup]",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": ""
    },
    {
      "GUID": "648368",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": -0.455690026,
        "posY": -0.363943547,
        "posZ": 0.414585561,
        "rotX": 2.656825E-05,
        "rotY": 90.0098343,
        "rotZ": -8.701996E-08,
        "scaleX": 0.1599998,
        "scaleY": 35.0000267,
        "scaleZ": 0.07996636
      },
      "Nickname": "Ruin",
      "Description": "You can NOT draw line of sight between the gaps in walls",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": ""
    },
    {
      "GUID": "a1337a",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": -0.4556918,
        "posY": -0.172782451,
        "posZ": -0.420050651,
        "rotX": 8.7020986E-08,
        "rotY": 180.009827,
        "rotZ": 2.65682411E-05,
        "scaleX": 0.0799663737,
        "scaleY": 35.0000076,
        "scaleZ": 0.1599999
      },
      "Nickname": "Ruin",
      "Description": "You can NOT draw line of sight between the gaps in walls",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "3c9aee",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": -3.483935,
            "posY": -0.008838829,
            "posZ": -0.0175681617,
            "rotX": 0.0,
            "rotY": 0.0,
            "rotZ": 0.0,
            "scaleX": 1.85914624,
            "scaleY": 1.00000179,
            "scaleZ": 1.25001037
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        }
      ]
    }
  ]
}]],
  [[{
  "GUID": "4bfcaa",
  "Name": "Custom_Assetbundle",
  "Transform": {
    "posX": 14.1924753,
    "posY": 1.08048773,
    "posZ": 11.254899,
    "rotX": 0.000230498088,
    "rotY": 41.00001,
    "rotZ": -7.93232E-06,
    "scaleX": 2.0,
    "scaleY": 3.50000548,
    "scaleZ": 1.0000093
  },
  "Nickname": "Ruin (9\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
  "Description": "",
  "GMNotes": "",
  "AltLookAngle": {
    "x": 0.0,
    "y": 0.0,
    "z": 0.0
  },
  "ColorDiffuse": {
    "r": 1.0,
    "g": 1.0,
    "b": 1.0
  },
  "LayoutGroupSortIndex": 0,
  "Value": 0,
  "Locked": true,
  "Grid": true,
  "Snap": true,
  "IgnoreFoW": false,
  "MeasureMovement": false,
  "DragSelectable": true,
  "Autoraise": true,
  "Sticky": true,
  "Tooltip": true,
  "GridProjection": false,
  "HideWhenFaceDown": false,
  "Hands": false,
  "CustomAssetbundle": {
    "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
    "AssetbundleSecondaryURL": "",
    "MaterialIndex": 2,
    "TypeIndex": 1,
    "LoopingEffectIndex": 0
  },
  "LuaScript": "\nBCBtype = \"terrain\"\n",
  "LuaScriptState": "",
  "XmlUI": "",
  "ChildObjects": [
    {
      "GUID": "12f429",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": -1.66335976,
        "posY": -4.695395E-06,
        "posZ": 1.60390592,
        "rotX": 0.000259141467,
        "rotY": 270.0,
        "rotZ": 0.000211977836,
        "scaleX": 0.9999867,
        "scaleY": 0.9999998,
        "scaleZ": 0.469566315
      },
      "Nickname": "",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "bd4f47",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": -1.56313694,
            "posY": 0.008891447,
            "posZ": 0.0170597527,
            "rotX": 0.0007243755,
            "rotY": 179.9797,
            "rotZ": -0.00114142289,
            "scaleX": 0.7513363,
            "scaleY": 0.999998152,
            "scaleZ": 0.8518104
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": "",
          "ChildObjects": [
            {
              "GUID": "5cc9a0",
              "Name": "Custom_Assetbundle",
              "Transform": {
                "posX": 0.0444651768,
                "posY": 1.561915E-05,
                "posZ": 8.15553951,
                "rotX": 0.00150016113,
                "rotY": 269.927673,
                "rotZ": -0.0006530432,
                "scaleX": 1.00003386,
                "scaleY": 1.0,
                "scaleZ": 0.9999646
              },
              "Nickname": "",
              "Description": "",
              "GMNotes": "",
              "AltLookAngle": {
                "x": 0.0,
                "y": 0.0,
                "z": 0.0
              },
              "ColorDiffuse": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "LayoutGroupSortIndex": 0,
              "Value": 0,
              "Locked": true,
              "Grid": true,
              "Snap": true,
              "IgnoreFoW": false,
              "MeasureMovement": false,
              "DragSelectable": true,
              "Autoraise": true,
              "Sticky": true,
              "Tooltip": true,
              "GridProjection": false,
              "HideWhenFaceDown": false,
              "Hands": false,
              "CustomAssetbundle": {
                "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
                "AssetbundleSecondaryURL": "",
                "MaterialIndex": 2,
                "TypeIndex": 1,
                "LoopingEffectIndex": 0
              },
              "LuaScript": "",
              "LuaScriptState": "",
              "XmlUI": "",
              "ChildObjects": [
                {
                  "GUID": "f0f588",
                  "Name": "Custom_Assetbundle",
                  "Transform": {
                    "posX": -8.186625,
                    "posY": -2.84014277E-05,
                    "posZ": 4.36520529,
                    "rotX": -0.000674018753,
                    "rotY": 90.07219,
                    "rotZ": -0.0014666667,
                    "scaleX": 1.00003493,
                    "scaleY": 0.9999998,
                    "scaleZ": 0.999966145
                  },
                  "Nickname": "",
                  "Description": "",
                  "GMNotes": "",
                  "AltLookAngle": {
                    "x": 0.0,
                    "y": 0.0,
                    "z": 0.0
                  },
                  "ColorDiffuse": {
                    "r": 1.0,
                    "g": 1.0,
                    "b": 1.0
                  },
                  "LayoutGroupSortIndex": 0,
                  "Value": 0,
                  "Locked": true,
                  "Grid": true,
                  "Snap": true,
                  "IgnoreFoW": false,
                  "MeasureMovement": false,
                  "DragSelectable": true,
                  "Autoraise": true,
                  "Sticky": true,
                  "Tooltip": true,
                  "GridProjection": false,
                  "HideWhenFaceDown": false,
                  "Hands": false,
                  "CustomAssetbundle": {
                    "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
                    "AssetbundleSecondaryURL": "",
                    "MaterialIndex": 2,
                    "TypeIndex": 1,
                    "LoopingEffectIndex": 0
                  },
                  "LuaScript": "",
                  "LuaScriptState": "",
                  "XmlUI": "",
                  "ChildObjects": [
                    {
                      "GUID": "ced9ff",
                      "Name": "BlockSquare",
                      "Transform": {
                        "posX": 0.877248347,
                        "posY": -0.0231600236,
                        "posZ": 7.01134968,
                        "rotX": 0.00108863518,
                        "rotY": 270.020416,
                        "rotZ": 0.000450732769,
                        "scaleX": 15.0006924,
                        "scaleY": 0.0285714269,
                        "scaleZ": 7.984984
                      },
                      "Nickname": "Ruin (9\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
                      "Description": "",
                      "GMNotes": "",
                      "AltLookAngle": {
                        "x": 0.0,
                        "y": 0.0,
                        "z": 0.0
                      },
                      "ColorDiffuse": {
                        "r": 0.232399791,
                        "g": 0.223999768,
                        "b": 0.349999815
                      },
                      "LayoutGroupSortIndex": 0,
                      "Value": 0,
                      "Locked": true,
                      "Grid": true,
                      "Snap": true,
                      "IgnoreFoW": false,
                      "MeasureMovement": false,
                      "DragSelectable": true,
                      "Autoraise": true,
                      "Sticky": true,
                      "Tooltip": true,
                      "GridProjection": false,
                      "HideWhenFaceDown": false,
                      "Hands": false,
                      "LuaScript": "\nBCBtype = \"terrain\"\n",
                      "LuaScriptState": "",
                      "XmlUI": ""
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}]],
  [[{
  "GUID": "7f414f",
  "Name": "Custom_Model",
  "Transform": {
    "posX": 0.0,
    "posY": -10.13,
    "posZ": 0.0,
    "rotX": 0.0,
    "rotY": 0.0,
    "rotZ": 0.0,
    "scaleX": 1.666,
    "scaleY": 1.06,
    "scaleZ": 1.2206
  },
  "Nickname": "",
  "Description": "",
  "GMNotes": "",
  "AltLookAngle": {
    "x": 0.0,
    "y": 0.0,
    "z": 0.0
  },
  "ColorDiffuse": {
    "r": 1.0,
    "g": 1.0,
    "b": 1.0
  },
  "LayoutGroupSortIndex": 0,
  "Value": 0,
  "Locked": true,
  "Grid": true,
  "Snap": true,
  "IgnoreFoW": false,
  "MeasureMovement": false,
  "DragSelectable": true,
  "Autoraise": true,
  "Sticky": true,
  "Tooltip": true,
  "GridProjection": true,
  "HideWhenFaceDown": false,
  "Hands": false,
  "CustomMesh": {
    "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/879750610978796176/4A5A65543B98BCFBF57E910D06EC984208223D38/",
    "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2044114931095280776/E1E5945811D1F5CE79E1A0B1580133658FC2A9AE/",
    "NormalURL": "",
    "ColliderURL": "",
    "Convex": true,
    "MaterialIndex": 3,
    "TypeIndex": 4,
    "CustomShader": {
      "SpecularColor": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "SpecularIntensity": 0.0,
      "SpecularSharpness": 2.0,
      "FresnelStrength": 0.0
    },
    "CastShadows": true
  },
  "LuaScript": "\nBCBtype = \"terrain\"\nfunction onload() \r\n    self.interactable = false\r\n    self.gizmo_selectable = true\r\nend",
  "LuaScriptState": "",
  "XmlUI": ""
}]],
  [[{
  "GUID": "089fa1",
  "Name": "BlockSquare",
  "Transform": {
    "posX": -20.42862,
    "posY": 1.03038824,
    "posZ": 13.0175667,
    "rotX": -2.693419E-06,
    "rotY": 323.031433,
    "rotZ": -1.86721721E-07,
    "scaleX": 10.0042038,
    "scaleY": 0.1,
    "scaleZ": 5.00000048
  },
  "Nickname": "Ruin (9\")  [sup]Barricade parts of this terrain feature are considered as 2\" high. Models may only be placed on the bottom level of this terrain feature[/sup]",
  "Description": "",
  "GMNotes": "",
  "AltLookAngle": {
    "x": 0.0,
    "y": 0.0,
    "z": 0.0
  },
  "ColorDiffuse": {
    "r": 0.232399553,
    "g": 0.22399953,
    "b": 0.349999547
  },
  "LayoutGroupSortIndex": 0,
  "Value": 0,
  "Locked": true,
  "Grid": true,
  "Snap": true,
  "IgnoreFoW": false,
  "MeasureMovement": false,
  "DragSelectable": true,
  "Autoraise": true,
  "Sticky": true,
  "Tooltip": true,
  "GridProjection": false,
  "HideWhenFaceDown": false,
  "Hands": false,
  "LuaScript": "\nBCBtype = \"terrain\"\n",
  "LuaScriptState": "",
  "XmlUI": "",
  "ChildObjects": [
    {
      "GUID": "b21c07",
      "Name": "Custom_Model",
      "Transform": {
        "posX": -0.316768825,
        "posY": 0.464860469,
        "posZ": -0.15316163,
        "rotX": -0.0003899341,
        "rotY": 231.968582,
        "rotZ": -6.56546254E-05,
        "scaleX": 0.265397877,
        "scaleY": 18.3109741,
        "scaleZ": 0.109541483
      },
      "Nickname": "",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 0.444141835,
        "g": 0.444141835,
        "b": 0.444141835
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomMesh": {
        "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009293027/95A2286D63E1AF7BB7CE9B8E33B5F27F9E975DDA/",
        "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009292144/9153E2B34BFF806C0F4E7EEFCD0594B21623FDC3/",
        "NormalURL": "",
        "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009293027/95A2286D63E1AF7BB7CE9B8E33B5F27F9E975DDA/",
        "Convex": false,
        "MaterialIndex": 3,
        "TypeIndex": 0,
        "CustomShader": {
          "SpecularColor": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "SpecularIntensity": 0.0,
          "SpecularSharpness": 2.0,
          "FresnelStrength": 0.0
        },
        "CastShadows": true
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": ""
    },
    {
      "GUID": "648368",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": -0.124679588,
        "posY": 0.8105263,
        "posZ": -0.411790818,
        "rotX": -0.00103296014,
        "rotY": 0.239548579,
        "rotZ": -0.000209828882,
        "scaleX": 0.07996709,
        "scaleY": 35.0,
        "scaleZ": 0.159997225
      },
      "Nickname": "Ruin",
      "Description": "You can NOT draw line of sight between the gaps in walls",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": ""
    },
    {
      "GUID": "84487a",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": 0.159674555,
        "posY": 0.499377072,
        "posZ": -0.408205539,
        "rotX": 0.00151213643,
        "rotY": 180.235367,
        "rotZ": -0.000844277267,
        "scaleX": 0.165282175,
        "scaleY": 35.0000534,
        "scaleZ": 0.200002775
      },
      "Nickname": "",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": ""
    },
    {
      "GUID": "f2a7d0",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": 0.453756124,
        "posY": 0.677646339,
        "posZ": -0.416630924,
        "rotX": -0.000813225459,
        "rotY": 90.2394943,
        "rotZ": -0.001244804,
        "scaleX": 0.159997225,
        "scaleY": 35.0,
        "scaleZ": 0.07996708
      },
      "Nickname": "Ruin",
      "Description": "You can NOT draw line of sight between the gaps in walls",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": ""
    },
    {
      "GUID": "fb9714",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": 0.460546046,
        "posY": 0.500269055,
        "posZ": 0.0111152763,
        "rotX": -0.000557691848,
        "rotY": 90.2380753,
        "rotZ": -0.00125915033,
        "scaleX": 0.220547646,
        "scaleY": 35.00006,
        "scaleZ": 0.09995994
      },
      "Nickname": "",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": ""
    },
    {
      "GUID": "1ec7ad",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": 0.455497265,
        "posY": 0.6785468,
        "posZ": 0.416397929,
        "rotX": -0.0008130619,
        "rotY": 90.2394943,
        "rotZ": -0.00124800159,
        "scaleX": 0.159997225,
        "scaleY": 35.0,
        "scaleZ": 0.07996708
      },
      "Nickname": "Ruin",
      "Description": "You can NOT draw line of sight between the gaps in walls",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": ""
    }
  ]
}]],
  [[{
  "GUID": "804aea",
  "Name": "Custom_Assetbundle",
  "Transform": {
    "posX": -14.1924763,
    "posY": 1.08048856,
    "posZ": -11.2549,
    "rotX": 0.000228606179,
    "rotY": 221.0,
    "rotZ": -3.162168E-05,
    "scaleX": 2.0,
    "scaleY": 3.50000548,
    "scaleZ": 1.0000093
  },
  "Nickname": "Ruin (9\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
  "Description": "",
  "GMNotes": "",
  "AltLookAngle": {
    "x": 0.0,
    "y": 0.0,
    "z": 0.0
  },
  "ColorDiffuse": {
    "r": 1.0,
    "g": 1.0,
    "b": 1.0
  },
  "LayoutGroupSortIndex": 0,
  "Value": 0,
  "Locked": true,
  "Grid": true,
  "Snap": true,
  "IgnoreFoW": false,
  "MeasureMovement": false,
  "DragSelectable": true,
  "Autoraise": true,
  "Sticky": true,
  "Tooltip": true,
  "GridProjection": false,
  "HideWhenFaceDown": false,
  "Hands": false,
  "CustomAssetbundle": {
    "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
    "AssetbundleSecondaryURL": "",
    "MaterialIndex": 2,
    "TypeIndex": 1,
    "LoopingEffectIndex": 0
  },
  "LuaScript": "\nBCBtype = \"terrain\"\n",
  "LuaScriptState": "",
  "XmlUI": "",
  "ChildObjects": [
    {
      "GUID": "12f429",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": -1.66335976,
        "posY": -4.695395E-06,
        "posZ": 1.60390592,
        "rotX": 0.000259141467,
        "rotY": 270.0,
        "rotZ": 0.000211977836,
        "scaleX": 0.9999867,
        "scaleY": 0.9999998,
        "scaleZ": 0.469566315
      },
      "Nickname": "",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "bd4f47",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": -1.56313694,
            "posY": 0.008891447,
            "posZ": 0.0170597527,
            "rotX": 0.0007243755,
            "rotY": 179.9797,
            "rotZ": -0.00114142289,
            "scaleX": 0.7513363,
            "scaleY": 0.999998152,
            "scaleZ": 0.8518104
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": "",
          "ChildObjects": [
            {
              "GUID": "5cc9a0",
              "Name": "Custom_Assetbundle",
              "Transform": {
                "posX": 0.0444651768,
                "posY": 1.561915E-05,
                "posZ": 8.15553951,
                "rotX": 0.00150016113,
                "rotY": 269.927673,
                "rotZ": -0.0006530432,
                "scaleX": 1.00003386,
                "scaleY": 1.0,
                "scaleZ": 0.9999646
              },
              "Nickname": "",
              "Description": "",
              "GMNotes": "",
              "AltLookAngle": {
                "x": 0.0,
                "y": 0.0,
                "z": 0.0
              },
              "ColorDiffuse": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "LayoutGroupSortIndex": 0,
              "Value": 0,
              "Locked": true,
              "Grid": true,
              "Snap": true,
              "IgnoreFoW": false,
              "MeasureMovement": false,
              "DragSelectable": true,
              "Autoraise": true,
              "Sticky": true,
              "Tooltip": true,
              "GridProjection": false,
              "HideWhenFaceDown": false,
              "Hands": false,
              "CustomAssetbundle": {
                "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
                "AssetbundleSecondaryURL": "",
                "MaterialIndex": 2,
                "TypeIndex": 1,
                "LoopingEffectIndex": 0
              },
              "LuaScript": "",
              "LuaScriptState": "",
              "XmlUI": "",
              "ChildObjects": [
                {
                  "GUID": "f0f588",
                  "Name": "Custom_Assetbundle",
                  "Transform": {
                    "posX": -8.186625,
                    "posY": -2.84014277E-05,
                    "posZ": 4.36520529,
                    "rotX": -0.000674018753,
                    "rotY": 90.07219,
                    "rotZ": -0.0014666667,
                    "scaleX": 1.00003493,
                    "scaleY": 0.9999998,
                    "scaleZ": 0.999966145
                  },
                  "Nickname": "",
                  "Description": "",
                  "GMNotes": "",
                  "AltLookAngle": {
                    "x": 0.0,
                    "y": 0.0,
                    "z": 0.0
                  },
                  "ColorDiffuse": {
                    "r": 1.0,
                    "g": 1.0,
                    "b": 1.0
                  },
                  "LayoutGroupSortIndex": 0,
                  "Value": 0,
                  "Locked": true,
                  "Grid": true,
                  "Snap": true,
                  "IgnoreFoW": false,
                  "MeasureMovement": false,
                  "DragSelectable": true,
                  "Autoraise": true,
                  "Sticky": true,
                  "Tooltip": true,
                  "GridProjection": false,
                  "HideWhenFaceDown": false,
                  "Hands": false,
                  "CustomAssetbundle": {
                    "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
                    "AssetbundleSecondaryURL": "",
                    "MaterialIndex": 2,
                    "TypeIndex": 1,
                    "LoopingEffectIndex": 0
                  },
                  "LuaScript": "",
                  "LuaScriptState": "",
                  "XmlUI": "",
                  "ChildObjects": [
                    {
                      "GUID": "ced9ff",
                      "Name": "BlockSquare",
                      "Transform": {
                        "posX": 0.877248347,
                        "posY": -0.0231600236,
                        "posZ": 7.01134968,
                        "rotX": 0.00108863518,
                        "rotY": 270.020416,
                        "rotZ": 0.000450732769,
                        "scaleX": 15.0006924,
                        "scaleY": 0.0285714269,
                        "scaleZ": 7.984984
                      },
                      "Nickname": "Ruin (9\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
                      "Description": "",
                      "GMNotes": "",
                      "AltLookAngle": {
                        "x": 0.0,
                        "y": 0.0,
                        "z": 0.0
                      },
                      "ColorDiffuse": {
                        "r": 0.232399791,
                        "g": 0.223999768,
                        "b": 0.349999815
                      },
                      "LayoutGroupSortIndex": 0,
                      "Value": 0,
                      "Locked": true,
                      "Grid": true,
                      "Snap": true,
                      "IgnoreFoW": false,
                      "MeasureMovement": false,
                      "DragSelectable": true,
                      "Autoraise": true,
                      "Sticky": true,
                      "Tooltip": true,
                      "GridProjection": false,
                      "HideWhenFaceDown": false,
                      "Hands": false,
                      "LuaScript": "\nBCBtype = \"terrain\"\n",
                      "LuaScriptState": "",
                      "XmlUI": ""
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}]],
  [[{
  "GUID": "7b1ab1",
  "Name": "BlockSquare",
  "Transform": {
    "posX": -14.46915,
    "posY": 1.04282427,
    "posZ": 1.99678457,
    "rotX": 359.9873,
    "rotY": 269.9901,
    "rotZ": 359.937347,
    "scaleX": 10.00421,
    "scaleY": 0.09999991,
    "scaleZ": 5.00000668
  },
  "Nickname": "Ruin (9\")  [sup]Barricade parts of this terrain feature are considered as 2\" high. Models may only be placed on the bottom level of this terrain feature[/sup]",
  "Description": "",
  "GMNotes": "",
  "AltLookAngle": {
    "x": 0.0,
    "y": 0.0,
    "z": 0.0
  },
  "ColorDiffuse": {
    "r": 0.2323995,
    "g": 0.22399947,
    "b": 0.3499995
  },
  "LayoutGroupSortIndex": 0,
  "Value": 0,
  "Locked": true,
  "Grid": true,
  "Snap": true,
  "IgnoreFoW": false,
  "MeasureMovement": true,
  "DragSelectable": true,
  "Autoraise": true,
  "Sticky": true,
  "Tooltip": true,
  "GridProjection": false,
  "HideWhenFaceDown": false,
  "Hands": false,
  "LuaScript": "\nBCBtype = \"terrain\"\n",
  "LuaScriptState": "",
  "XmlUI": "",
  "ChildObjects": [
    {
      "GUID": "a811d0",
      "Name": "Custom_Model",
      "Transform": {
        "posX": 0.287939936,
        "posY": 0.4625298,
        "posZ": 0.05030344,
        "rotX": -0.0007553774,
        "rotY": 59.9928,
        "rotZ": 0.000143050667,
        "scaleX": 0.312212735,
        "scaleY": 19.51829,
        "scaleZ": 0.108120918
      },
      "Nickname": "",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 0.444141835,
        "g": 0.444141835,
        "b": 0.444141835
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomMesh": {
        "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009293027/95A2286D63E1AF7BB7CE9B8E33B5F27F9E975DDA/",
        "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009292144/9153E2B34BFF806C0F4E7EEFCD0594B21623FDC3/",
        "NormalURL": "",
        "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009293027/95A2286D63E1AF7BB7CE9B8E33B5F27F9E975DDA/",
        "Convex": false,
        "MaterialIndex": 3,
        "TypeIndex": 0,
        "CustomShader": {
          "SpecularColor": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "SpecularIntensity": 0.0,
          "SpecularSharpness": 2.0,
          "FresnelStrength": 0.0
        },
        "CastShadows": true
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": ""
    },
    {
      "GUID": "2ff768",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": 0.09407788,
        "posY": -0.294445038,
        "posZ": -0.4200653,
        "rotX": 8.7020986E-08,
        "rotY": 180.009827,
        "rotZ": 2.65682411E-05,
        "scaleX": 0.07996636,
        "scaleY": 35.0000076,
        "scaleZ": 0.159999922
      },
      "Nickname": "Ruin",
      "Description": "You can NOT draw line of sight between the gaps in walls",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": ""
    },
    {
      "GUID": "43121c",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": -0.452701449,
        "posY": -0.5861089,
        "posZ": -0.0028835258,
        "rotX": -2.65682429E-05,
        "rotY": 270.009827,
        "rotZ": 8.701101E-08,
        "scaleX": 0.229364187,
        "scaleY": 35.0000839,
        "scaleZ": 0.0999589339
      },
      "Nickname": "Ruin (9\")  [sup]Barricade parts of this terrain feature are considered as 2\" high. Models may only be placed on the bottom level of this terrain feature[/sup]",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": ""
    },
    {
      "GUID": "648368",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": -0.455690026,
        "posY": -0.363943547,
        "posZ": 0.414585561,
        "rotX": 2.656825E-05,
        "rotY": 90.0098343,
        "rotZ": -8.701996E-08,
        "scaleX": 0.1599998,
        "scaleY": 35.0000267,
        "scaleZ": 0.07996636
      },
      "Nickname": "Ruin",
      "Description": "You can NOT draw line of sight between the gaps in walls",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": ""
    },
    {
      "GUID": "a1337a",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": -0.4556918,
        "posY": -0.172782451,
        "posZ": -0.420050651,
        "rotX": 8.7020986E-08,
        "rotY": 180.009827,
        "rotZ": 2.65682411E-05,
        "scaleX": 0.0799663737,
        "scaleY": 35.0000076,
        "scaleZ": 0.1599999
      },
      "Nickname": "Ruin",
      "Description": "You can NOT draw line of sight between the gaps in walls",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "3c9aee",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": -3.483935,
            "posY": -0.008838829,
            "posZ": -0.0175681617,
            "rotX": 0.0,
            "rotY": 0.0,
            "rotZ": 0.0,
            "scaleX": 1.85914624,
            "scaleY": 1.00000179,
            "scaleZ": 1.25001037
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        }
      ]
    }
  ]
}]],
  [[{
  "GUID": "f63c8c",
  "Name": "Custom_Assetbundle",
  "Transform": {
    "posX": -2.49999881,
    "posY": 1.06911421,
    "posZ": 16.0000019,
    "rotX": 0.0005046936,
    "rotY": 90.0,
    "rotZ": 0.22159636,
    "scaleX": 1.99489665,
    "scaleY": 3.527635,
    "scaleZ": 1.00002432
  },
  "Nickname": "Ruin (9\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
  "Description": "",
  "GMNotes": "",
  "AltLookAngle": {
    "x": 0.0,
    "y": 0.0,
    "z": 0.0
  },
  "ColorDiffuse": {
    "r": 1.0,
    "g": 1.0,
    "b": 1.0
  },
  "LayoutGroupSortIndex": 0,
  "Value": 0,
  "Locked": true,
  "Grid": true,
  "Snap": true,
  "IgnoreFoW": false,
  "MeasureMovement": false,
  "DragSelectable": true,
  "Autoraise": true,
  "Sticky": true,
  "Tooltip": true,
  "GridProjection": false,
  "HideWhenFaceDown": false,
  "Hands": false,
  "CustomAssetbundle": {
    "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
    "AssetbundleSecondaryURL": "",
    "MaterialIndex": 2,
    "TypeIndex": 1,
    "LoopingEffectIndex": 0
  },
  "LuaScript": "",
  "LuaScriptState": "",
  "XmlUI": "",
  "ChildObjects": [
    {
      "GUID": "0d1b87",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": 1.76267076,
        "posY": -0.000449319079,
        "posZ": -0.01457209,
        "rotX": 0.000112515983,
        "rotY": 180.213272,
        "rotZ": 2.12263944E-06,
        "scaleX": 0.40102616,
        "scaleY": 1.0,
        "scaleZ": 0.7999697
      },
      "Nickname": "",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "f321f4",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": -0.0138203735,
            "posY": -0.008904007,
            "posZ": 1.91282463,
            "rotX": 2.52710084E-08,
            "rotY": 89.99715,
            "rotZ": -3.0327833E-06,
            "scaleX": 1.25001657,
            "scaleY": 0.9999999,
            "scaleZ": 1.25002515
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": "",
          "ChildObjects": [
            {
              "GUID": "49d9cf",
              "Name": "Custom_Assetbundle",
              "Transform": {
                "posX": -1.46976483,
                "posY": 0.008956638,
                "posZ": -0.0437401868,
                "rotX": 359.7561,
                "rotY": 180.0035,
                "rotZ": -1.2685734E-05,
                "scaleX": 0.7999891,
                "scaleY": 1.00001287,
                "scaleZ": 0.7999471
              },
              "Nickname": "",
              "Description": "",
              "GMNotes": "",
              "AltLookAngle": {
                "x": 0.0,
                "y": 0.0,
                "z": 0.0
              },
              "ColorDiffuse": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "LayoutGroupSortIndex": 0,
              "Value": 0,
              "Locked": true,
              "Grid": true,
              "Snap": true,
              "IgnoreFoW": false,
              "MeasureMovement": false,
              "DragSelectable": true,
              "Autoraise": true,
              "Sticky": true,
              "Tooltip": true,
              "GridProjection": false,
              "HideWhenFaceDown": false,
              "Hands": false,
              "CustomAssetbundle": {
                "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
                "AssetbundleSecondaryURL": "",
                "MaterialIndex": 2,
                "TypeIndex": 1,
                "LoopingEffectIndex": 0
              },
              "LuaScript": "",
              "LuaScriptState": "",
              "XmlUI": ""
            }
          ]
        }
      ]
    },
    {
      "GUID": "aa4e95",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": -1.81088126,
        "posY": 0.01569178,
        "posZ": 0.037571,
        "rotX": 5.44979E-06,
        "rotY": 269.499969,
        "rotZ": 0.0022164823,
        "scaleX": 0.7999201,
        "scaleY": 0.9999999,
        "scaleZ": 0.401038647
      },
      "Nickname": "",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "2d4667",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": -1.94005382,
            "posY": -0.0366984,
            "posZ": 0.0241482537,
            "rotX": -2.60551053E-10,
            "rotY": 4.798938E-15,
            "rotZ": -0.002110595,
            "scaleX": 1.25001729,
            "scaleY": 1.0,
            "scaleZ": 1.25002539
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": "",
          "ChildObjects": [
            {
              "GUID": "f2635d",
              "Name": "Custom_Assetbundle",
              "Transform": {
                "posX": -1.4476639,
                "posY": 0.0367337279,
                "posZ": 0.0714720041,
                "rotX": -3.90826572E-11,
                "rotY": -1.1715962E-17,
                "rotZ": 3.4351564E-05,
                "scaleX": 0.799989,
                "scaleY": 1.0,
                "scaleZ": 0.7999835
              },
              "Nickname": "",
              "Description": "",
              "GMNotes": "",
              "AltLookAngle": {
                "x": 0.0,
                "y": 0.0,
                "z": 0.0
              },
              "ColorDiffuse": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "LayoutGroupSortIndex": 0,
              "Value": 0,
              "Locked": true,
              "Grid": true,
              "Snap": true,
              "IgnoreFoW": false,
              "MeasureMovement": false,
              "DragSelectable": true,
              "Autoraise": true,
              "Sticky": true,
              "Tooltip": true,
              "GridProjection": false,
              "HideWhenFaceDown": false,
              "Hands": false,
              "CustomAssetbundle": {
                "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
                "AssetbundleSecondaryURL": "",
                "MaterialIndex": 2,
                "TypeIndex": 1,
                "LoopingEffectIndex": 0
              },
              "LuaScript": "",
              "LuaScriptState": "",
              "XmlUI": ""
            }
          ]
        }
      ]
    },
    {
      "GUID": "e35bfc",
      "Name": "BlockSquare",
      "Transform": {
        "posX": 0.00368750119,
        "posY": -0.0051049157,
        "posZ": -2.59992743,
        "rotX": 359.5802,
        "rotY": 269.8327,
        "rotZ": 0.00140524248,
        "scaleX": 5.999804,
        "scaleY": 0.0283482671,
        "scaleZ": 6.015127
      },
      "Nickname": "Ruin (9\")  [sup]Barricade parts of this terrain feature are considered as 2\" high. Models may only be placed on the bottom level of this terrain feature[/sup]",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 0.2323997,
        "g": 0.223999679,
        "b": 0.349999726
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": ""
    }
  ]
}]],
  [[{
  "GUID": "2aca36",
  "Name": "BlockSquare",
  "Transform": {
    "posX": -4.926212,
    "posY": 1.03038824,
    "posZ": -3.07231665,
    "rotX": -3.19177911E-06,
    "rotY": 179.968933,
    "rotZ": 3.640631E-05,
    "scaleX": 4.0,
    "scaleY": 0.1,
    "scaleZ": 6.0
  },
  "Nickname": "Ruin (2\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
  "Description": "",
  "GMNotes": "",
  "AltLookAngle": {
    "x": 0.0,
    "y": 0.0,
    "z": 0.0
  },
  "ColorDiffuse": {
    "r": 0.232288122,
    "g": 0.2266227,
    "b": 0.35126254
  },
  "LayoutGroupSortIndex": 0,
  "Value": 0,
  "Locked": true,
  "Grid": true,
  "Snap": true,
  "IgnoreFoW": false,
  "MeasureMovement": true,
  "DragSelectable": true,
  "Autoraise": true,
  "Sticky": true,
  "Tooltip": true,
  "GridProjection": false,
  "HideWhenFaceDown": false,
  "Hands": false,
  "LuaScript": "\nBCBtype = \"terrain\"\n",
  "LuaScriptState": "",
  "XmlUI": "",
  "ChildObjects": [
    {
      "GUID": "d278b0",
      "Name": "Custom_Model",
      "Transform": {
        "posX": -0.342106521,
        "posY": 0.5002547,
        "posZ": 0.420916915,
        "rotX": 0.000826747855,
        "rotY": 90.12874,
        "rotZ": -0.000115829331,
        "scaleX": 0.201922491,
        "scaleY": 6.499999,
        "scaleZ": 0.249999359
      },
      "Nickname": "",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": false,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomMesh": {
        "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1660102063049489276/CC39BAD16D7046F6171B5B565BE67333FF024F50/",
        "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1660102063049466406/1E15C7A543B870999589AB951C23D29F5492B2F7/",
        "NormalURL": "",
        "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1660102063049489276/CC39BAD16D7046F6171B5B565BE67333FF024F50/",
        "Convex": false,
        "MaterialIndex": 3,
        "TypeIndex": 0,
        "CustomShader": {
          "SpecularColor": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "SpecularIntensity": 0.0,
          "SpecularSharpness": 2.0,
          "FresnelStrength": 0.0
        },
        "CastShadows": true
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "9f67af",
          "Name": "Custom_Model",
          "Transform": {
            "posX": 2.002932,
            "posY": -1.55883918E-05,
            "posZ": 0.00561213866,
            "rotX": -0.00011899956,
            "rotY": -1.10526713E-10,
            "rotZ": 0.00010643257,
            "scaleX": 1.0,
            "scaleY": 1.0,
            "scaleZ": 1.0
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": false,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1660102063049489276/CC39BAD16D7046F6171B5B565BE67333FF024F50/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1660102063049466406/1E15C7A543B870999589AB951C23D29F5492B2F7/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1660102063049489276/CC39BAD16D7046F6171B5B565BE67333FF024F50/",
            "Convex": false,
            "MaterialIndex": 3,
            "TypeIndex": 0,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        }
      ]
    },
    {
      "GUID": "1bb8b4",
      "Name": "Custom_Model",
      "Transform": {
        "posX": 0.287058562,
        "posY": 0.499547869,
        "posZ": -0.391400456,
        "rotX": 0.00117708463,
        "rotY": 180.121628,
        "rotZ": 0.000885957561,
        "scaleX": 0.313769966,
        "scaleY": 6.499999,
        "scaleZ": 0.16666688
      },
      "Nickname": "",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": false,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomMesh": {
        "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1660102063049489276/CC39BAD16D7046F6171B5B565BE67333FF024F50/",
        "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1660102063049466406/1E15C7A543B870999589AB951C23D29F5492B2F7/",
        "NormalURL": "",
        "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1660102063049489276/CC39BAD16D7046F6171B5B565BE67333FF024F50/",
        "Convex": false,
        "MaterialIndex": 3,
        "TypeIndex": 0,
        "CustomShader": {
          "SpecularColor": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "SpecularIntensity": 0.0,
          "SpecularSharpness": 2.0,
          "FresnelStrength": 0.0
        },
        "CastShadows": true
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": ""
    },
    {
      "GUID": "33d02f",
      "Name": "BlockSquare",
      "Transform": {
        "posX": 0.0004012551,
        "posY": -4.442958E-11,
        "posZ": 1.000078,
        "rotX": 5.266981E-10,
        "rotY": -0.002373651,
        "rotZ": 1.42740271E-06,
        "scaleX": 1.0,
        "scaleY": 1.0,
        "scaleZ": 1.00000012
      },
      "Nickname": "Ruin (2\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 0.232288122,
        "g": 0.2266227,
        "b": 0.35126254
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": false,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "a811d0",
          "Name": "Custom_Model",
          "Transform": {
            "posX": -0.07418283,
            "posY": 0.4624097,
            "posZ": 0.25613755,
            "rotX": 359.979248,
            "rotY": 330.025116,
            "rotZ": 0.0009494756,
            "scaleX": 0.433813274,
            "scaleY": 19.5181332,
            "scaleZ": 0.172038317
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 0.4441417,
            "g": 0.4441417,
            "b": 0.4441417
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": false,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009293027/95A2286D63E1AF7BB7CE9B8E33B5F27F9E975DDA/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009292144/9153E2B34BFF806C0F4E7EEFCD0594B21623FDC3/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009293027/95A2286D63E1AF7BB7CE9B8E33B5F27F9E975DDA/",
            "Convex": false,
            "MaterialIndex": 3,
            "TypeIndex": 0,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        }
      ]
    }
  ]
}]],
  [[{
  "GUID": "26d257",
  "Name": "Custom_Assetbundle",
  "Transform": {
    "posX": 2.5,
    "posY": 1.0691148,
    "posZ": -15.9979534,
    "rotX": 0.000504707,
    "rotY": 270.0013,
    "rotZ": 0.221591413,
    "scaleX": 1.99489665,
    "scaleY": 3.527635,
    "scaleZ": 1.00002432
  },
  "Nickname": "Ruin (9\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
  "Description": "",
  "GMNotes": "",
  "AltLookAngle": {
    "x": 0.0,
    "y": 0.0,
    "z": 0.0
  },
  "ColorDiffuse": {
    "r": 1.0,
    "g": 1.0,
    "b": 1.0
  },
  "LayoutGroupSortIndex": 0,
  "Value": 0,
  "Locked": true,
  "Grid": true,
  "Snap": true,
  "IgnoreFoW": false,
  "MeasureMovement": false,
  "DragSelectable": true,
  "Autoraise": true,
  "Sticky": true,
  "Tooltip": true,
  "GridProjection": false,
  "HideWhenFaceDown": false,
  "Hands": false,
  "CustomAssetbundle": {
    "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
    "AssetbundleSecondaryURL": "",
    "MaterialIndex": 2,
    "TypeIndex": 1,
    "LoopingEffectIndex": 0
  },
  "LuaScript": "",
  "LuaScriptState": "",
  "XmlUI": "",
  "ChildObjects": [
    {
      "GUID": "0d1b87",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": 1.76267076,
        "posY": -0.000449319079,
        "posZ": -0.01457209,
        "rotX": 0.000112515983,
        "rotY": 180.213272,
        "rotZ": 2.12263944E-06,
        "scaleX": 0.40102616,
        "scaleY": 1.0,
        "scaleZ": 0.7999697
      },
      "Nickname": "",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "f321f4",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": -0.0138203735,
            "posY": -0.008904007,
            "posZ": 1.91282463,
            "rotX": 2.52710084E-08,
            "rotY": 89.99715,
            "rotZ": -3.0327833E-06,
            "scaleX": 1.25001657,
            "scaleY": 0.9999999,
            "scaleZ": 1.25002515
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": "",
          "ChildObjects": [
            {
              "GUID": "49d9cf",
              "Name": "Custom_Assetbundle",
              "Transform": {
                "posX": -1.46976483,
                "posY": 0.008956638,
                "posZ": -0.0437401868,
                "rotX": 359.7561,
                "rotY": 180.0035,
                "rotZ": -1.2685734E-05,
                "scaleX": 0.7999891,
                "scaleY": 1.00001287,
                "scaleZ": 0.7999471
              },
              "Nickname": "",
              "Description": "",
              "GMNotes": "",
              "AltLookAngle": {
                "x": 0.0,
                "y": 0.0,
                "z": 0.0
              },
              "ColorDiffuse": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "LayoutGroupSortIndex": 0,
              "Value": 0,
              "Locked": true,
              "Grid": true,
              "Snap": true,
              "IgnoreFoW": false,
              "MeasureMovement": false,
              "DragSelectable": true,
              "Autoraise": true,
              "Sticky": true,
              "Tooltip": true,
              "GridProjection": false,
              "HideWhenFaceDown": false,
              "Hands": false,
              "CustomAssetbundle": {
                "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
                "AssetbundleSecondaryURL": "",
                "MaterialIndex": 2,
                "TypeIndex": 1,
                "LoopingEffectIndex": 0
              },
              "LuaScript": "",
              "LuaScriptState": "",
              "XmlUI": ""
            }
          ]
        }
      ]
    },
    {
      "GUID": "aa4e95",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": -1.81088126,
        "posY": 0.01569178,
        "posZ": 0.037571,
        "rotX": 5.44979E-06,
        "rotY": 269.499969,
        "rotZ": 0.0022164823,
        "scaleX": 0.7999201,
        "scaleY": 0.9999999,
        "scaleZ": 0.401038647
      },
      "Nickname": "",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "2d4667",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": -1.94005382,
            "posY": -0.0366984,
            "posZ": 0.0241482537,
            "rotX": -2.60551053E-10,
            "rotY": 4.798938E-15,
            "rotZ": -0.002110595,
            "scaleX": 1.25001729,
            "scaleY": 1.0,
            "scaleZ": 1.25002539
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": "",
          "ChildObjects": [
            {
              "GUID": "f2635d",
              "Name": "Custom_Assetbundle",
              "Transform": {
                "posX": -1.4476639,
                "posY": 0.0367337279,
                "posZ": 0.0714720041,
                "rotX": -3.90826572E-11,
                "rotY": -1.1715962E-17,
                "rotZ": 3.4351564E-05,
                "scaleX": 0.799989,
                "scaleY": 1.0,
                "scaleZ": 0.7999835
              },
              "Nickname": "",
              "Description": "",
              "GMNotes": "",
              "AltLookAngle": {
                "x": 0.0,
                "y": 0.0,
                "z": 0.0
              },
              "ColorDiffuse": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "LayoutGroupSortIndex": 0,
              "Value": 0,
              "Locked": true,
              "Grid": true,
              "Snap": true,
              "IgnoreFoW": false,
              "MeasureMovement": false,
              "DragSelectable": true,
              "Autoraise": true,
              "Sticky": true,
              "Tooltip": true,
              "GridProjection": false,
              "HideWhenFaceDown": false,
              "Hands": false,
              "CustomAssetbundle": {
                "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
                "AssetbundleSecondaryURL": "",
                "MaterialIndex": 2,
                "TypeIndex": 1,
                "LoopingEffectIndex": 0
              },
              "LuaScript": "",
              "LuaScriptState": "",
              "XmlUI": ""
            }
          ]
        }
      ]
    },
    {
      "GUID": "e35bfc",
      "Name": "BlockSquare",
      "Transform": {
        "posX": 0.00368750119,
        "posY": -0.0051049157,
        "posZ": -2.59992743,
        "rotX": 359.5802,
        "rotY": 269.8327,
        "rotZ": 0.00140524248,
        "scaleX": 5.999804,
        "scaleY": 0.0283482671,
        "scaleZ": 6.015127
      },
      "Nickname": "Ruin (9\")  [sup]Barricade parts of this terrain feature are considered as 2\" high. Models may only be placed on the bottom level of this terrain feature[/sup]",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 0.2323997,
        "g": 0.223999679,
        "b": 0.349999726
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": ""
    }
  ]
}]],
  [[{
  "GUID": "7fa314",
  "Name": "BlockSquare",
  "Transform": {
    "posX": 5.026309,
    "posY": 1.03038824,
    "posZ": 3.104753,
    "rotX": -1.067735E-07,
    "rotY": 359.992065,
    "rotZ": -7.47044453E-07,
    "scaleX": 4.0,
    "scaleY": 0.1,
    "scaleZ": 6.0
  },
  "Nickname": "Ruin (2\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
  "Description": "",
  "GMNotes": "",
  "AltLookAngle": {
    "x": 0.0,
    "y": 0.0,
    "z": 0.0
  },
  "ColorDiffuse": {
    "r": 0.232288092,
    "g": 0.226622671,
    "b": 0.3512625
  },
  "LayoutGroupSortIndex": 0,
  "Value": 0,
  "Locked": true,
  "Grid": true,
  "Snap": true,
  "IgnoreFoW": false,
  "MeasureMovement": true,
  "DragSelectable": true,
  "Autoraise": true,
  "Sticky": true,
  "Tooltip": true,
  "GridProjection": false,
  "HideWhenFaceDown": false,
  "Hands": false,
  "LuaScript": "\nBCBtype = \"terrain\"\n",
  "LuaScriptState": "",
  "XmlUI": "",
  "ChildObjects": [
    {
      "GUID": "d278b0",
      "Name": "Custom_Model",
      "Transform": {
        "posX": -0.342106521,
        "posY": 0.5002547,
        "posZ": 0.420916915,
        "rotX": 0.000826747855,
        "rotY": 90.12874,
        "rotZ": -0.000115829331,
        "scaleX": 0.201922491,
        "scaleY": 6.499999,
        "scaleZ": 0.249999359
      },
      "Nickname": "",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": false,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomMesh": {
        "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1660102063049489276/CC39BAD16D7046F6171B5B565BE67333FF024F50/",
        "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1660102063049466406/1E15C7A543B870999589AB951C23D29F5492B2F7/",
        "NormalURL": "",
        "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1660102063049489276/CC39BAD16D7046F6171B5B565BE67333FF024F50/",
        "Convex": false,
        "MaterialIndex": 3,
        "TypeIndex": 0,
        "CustomShader": {
          "SpecularColor": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "SpecularIntensity": 0.0,
          "SpecularSharpness": 2.0,
          "FresnelStrength": 0.0
        },
        "CastShadows": true
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "9f67af",
          "Name": "Custom_Model",
          "Transform": {
            "posX": 2.002932,
            "posY": -1.55883918E-05,
            "posZ": 0.00561213866,
            "rotX": -0.00011899956,
            "rotY": -1.10526713E-10,
            "rotZ": 0.00010643257,
            "scaleX": 1.0,
            "scaleY": 1.0,
            "scaleZ": 1.0
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": false,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1660102063049489276/CC39BAD16D7046F6171B5B565BE67333FF024F50/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1660102063049466406/1E15C7A543B870999589AB951C23D29F5492B2F7/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1660102063049489276/CC39BAD16D7046F6171B5B565BE67333FF024F50/",
            "Convex": false,
            "MaterialIndex": 3,
            "TypeIndex": 0,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        }
      ]
    },
    {
      "GUID": "1bb8b4",
      "Name": "Custom_Model",
      "Transform": {
        "posX": 0.287058562,
        "posY": 0.499547869,
        "posZ": -0.391400456,
        "rotX": 0.00117708463,
        "rotY": 180.121628,
        "rotZ": 0.000885957561,
        "scaleX": 0.313769966,
        "scaleY": 6.499999,
        "scaleZ": 0.16666688
      },
      "Nickname": "",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": false,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomMesh": {
        "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1660102063049489276/CC39BAD16D7046F6171B5B565BE67333FF024F50/",
        "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1660102063049466406/1E15C7A543B870999589AB951C23D29F5492B2F7/",
        "NormalURL": "",
        "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1660102063049489276/CC39BAD16D7046F6171B5B565BE67333FF024F50/",
        "Convex": false,
        "MaterialIndex": 3,
        "TypeIndex": 0,
        "CustomShader": {
          "SpecularColor": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "SpecularIntensity": 0.0,
          "SpecularSharpness": 2.0,
          "FresnelStrength": 0.0
        },
        "CastShadows": true
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": ""
    },
    {
      "GUID": "33d02f",
      "Name": "BlockSquare",
      "Transform": {
        "posX": 0.0004012551,
        "posY": -4.442958E-11,
        "posZ": 1.000078,
        "rotX": 5.266981E-10,
        "rotY": -0.002373651,
        "rotZ": 1.42740271E-06,
        "scaleX": 1.0,
        "scaleY": 1.0,
        "scaleZ": 1.00000012
      },
      "Nickname": "Ruin (2\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 0.232288122,
        "g": 0.2266227,
        "b": 0.35126254
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": false,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "a811d0",
          "Name": "Custom_Model",
          "Transform": {
            "posX": -0.07418283,
            "posY": 0.4624097,
            "posZ": 0.25613755,
            "rotX": 359.979248,
            "rotY": 330.025116,
            "rotZ": 0.0009494756,
            "scaleX": 0.433813274,
            "scaleY": 19.5181332,
            "scaleZ": 0.172038317
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 0.4441417,
            "g": 0.4441417,
            "b": 0.4441417
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": false,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009293027/95A2286D63E1AF7BB7CE9B8E33B5F27F9E975DDA/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009292144/9153E2B34BFF806C0F4E7EEFCD0594B21623FDC3/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009293027/95A2286D63E1AF7BB7CE9B8E33B5F27F9E975DDA/",
            "Convex": false,
            "MaterialIndex": 3,
            "TypeIndex": 0,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        }
      ]
    }
  ]
}]],

}

