-- FTC-GUID: 3f93b5,25933b,25983b
    -- TO CHANGE THE SIZE OF THE AREA FOR THE MAP LOADING/DELETING, READ THIS
    -- Change the zoneScale size to match a zone you create in game (as reference)
    -- Be sure the zone extends below the table too
    -- This should be the same as the Saving Tool for your table.
    -------------------------------------------------------------
    zoneScale = {x=60.12, y=73, z=44.04} --60x44 Strike Force
    -------------------------------------------------------------
    function onLoad()
        self.createButton({
            label = "Load Map",
            font_size = 115,
            color = {0, 1, 0,},
            position = {-0.96, 0.5, 0},
            rotation = {0, 90, 0},
            scale = {1.3, 1, .7},
            width = 570,
            height = 160,
            click_function = "loadMap",
            function_owner = self,
        })

        self.createButton({
            label = "Clear Map",
            font_size = 100,
            position = {1, 0.5, 0},
            rotation = {0, 90, 0},
            scale = {.6, .6, .4},
            width = 530,
            height = 130,
            color = {1, 0, 0},
            click_function = "clearMap",
            function_owner = self,
        })
    end

    -------------------
    -- Prepares the terrain saved into the card from Map Saver tool
    string.split = function(s, delimiter)
        local result = { }
        local from  = 1
        local delim_from, delim_to = string.find( s, delimiter, from  )
        while delim_from do
            table.insert( result, string.sub( s, from , delim_from-1 ) )
            from  = delim_to + 1
            delim_from, delim_to = string.find( s, delimiter, from  )
        end
        table.insert( result, string.sub( s, from  ) )
        return result
    end

	function scriptzoneCallback(zone) --This deletes everything except the things listed, when the scripting zone is briefly spawned.

        local objects = zone.getObjects()

        for i, obj in ipairs(objects) do
            ----------------------------------------------
             --IMPORTANT! Keep the map card from deleting speficic stuff here
            ----------------------------------------------
            if obj.getGMNotes() ~= "MapExclude" -- As black player, right click and add "MapExclude" to anything you dont want deleted. You may have to temporarily make your table interactable to do this, with its scripting.
                and
                obj.getGUID() ~= "e7ca6e" --Exclude Map Buidler Table
                and
                obj.getGUID() ~= "6012bf" --...and ForceOrg Table...
                and
                obj.getGUID() ~= "4ee1f2" --...and FTC board matObjSurface
                and
                obj.getGUID() ~= "948ce5" --...and FTC Table
                and
                obj.getGUID() ~= "28865a" --...and FTC Felt Surface
                then
                obj.destruct()
            end
        end
        zone.destruct()
    end
    function loadMap(objectClicked, clickerColor, altClickUsed)
        ----------
        -- Spawn the scripting zone, which uses the callback above that deletes everything then deletes itself.
        local scriptzoneParams = {                  -- Define the parameters for the scripting zone
            position = {x=0, y=26, z=0},
            scale = zoneScale,
            type = 'ScriptingTrigger',              -- Use the ScriptingTrigger type to spawn a Scripting Zone
            callback_function = scriptzoneCallback, -- Specify the function to call when the zone is created
            callback_owner = self,
            }

		spawnObject(scriptzoneParams)
		-- Then Sspawn the objects stored in the card

        Wait.time(
        function()
            for _, objectJSON in ipairs(objectJSONs) do
                -- Spawn the map from the JSON data
                spawnObjectJSON({
                    json = objectJSON
                })
            end
        end, .5)
    end

    -----------------------------
    -- This function runs when the Clear Map button is clicked on the Map Card
    function clearMap(objectClicked, clickerColor, altClickUsed)

        local scriptzoneParams = {                  -- Define the parameters for the scripting zone
            position = {x=0, y=26, z=0},
            scale = zoneScale,
            type = 'ScriptingTrigger',              -- Use the ScriptingTrigger type to spawn a Scripting Zone
            callback_function = scriptzoneCallback, -- Specify the function to call when the zone is created
            callback_owner = self,
            }

    spawnObject(scriptzoneParams)

    end


objectJSONs = {
  [[{
  "GUID": "bfd9e6",
  "Name": "BlockSquare",
  "Transform": {
    "posX": 19.0331326,
    "posY": 1.1513207,
    "posZ": 11.0443544,
    "rotX": 3.06661178E-07,
    "rotY": 89.99999,
    "rotZ": 2.42590033E-07,
    "scaleX": 9.999998,
    "scaleY": 0.1,
    "scaleZ": 5.99999952
  },
  "Nickname": "Ruin (9\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
  "Description": "",
  "GMNotes": "",
  "AltLookAngle": {
    "x": 0.0,
    "y": 0.0,
    "z": 0.0
  },
  "ColorDiffuse": {
    "r": 0.232399642,
    "g": 0.223999619,
    "b": 0.349999636
  },
  "LayoutGroupSortIndex": 0,
  "Value": 0,
  "Locked": true,
  "Grid": true,
  "Snap": true,
  "IgnoreFoW": false,
  "MeasureMovement": false,
  "DragSelectable": true,
  "Autoraise": true,
  "Sticky": true,
  "Tooltip": true,
  "GridProjection": false,
  "HideWhenFaceDown": false,
  "Hands": false,
  "LuaScript": "\nBCBtype = \"terrain\"\n",
  "LuaScriptState": "",
  "XmlUI": "",
  "ChildObjects": [
    {
      "GUID": "61c957",
      "Name": "BlockSquare",
      "Transform": {
        "posX": -0.466319919,
        "posY": 3.7741936E-06,
        "posZ": 0.00148018217,
        "rotX": 4.681715E-07,
        "rotY": 179.9873,
        "rotZ": 7.248697E-07,
        "scaleX": 0.400000066,
        "scaleY": 1.0,
        "scaleZ": 0.99999994
      },
      "Nickname": "Ruin (2\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 0.232288182,
        "g": 0.22662279,
        "b": 0.3512626
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": ""
    },
    {
      "GUID": "2d4667",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": 0.464923441,
        "posY": 0.49864623,
        "posZ": -0.200392827,
        "rotX": 0.016721854,
        "rotY": 268.751038,
        "rotZ": -0.000813133433,
        "scaleX": 0.166616231,
        "scaleY": 35.2760468,
        "scaleZ": 0.100021116
      },
      "Nickname": "",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "f2635d",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": -1.4476639,
            "posY": 0.0367337279,
            "posZ": 0.0714720041,
            "rotX": -3.90826572E-11,
            "rotY": -1.1715962E-17,
            "rotZ": 3.4351564E-05,
            "scaleX": 0.799989,
            "scaleY": 1.0,
            "scaleZ": 0.7999835
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        }
      ]
    },
    {
      "GUID": "b09707",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": 0.09718095,
        "posY": 0.500664532,
        "posZ": -0.435123265,
        "rotX": 359.993225,
        "rotY": 180.1011,
        "rotZ": -8.200698E-05,
        "scaleX": 0.199489921,
        "scaleY": 35.2763176,
        "scaleZ": 0.166670337
      },
      "Nickname": "Ruin (9\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "0d1b87",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": 1.76267242,
            "posY": 0.009350949,
            "posZ": -0.0146168517,
            "rotX": -0.0012427941,
            "rotY": 180.217087,
            "rotZ": 0.323409,
            "scaleX": 0.401016355,
            "scaleY": 1.00001383,
            "scaleZ": 0.799969137
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        },
        {
          "GUID": "aa4e95",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": -1.81066048,
            "posY": 0.0368981063,
            "posZ": 0.03800849,
            "rotX": 359.676636,
            "rotY": 269.5038,
            "rotZ": 0.0009048677,
            "scaleX": 0.799920857,
            "scaleY": 1.00001371,
            "scaleZ": 0.401028633
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        }
      ]
    }
  ]
}]],
  [[{
  "GUID": "b18337",
  "Name": "BlockSquare",
  "Transform": {
    "posX": 22.0,
    "posY": 1.05077577,
    "posZ": -13.0,
    "rotX": 3.06661121E-07,
    "rotY": 89.99999,
    "rotZ": 2.42590033E-07,
    "scaleX": 9.999998,
    "scaleY": 0.1,
    "scaleZ": 5.99999952
  },
  "Nickname": "Ruin (9\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
  "Description": "",
  "GMNotes": "",
  "AltLookAngle": {
    "x": 0.0,
    "y": 0.0,
    "z": 0.0
  },
  "ColorDiffuse": {
    "r": 0.232399672,
    "g": 0.223999649,
    "b": 0.3499997
  },
  "LayoutGroupSortIndex": 0,
  "Value": 0,
  "Locked": true,
  "Grid": true,
  "Snap": true,
  "IgnoreFoW": false,
  "MeasureMovement": false,
  "DragSelectable": true,
  "Autoraise": true,
  "Sticky": true,
  "Tooltip": true,
  "GridProjection": false,
  "HideWhenFaceDown": false,
  "Hands": false,
  "LuaScript": "\nBCBtype = \"terrain\"\n",
  "LuaScriptState": "",
  "XmlUI": "",
  "ChildObjects": [
    {
      "GUID": "61c957",
      "Name": "BlockSquare",
      "Transform": {
        "posX": -0.466319919,
        "posY": 3.7741936E-06,
        "posZ": 0.00148018217,
        "rotX": 4.681715E-07,
        "rotY": 179.9873,
        "rotZ": 7.248697E-07,
        "scaleX": 0.400000066,
        "scaleY": 1.0,
        "scaleZ": 0.99999994
      },
      "Nickname": "Ruin (2\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 0.232288182,
        "g": 0.22662279,
        "b": 0.3512626
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": ""
    },
    {
      "GUID": "2d4667",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": 0.464923441,
        "posY": 0.49864623,
        "posZ": -0.200392827,
        "rotX": 0.016721854,
        "rotY": 268.751038,
        "rotZ": -0.000813133433,
        "scaleX": 0.166616231,
        "scaleY": 35.2760468,
        "scaleZ": 0.100021116
      },
      "Nickname": "",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "f2635d",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": -1.4476639,
            "posY": 0.0367337279,
            "posZ": 0.0714720041,
            "rotX": -3.90826572E-11,
            "rotY": -1.1715962E-17,
            "rotZ": 3.4351564E-05,
            "scaleX": 0.799989,
            "scaleY": 1.0,
            "scaleZ": 0.7999835
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        }
      ]
    },
    {
      "GUID": "b09707",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": 0.09718095,
        "posY": 0.500664532,
        "posZ": -0.435123265,
        "rotX": 359.993225,
        "rotY": 180.1011,
        "rotZ": -8.200698E-05,
        "scaleX": 0.199489921,
        "scaleY": 35.2763176,
        "scaleZ": 0.166670337
      },
      "Nickname": "Ruin (9\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "0d1b87",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": 1.76267242,
            "posY": 0.009350949,
            "posZ": -0.0146168517,
            "rotX": -0.0012427941,
            "rotY": 180.217087,
            "rotZ": 0.323409,
            "scaleX": 0.401016355,
            "scaleY": 1.00001383,
            "scaleZ": 0.799969137
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        },
        {
          "GUID": "aa4e95",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": -1.81066048,
            "posY": 0.0368981063,
            "posZ": 0.03800849,
            "rotX": 359.676636,
            "rotY": 269.5038,
            "rotZ": 0.0009048677,
            "scaleX": 0.799920857,
            "scaleY": 1.00001371,
            "scaleZ": 0.401028633
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        }
      ]
    }
  ]
}]],
  [[{
  "GUID": "243dc4",
  "Name": "BlockSquare",
  "Transform": {
    "posX": 25.0034752,
    "posY": 1.050776,
    "posZ": 3.995736,
    "rotX": 2.23651568E-07,
    "rotY": 270.0,
    "rotZ": 1.084896E-06,
    "scaleX": 4.0,
    "scaleY": 0.1,
    "scaleZ": 6.0
  },
  "Nickname": "Ruin (2\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
  "Description": "",
  "GMNotes": "",
  "AltLookAngle": {
    "x": 0.0,
    "y": 0.0,
    "z": 0.0
  },
  "ColorDiffuse": {
    "r": 0.232288182,
    "g": 0.22662279,
    "b": 0.3512626
  },
  "LayoutGroupSortIndex": 0,
  "Value": 0,
  "Locked": true,
  "Grid": true,
  "Snap": true,
  "IgnoreFoW": false,
  "MeasureMovement": false,
  "DragSelectable": true,
  "Autoraise": true,
  "Sticky": true,
  "Tooltip": true,
  "GridProjection": false,
  "HideWhenFaceDown": false,
  "Hands": false,
  "LuaScript": "\nBCBtype = \"terrain\"\n",
  "LuaScriptState": "",
  "XmlUI": "",
  "ChildObjects": [
    {
      "GUID": "5465db",
      "Name": "Custom_Model",
      "Transform": {
        "posX": 0.05186952,
        "posY": -0.9508598,
        "posZ": 0.424282759,
        "rotX": 0.0241138525,
        "rotY": 90.00001,
        "rotZ": -2.22614815E-07,
        "scaleX": 0.158333316,
        "scaleY": 9.499966,
        "scaleZ": 0.14669925
      },
      "Nickname": "prison wall 3",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomMesh": {
        "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1852681510007517842/A49F5DB08B4B726084948D1FD79B7D625F24EE07/",
        "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1829033806572958162/ADFC131F71CC6446077F60F87C980A9B9DCF7C12/",
        "NormalURL": "",
        "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1852681510007517842/A49F5DB08B4B726084948D1FD79B7D625F24EE07/",
        "Convex": false,
        "MaterialIndex": 3,
        "TypeIndex": 4,
        "CustomShader": {
          "SpecularColor": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "SpecularIntensity": 0.0,
          "SpecularSharpness": 2.0,
          "FresnelStrength": 0.0
        },
        "CastShadows": true
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": ""
    },
    {
      "GUID": "3b8767",
      "Name": "Custom_Model",
      "Transform": {
        "posX": -0.3898291,
        "posY": -0.7396576,
        "posZ": -0.00557935238,
        "rotX": -2.2365154E-07,
        "rotY": 2.11742186E-15,
        "rotZ": -1.084896E-06,
        "scaleX": 0.237500012,
        "scaleY": 9.5,
        "scaleZ": 0.158333346
      },
      "Nickname": "prison wall 3",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomMesh": {
        "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1852681510007517842/A49F5DB08B4B726084948D1FD79B7D625F24EE07/",
        "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1829033806572958162/ADFC131F71CC6446077F60F87C980A9B9DCF7C12/",
        "NormalURL": "",
        "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1852681510007517842/A49F5DB08B4B726084948D1FD79B7D625F24EE07/",
        "Convex": false,
        "MaterialIndex": 3,
        "TypeIndex": 4,
        "CustomShader": {
          "SpecularColor": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "SpecularIntensity": 0.0,
          "SpecularSharpness": 2.0,
          "FresnelStrength": 0.0
        },
        "CastShadows": true
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": ""
    }
  ]
}]],
  [[{
  "GUID": "7f414f",
  "Name": "Custom_Model",
  "Transform": {
    "posX": 0.0019,
    "posY": -10.13,
    "posZ": 0.0029,
    "rotX": 0.0,
    "rotY": 0.0,
    "rotZ": 0.0,
    "scaleX": 1.666,
    "scaleY": 1.06,
    "scaleZ": 1.2206
  },
  "Nickname": "",
  "Description": "",
  "GMNotes": "",
  "AltLookAngle": {
    "x": 0.0,
    "y": 0.0,
    "z": 0.0
  },
  "ColorDiffuse": {
    "r": 1.0,
    "g": 1.0,
    "b": 1.0
  },
  "LayoutGroupSortIndex": 0,
  "Value": 0,
  "Locked": true,
  "Grid": true,
  "Snap": true,
  "IgnoreFoW": false,
  "MeasureMovement": false,
  "DragSelectable": true,
  "Autoraise": true,
  "Sticky": true,
  "Tooltip": true,
  "GridProjection": true,
  "HideWhenFaceDown": false,
  "Hands": false,
  "CustomMesh": {
    "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/879750610978796176/4A5A65543B98BCFBF57E910D06EC984208223D38/",
    "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2044114931095280776/E1E5945811D1F5CE79E1A0B1580133658FC2A9AE/",
    "NormalURL": "",
    "ColliderURL": "",
    "Convex": true,
    "MaterialIndex": 3,
    "TypeIndex": 4,
    "CustomShader": {
      "SpecularColor": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "SpecularIntensity": 0.0,
      "SpecularSharpness": 2.0,
      "FresnelStrength": 0.0
    },
    "CastShadows": true
  },
  "LuaScript": "function onload() \r\n    self.interactable = false\r\n    self.gizmo_selectable = true\r\nend",
  "LuaScriptState": "",
  "XmlUI": ""
}]],
  [[{
  "GUID": "d35254",
  "Name": "BlockSquare",
  "Transform": {
    "posX": -25.0034752,
    "posY": 1.03038788,
    "posZ": -3.995736,
    "rotX": 2.23651568E-07,
    "rotY": 90.0,
    "rotZ": 1.084896E-06,
    "scaleX": 4.0,
    "scaleY": 0.1,
    "scaleZ": 6.0
  },
  "Nickname": "Ruin (2\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
  "Description": "",
  "GMNotes": "",
  "AltLookAngle": {
    "x": 0.0,
    "y": 0.0,
    "z": 0.0
  },
  "ColorDiffuse": {
    "r": 0.232288212,
    "g": 0.22662282,
    "b": 0.351262629
  },
  "LayoutGroupSortIndex": 0,
  "Value": 0,
  "Locked": true,
  "Grid": true,
  "Snap": true,
  "IgnoreFoW": false,
  "MeasureMovement": false,
  "DragSelectable": true,
  "Autoraise": true,
  "Sticky": true,
  "Tooltip": true,
  "GridProjection": false,
  "HideWhenFaceDown": false,
  "Hands": false,
  "LuaScript": "\nBCBtype = \"terrain\"\n",
  "LuaScriptState": "",
  "XmlUI": "",
  "ChildObjects": [
    {
      "GUID": "5465db",
      "Name": "Custom_Model",
      "Transform": {
        "posX": 0.05186952,
        "posY": -0.9508598,
        "posZ": 0.424282759,
        "rotX": 0.0241138525,
        "rotY": 90.00001,
        "rotZ": -2.22614815E-07,
        "scaleX": 0.158333316,
        "scaleY": 9.499966,
        "scaleZ": 0.14669925
      },
      "Nickname": "prison wall 3",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomMesh": {
        "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1852681510007517842/A49F5DB08B4B726084948D1FD79B7D625F24EE07/",
        "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1829033806572958162/ADFC131F71CC6446077F60F87C980A9B9DCF7C12/",
        "NormalURL": "",
        "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1852681510007517842/A49F5DB08B4B726084948D1FD79B7D625F24EE07/",
        "Convex": false,
        "MaterialIndex": 3,
        "TypeIndex": 4,
        "CustomShader": {
          "SpecularColor": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "SpecularIntensity": 0.0,
          "SpecularSharpness": 2.0,
          "FresnelStrength": 0.0
        },
        "CastShadows": true
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": ""
    },
    {
      "GUID": "3b8767",
      "Name": "Custom_Model",
      "Transform": {
        "posX": -0.3898291,
        "posY": -0.7396576,
        "posZ": -0.00557935238,
        "rotX": -2.2365154E-07,
        "rotY": 2.11742186E-15,
        "rotZ": -1.084896E-06,
        "scaleX": 0.237500012,
        "scaleY": 9.5,
        "scaleZ": 0.158333346
      },
      "Nickname": "prison wall 3",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomMesh": {
        "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1852681510007517842/A49F5DB08B4B726084948D1FD79B7D625F24EE07/",
        "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1829033806572958162/ADFC131F71CC6446077F60F87C980A9B9DCF7C12/",
        "NormalURL": "",
        "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1852681510007517842/A49F5DB08B4B726084948D1FD79B7D625F24EE07/",
        "Convex": false,
        "MaterialIndex": 3,
        "TypeIndex": 4,
        "CustomShader": {
          "SpecularColor": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "SpecularIntensity": 0.0,
          "SpecularSharpness": 2.0,
          "FresnelStrength": 0.0
        },
        "CastShadows": true
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": ""
    }
  ]
}]],
  [[{
  "GUID": "084faf",
  "Name": "BlockSquare",
  "Transform": {
    "posX": -22.0,
    "posY": 1.03038776,
    "posZ": 13.0,
    "rotX": 3.066611E-07,
    "rotY": 270.0,
    "rotZ": 2.42590033E-07,
    "scaleX": 9.999998,
    "scaleY": 0.1,
    "scaleZ": 5.99999952
  },
  "Nickname": "Ruin (9\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
  "Description": "",
  "GMNotes": "",
  "AltLookAngle": {
    "x": 0.0,
    "y": 0.0,
    "z": 0.0
  },
  "ColorDiffuse": {
    "r": 0.2323997,
    "g": 0.223999679,
    "b": 0.349999726
  },
  "LayoutGroupSortIndex": 0,
  "Value": 0,
  "Locked": true,
  "Grid": true,
  "Snap": true,
  "IgnoreFoW": false,
  "MeasureMovement": false,
  "DragSelectable": true,
  "Autoraise": true,
  "Sticky": true,
  "Tooltip": true,
  "GridProjection": false,
  "HideWhenFaceDown": false,
  "Hands": false,
  "LuaScript": "\nBCBtype = \"terrain\"\n",
  "LuaScriptState": "",
  "XmlUI": "",
  "ChildObjects": [
    {
      "GUID": "61c957",
      "Name": "BlockSquare",
      "Transform": {
        "posX": -0.466319919,
        "posY": 3.7741936E-06,
        "posZ": 0.00148018217,
        "rotX": 4.681715E-07,
        "rotY": 179.9873,
        "rotZ": 7.248697E-07,
        "scaleX": 0.400000066,
        "scaleY": 1.0,
        "scaleZ": 0.99999994
      },
      "Nickname": "Ruin (2\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 0.232288182,
        "g": 0.22662279,
        "b": 0.3512626
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": ""
    },
    {
      "GUID": "2d4667",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": 0.464923441,
        "posY": 0.49864623,
        "posZ": -0.200392827,
        "rotX": 0.016721854,
        "rotY": 268.751038,
        "rotZ": -0.000813133433,
        "scaleX": 0.166616231,
        "scaleY": 35.2760468,
        "scaleZ": 0.100021116
      },
      "Nickname": "",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "f2635d",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": -1.4476639,
            "posY": 0.0367337279,
            "posZ": 0.0714720041,
            "rotX": -3.90826572E-11,
            "rotY": -1.1715962E-17,
            "rotZ": 3.4351564E-05,
            "scaleX": 0.799989,
            "scaleY": 1.0,
            "scaleZ": 0.7999835
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        }
      ]
    },
    {
      "GUID": "b09707",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": 0.09718095,
        "posY": 0.500664532,
        "posZ": -0.435123265,
        "rotX": 359.993225,
        "rotY": 180.1011,
        "rotZ": -8.200698E-05,
        "scaleX": 0.199489921,
        "scaleY": 35.2763176,
        "scaleZ": 0.166670337
      },
      "Nickname": "Ruin (9\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "0d1b87",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": 1.76267242,
            "posY": 0.009350949,
            "posZ": -0.0146168517,
            "rotX": -0.0012427941,
            "rotY": 180.217087,
            "rotZ": 0.323409,
            "scaleX": 0.401016355,
            "scaleY": 1.00001383,
            "scaleZ": 0.799969137
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        },
        {
          "GUID": "aa4e95",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": -1.81066048,
            "posY": 0.0368981063,
            "posZ": 0.03800849,
            "rotX": 359.676636,
            "rotY": 269.5038,
            "rotZ": 0.0009048677,
            "scaleX": 0.799920857,
            "scaleY": 1.00001371,
            "scaleZ": 0.401028633
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        }
      ]
    }
  ]
}]],
  [[{
  "GUID": "c6c337",
  "Name": "BlockSquare",
  "Transform": {
    "posX": -19.0331326,
    "posY": 1.13093269,
    "posZ": -11.0443544,
    "rotX": 3.066612E-07,
    "rotY": 270.0,
    "rotZ": 2.42590033E-07,
    "scaleX": 9.999998,
    "scaleY": 0.1,
    "scaleZ": 5.99999952
  },
  "Nickname": "Ruin (9\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
  "Description": "",
  "GMNotes": "",
  "AltLookAngle": {
    "x": 0.0,
    "y": 0.0,
    "z": 0.0
  },
  "ColorDiffuse": {
    "r": 0.232399672,
    "g": 0.223999649,
    "b": 0.3499997
  },
  "LayoutGroupSortIndex": 0,
  "Value": 0,
  "Locked": true,
  "Grid": true,
  "Snap": true,
  "IgnoreFoW": false,
  "MeasureMovement": false,
  "DragSelectable": true,
  "Autoraise": true,
  "Sticky": true,
  "Tooltip": true,
  "GridProjection": false,
  "HideWhenFaceDown": false,
  "Hands": false,
  "LuaScript": "\nBCBtype = \"terrain\"\n",
  "LuaScriptState": "",
  "XmlUI": "",
  "ChildObjects": [
    {
      "GUID": "61c957",
      "Name": "BlockSquare",
      "Transform": {
        "posX": -0.466319919,
        "posY": 3.7741936E-06,
        "posZ": 0.00148018217,
        "rotX": 4.681715E-07,
        "rotY": 179.9873,
        "rotZ": 7.248697E-07,
        "scaleX": 0.400000066,
        "scaleY": 1.0,
        "scaleZ": 0.99999994
      },
      "Nickname": "Ruin (2\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 0.232288182,
        "g": 0.22662279,
        "b": 0.3512626
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": ""
    },
    {
      "GUID": "2d4667",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": 0.464923441,
        "posY": 0.49864623,
        "posZ": -0.200392827,
        "rotX": 0.016721854,
        "rotY": 268.751038,
        "rotZ": -0.000813133433,
        "scaleX": 0.166616231,
        "scaleY": 35.2760468,
        "scaleZ": 0.100021116
      },
      "Nickname": "",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "f2635d",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": -1.4476639,
            "posY": 0.0367337279,
            "posZ": 0.0714720041,
            "rotX": -3.90826572E-11,
            "rotY": -1.1715962E-17,
            "rotZ": 3.4351564E-05,
            "scaleX": 0.799989,
            "scaleY": 1.0,
            "scaleZ": 0.7999835
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        }
      ]
    },
    {
      "GUID": "b09707",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": 0.09718095,
        "posY": 0.500664532,
        "posZ": -0.435123265,
        "rotX": 359.993225,
        "rotY": 180.1011,
        "rotZ": -8.200698E-05,
        "scaleX": 0.199489921,
        "scaleY": 35.2763176,
        "scaleZ": 0.166670337
      },
      "Nickname": "Ruin (9\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "0d1b87",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": 1.76267242,
            "posY": 0.009350949,
            "posZ": -0.0146168517,
            "rotX": -0.0012427941,
            "rotY": 180.217087,
            "rotZ": 0.323409,
            "scaleX": 0.401016355,
            "scaleY": 1.00001383,
            "scaleZ": 0.799969137
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        },
        {
          "GUID": "aa4e95",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": -1.81066048,
            "posY": 0.0368981063,
            "posZ": 0.03800849,
            "rotX": 359.676636,
            "rotY": 269.5038,
            "rotZ": 0.0009048677,
            "scaleX": 0.799920857,
            "scaleY": 1.00001371,
            "scaleZ": 0.401028633
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        }
      ]
    }
  ]
}]],
  [[{
  "GUID": "e35bfc",
  "Name": "BlockSquare",
  "Transform": {
    "posX": -10.52092,
    "posY": 1.04120111,
    "posZ": 0.2743094,
    "rotX": -8.233413E-09,
    "rotY": 310.999939,
    "rotZ": 0.0006618238,
    "scaleX": 6.0,
    "scaleY": 0.100000016,
    "scaleZ": 12.0
  },
  "Nickname": "Ruin (9\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
  "Description": "",
  "GMNotes": "",
  "AltLookAngle": {
    "x": 0.0,
    "y": 0.0,
    "z": 0.0
  },
  "ColorDiffuse": {
    "r": 0.2323995,
    "g": 0.22399947,
    "b": 0.3499995
  },
  "LayoutGroupSortIndex": 0,
  "Value": 0,
  "Locked": true,
  "Grid": true,
  "Snap": true,
  "IgnoreFoW": false,
  "MeasureMovement": false,
  "DragSelectable": true,
  "Autoraise": true,
  "Sticky": true,
  "Tooltip": true,
  "GridProjection": false,
  "HideWhenFaceDown": false,
  "Hands": false,
  "LuaScript": "\nBCBtype = \"terrain\"\n",
  "LuaScriptState": "",
  "XmlUI": ""
}]],
  [[{
  "GUID": "f75cac",
  "Name": "Custom_Assetbundle",
  "Transform": {
    "posX": -8.738447,
    "posY": 1.0547967,
    "posZ": 2.09542274,
    "rotX": 0.000621076848,
    "rotY": 40.60659,
    "rotZ": -9.875054E-06,
    "scaleX": 1.99489653,
    "scaleY": 3.52763486,
    "scaleZ": 1.0000242
  },
  "Nickname": "Ruin (9\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
  "Description": "",
  "GMNotes": "",
  "AltLookAngle": {
    "x": 0.0,
    "y": 0.0,
    "z": 0.0
  },
  "ColorDiffuse": {
    "r": 1.0,
    "g": 1.0,
    "b": 1.0
  },
  "LayoutGroupSortIndex": 0,
  "Value": 0,
  "Locked": true,
  "Grid": true,
  "Snap": true,
  "IgnoreFoW": false,
  "MeasureMovement": false,
  "DragSelectable": true,
  "Autoraise": true,
  "Sticky": true,
  "Tooltip": true,
  "GridProjection": false,
  "HideWhenFaceDown": false,
  "Hands": false,
  "CustomAssetbundle": {
    "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
    "AssetbundleSecondaryURL": "",
    "MaterialIndex": 2,
    "TypeIndex": 1,
    "LoopingEffectIndex": 0
  },
  "LuaScript": "\nBCBtype = \"terrain\"\n",
  "LuaScriptState": "",
  "XmlUI": "",
  "ChildObjects": [
    {
      "GUID": "0d1b87",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": 1.76267076,
        "posY": -0.000449319079,
        "posZ": -0.01457209,
        "rotX": 0.000112515983,
        "rotY": 180.213272,
        "rotZ": 2.12263944E-06,
        "scaleX": 0.40102616,
        "scaleY": 1.0,
        "scaleZ": 0.7999697
      },
      "Nickname": "",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "f321f4",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": -0.0138203735,
            "posY": -0.008904007,
            "posZ": 1.91282463,
            "rotX": 2.52710084E-08,
            "rotY": 89.99715,
            "rotZ": -3.0327833E-06,
            "scaleX": 1.25001657,
            "scaleY": 0.9999999,
            "scaleZ": 1.25002515
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": "",
          "ChildObjects": [
            {
              "GUID": "49d9cf",
              "Name": "Custom_Assetbundle",
              "Transform": {
                "posX": -1.46976483,
                "posY": 0.008956638,
                "posZ": -0.0437401868,
                "rotX": 359.7561,
                "rotY": 180.0035,
                "rotZ": -1.2685734E-05,
                "scaleX": 0.7999891,
                "scaleY": 1.00001287,
                "scaleZ": 0.7999471
              },
              "Nickname": "",
              "Description": "",
              "GMNotes": "",
              "AltLookAngle": {
                "x": 0.0,
                "y": 0.0,
                "z": 0.0
              },
              "ColorDiffuse": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "LayoutGroupSortIndex": 0,
              "Value": 0,
              "Locked": true,
              "Grid": true,
              "Snap": true,
              "IgnoreFoW": false,
              "MeasureMovement": false,
              "DragSelectable": true,
              "Autoraise": true,
              "Sticky": true,
              "Tooltip": true,
              "GridProjection": false,
              "HideWhenFaceDown": false,
              "Hands": false,
              "CustomAssetbundle": {
                "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
                "AssetbundleSecondaryURL": "",
                "MaterialIndex": 2,
                "TypeIndex": 1,
                "LoopingEffectIndex": 0
              },
              "LuaScript": "",
              "LuaScriptState": "",
              "XmlUI": ""
            }
          ]
        }
      ]
    },
    {
      "GUID": "aa4e95",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": -1.81088126,
        "posY": 0.01569178,
        "posZ": 0.037571,
        "rotX": 5.44979E-06,
        "rotY": 269.499969,
        "rotZ": 0.0022164823,
        "scaleX": 0.7999201,
        "scaleY": 0.9999999,
        "scaleZ": 0.401038647
      },
      "Nickname": "",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "2d4667",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": -1.94005382,
            "posY": -0.0366984,
            "posZ": 0.0241482537,
            "rotX": -2.60551053E-10,
            "rotY": 4.798938E-15,
            "rotZ": -0.002110595,
            "scaleX": 1.25001729,
            "scaleY": 1.0,
            "scaleZ": 1.25002539
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": "",
          "ChildObjects": [
            {
              "GUID": "f2635d",
              "Name": "Custom_Assetbundle",
              "Transform": {
                "posX": -1.4476639,
                "posY": 0.0367337279,
                "posZ": 0.0714720041,
                "rotX": -3.90826572E-11,
                "rotY": -1.1715962E-17,
                "rotZ": 3.4351564E-05,
                "scaleX": 0.799989,
                "scaleY": 1.0,
                "scaleZ": 0.7999835
              },
              "Nickname": "",
              "Description": "",
              "GMNotes": "",
              "AltLookAngle": {
                "x": 0.0,
                "y": 0.0,
                "z": 0.0
              },
              "ColorDiffuse": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "LayoutGroupSortIndex": 0,
              "Value": 0,
              "Locked": true,
              "Grid": true,
              "Snap": true,
              "IgnoreFoW": false,
              "MeasureMovement": false,
              "DragSelectable": true,
              "Autoraise": true,
              "Sticky": true,
              "Tooltip": true,
              "GridProjection": false,
              "HideWhenFaceDown": false,
              "Hands": false,
              "CustomAssetbundle": {
                "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
                "AssetbundleSecondaryURL": "",
                "MaterialIndex": 2,
                "TypeIndex": 1,
                "LoopingEffectIndex": 0
              },
              "LuaScript": "",
              "LuaScriptState": "",
              "XmlUI": ""
            }
          ]
        }
      ]
    }
  ]
}]],
  [[{
  "GUID": "3a8588",
  "Name": "BlockSquare",
  "Transform": {
    "posX": -4.996993,
    "posY": 1.05077028,
    "posZ": 15.4976273,
    "rotX": 0.00021757865,
    "rotY": 359.953247,
    "rotZ": -0.00032751105,
    "scaleX": 10.004199,
    "scaleY": 0.1,
    "scaleZ": 5.0
  },
  "Nickname": "Ruin (9\")  [sup]Barricade parts of this terrain feature are considered as 2\" high. Models may only be placed on the bottom level of this terrain feature[/sup]",
  "Description": "",
  "GMNotes": "",
  "AltLookAngle": {
    "x": 0.0,
    "y": 0.0,
    "z": 0.0
  },
  "ColorDiffuse": {
    "r": 0.232399434,
    "g": 0.223999411,
    "b": 0.349999428
  },
  "LayoutGroupSortIndex": 0,
  "Value": 0,
  "Locked": true,
  "Grid": true,
  "Snap": true,
  "IgnoreFoW": false,
  "MeasureMovement": false,
  "DragSelectable": true,
  "Autoraise": true,
  "Sticky": true,
  "Tooltip": true,
  "GridProjection": false,
  "HideWhenFaceDown": false,
  "Hands": false,
  "LuaScript": "\nBCBtype = \"terrain\"\n",
  "LuaScriptState": "",
  "XmlUI": "",
  "ChildObjects": [
    {
      "GUID": "f2a7d0",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": -0.09974817,
        "posY": 0.6778383,
        "posZ": -0.420000076,
        "rotX": 1.07729184E-05,
        "rotY": 180.0,
        "rotZ": -6.33625541E-06,
        "scaleX": 0.0799664259,
        "scaleY": 35.0,
        "scaleZ": 0.160000011
      },
      "Nickname": "Ruin",
      "Description": "You can NOT draw line of sight between the gaps in walls",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": ""
    },
    {
      "GUID": "84487a",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": -0.0967601761,
        "posY": 0.499988765,
        "posZ": -0.002801514,
        "rotX": 0.0002737262,
        "rotY": 269.995819,
        "rotZ": -2.01892526E-05,
        "scaleX": 0.22936438,
        "scaleY": 35.0000534,
        "scaleZ": 0.09995896
      },
      "Nickname": "",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": ""
    },
    {
      "GUID": "fb9714",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": 0.1788471,
        "posY": 0.4999888,
        "posZ": -0.4317932,
        "rotX": 0.000266336749,
        "rotY": 179.998566,
        "rotZ": -2.07037938E-05,
        "scaleX": 0.1486693,
        "scaleY": 35.0000534,
        "scaleZ": 0.200001866
      },
      "Nickname": "",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": ""
    },
    {
      "GUID": "1ec7ad",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": 0.450021058,
        "posY": 0.677840769,
        "posZ": -0.420000076,
        "rotX": 1.093624E-05,
        "rotY": 180.0,
        "rotZ": -9.5340265E-06,
        "scaleX": 0.0799664259,
        "scaleY": 35.0,
        "scaleZ": 0.160000011
      },
      "Nickname": "Ruin",
      "Description": "You can NOT draw line of sight between the gaps in walls",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": ""
    },
    {
      "GUID": "648368",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": -0.09974817,
        "posY": 0.811257362,
        "posZ": 0.414645761,
        "rotX": 0.000205508957,
        "rotY": 90.0,
        "rotZ": -0.00103382533,
        "scaleX": 0.160000011,
        "scaleY": 35.0,
        "scaleZ": 0.07996643
      },
      "Nickname": "Ruin",
      "Description": "You can NOT draw line of sight between the gaps in walls",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": ""
    },
    {
      "GUID": "d6f229",
      "Name": "Custom_Model",
      "Transform": {
        "posX": -0.311212033,
        "posY": 0.4695249,
        "posZ": -0.450050652,
        "rotX": 359.956451,
        "rotY": 179.483627,
        "rotZ": 0.00105330127,
        "scaleX": 0.164937377,
        "scaleY": 16.4995327,
        "scaleZ": 0.159987018
      },
      "Nickname": "",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 0.444141954,
        "g": 0.444141954,
        "b": 0.444141954
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomMesh": {
        "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009293027/95A2286D63E1AF7BB7CE9B8E33B5F27F9E975DDA/",
        "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009292144/9153E2B34BFF806C0F4E7EEFCD0594B21623FDC3/",
        "NormalURL": "",
        "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009293027/95A2286D63E1AF7BB7CE9B8E33B5F27F9E975DDA/",
        "Convex": false,
        "MaterialIndex": 3,
        "TypeIndex": 0,
        "CustomShader": {
          "SpecularColor": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "SpecularIntensity": 0.0,
          "SpecularSharpness": 2.0,
          "FresnelStrength": 0.0
        },
        "CastShadows": true
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": ""
    },
    {
      "GUID": "a811d0",
      "Name": "Custom_Model",
      "Transform": {
        "posX": -0.474871278,
        "posY": 0.46890226,
        "posZ": -0.141171828,
        "rotX": 0.00461364863,
        "rotY": 271.615753,
        "rotZ": -0.00112781359,
        "scaleX": 0.329737484,
        "scaleY": 16.4999886,
        "scaleZ": 0.0799982
      },
      "Nickname": "",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 0.444141954,
        "g": 0.444141954,
        "b": 0.444141954
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomMesh": {
        "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009293027/95A2286D63E1AF7BB7CE9B8E33B5F27F9E975DDA/",
        "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009292144/9153E2B34BFF806C0F4E7EEFCD0594B21623FDC3/",
        "NormalURL": "",
        "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009293027/95A2286D63E1AF7BB7CE9B8E33B5F27F9E975DDA/",
        "Convex": false,
        "MaterialIndex": 3,
        "TypeIndex": 0,
        "CustomShader": {
          "SpecularColor": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "SpecularIntensity": 0.0,
          "SpecularSharpness": 2.0,
          "FresnelStrength": 0.0
        },
        "CastShadows": true
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": ""
    }
  ]
}]],
  [[{
  "GUID": "a50e70",
  "Name": "BlockSquare",
  "Transform": {
    "posX": -2.99746132,
    "posY": 1.03,
    "posZ": -11.0003767,
    "rotX": 0.0,
    "rotY": 90.0,
    "rotZ": 0.0,
    "scaleX": 4.0,
    "scaleY": 0.1,
    "scaleZ": 6.0
  },
  "Nickname": "Ruin (2\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
  "Description": "",
  "GMNotes": "",
  "AltLookAngle": {
    "x": 0.0,
    "y": 0.0,
    "z": 0.0
  },
  "ColorDiffuse": {
    "r": 0.232288182,
    "g": 0.22662279,
    "b": 0.3512626
  },
  "LayoutGroupSortIndex": 0,
  "Value": 0,
  "Locked": true,
  "Grid": true,
  "Snap": true,
  "IgnoreFoW": false,
  "MeasureMovement": false,
  "DragSelectable": true,
  "Autoraise": true,
  "Sticky": true,
  "Tooltip": true,
  "GridProjection": false,
  "HideWhenFaceDown": false,
  "Hands": false,
  "LuaScript": "\nBCBtype = \"terrain\"\n",
  "LuaScriptState": "",
  "XmlUI": "",
  "ChildObjects": [
    {
      "GUID": "5465db",
      "Name": "Custom_Model",
      "Transform": {
        "posX": 0.05186952,
        "posY": -0.9508598,
        "posZ": 0.424282759,
        "rotX": 0.0241138525,
        "rotY": 90.00001,
        "rotZ": -2.22614815E-07,
        "scaleX": 0.158333316,
        "scaleY": 9.499966,
        "scaleZ": 0.14669925
      },
      "Nickname": "prison wall 3",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomMesh": {
        "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1852681510007517842/A49F5DB08B4B726084948D1FD79B7D625F24EE07/",
        "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1829033806572958162/ADFC131F71CC6446077F60F87C980A9B9DCF7C12/",
        "NormalURL": "",
        "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1852681510007517842/A49F5DB08B4B726084948D1FD79B7D625F24EE07/",
        "Convex": false,
        "MaterialIndex": 3,
        "TypeIndex": 4,
        "CustomShader": {
          "SpecularColor": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "SpecularIntensity": 0.0,
          "SpecularSharpness": 2.0,
          "FresnelStrength": 0.0
        },
        "CastShadows": true
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": ""
    },
    {
      "GUID": "3b8767",
      "Name": "Custom_Model",
      "Transform": {
        "posX": -0.3898291,
        "posY": -0.7396576,
        "posZ": -0.00557935238,
        "rotX": -2.2365154E-07,
        "rotY": 2.11742186E-15,
        "rotZ": -1.084896E-06,
        "scaleX": 0.237500012,
        "scaleY": 9.5,
        "scaleZ": 0.158333346
      },
      "Nickname": "prison wall 3",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomMesh": {
        "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1852681510007517842/A49F5DB08B4B726084948D1FD79B7D625F24EE07/",
        "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1829033806572958162/ADFC131F71CC6446077F60F87C980A9B9DCF7C12/",
        "NormalURL": "",
        "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1852681510007517842/A49F5DB08B4B726084948D1FD79B7D625F24EE07/",
        "Convex": false,
        "MaterialIndex": 3,
        "TypeIndex": 4,
        "CustomShader": {
          "SpecularColor": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "SpecularIntensity": 0.0,
          "SpecularSharpness": 2.0,
          "FresnelStrength": 0.0
        },
        "CastShadows": true
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": ""
    }
  ]
}]],
  [[{
  "GUID": "698925",
  "Name": "BlockSquare",
  "Transform": {
    "posX": 4.996993,
    "posY": 1.03038216,
    "posZ": -15.4976273,
    "rotX": 0.000217578636,
    "rotY": 179.953232,
    "rotZ": -0.00032751105,
    "scaleX": 10.004199,
    "scaleY": 0.1,
    "scaleZ": 5.0
  },
  "Nickname": "Ruin (9\")  [sup]Barricade parts of this terrain feature are considered as 2\" high. Models may only be placed on the bottom level of this terrain feature[/sup]",
  "Description": "",
  "GMNotes": "",
  "AltLookAngle": {
    "x": 0.0,
    "y": 0.0,
    "z": 0.0
  },
  "ColorDiffuse": {
    "r": 0.232399464,
    "g": 0.223999441,
    "b": 0.349999458
  },
  "LayoutGroupSortIndex": 0,
  "Value": 0,
  "Locked": true,
  "Grid": true,
  "Snap": true,
  "IgnoreFoW": false,
  "MeasureMovement": false,
  "DragSelectable": true,
  "Autoraise": true,
  "Sticky": true,
  "Tooltip": true,
  "GridProjection": false,
  "HideWhenFaceDown": false,
  "Hands": false,
  "LuaScript": "\nBCBtype = \"terrain\"\n",
  "LuaScriptState": "",
  "XmlUI": "",
  "ChildObjects": [
    {
      "GUID": "f2a7d0",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": -0.09974817,
        "posY": 0.6778383,
        "posZ": -0.420000076,
        "rotX": 1.07729184E-05,
        "rotY": 180.0,
        "rotZ": -6.33625541E-06,
        "scaleX": 0.0799664259,
        "scaleY": 35.0,
        "scaleZ": 0.160000011
      },
      "Nickname": "Ruin",
      "Description": "You can NOT draw line of sight between the gaps in walls",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": ""
    },
    {
      "GUID": "84487a",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": -0.0967601761,
        "posY": 0.499988765,
        "posZ": -0.002801514,
        "rotX": 0.0002737262,
        "rotY": 269.995819,
        "rotZ": -2.01892526E-05,
        "scaleX": 0.22936438,
        "scaleY": 35.0000534,
        "scaleZ": 0.09995896
      },
      "Nickname": "",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": ""
    },
    {
      "GUID": "fb9714",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": 0.1788471,
        "posY": 0.4999888,
        "posZ": -0.4317932,
        "rotX": 0.000266336749,
        "rotY": 179.998566,
        "rotZ": -2.07037938E-05,
        "scaleX": 0.1486693,
        "scaleY": 35.0000534,
        "scaleZ": 0.200001866
      },
      "Nickname": "",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": ""
    },
    {
      "GUID": "1ec7ad",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": 0.450021058,
        "posY": 0.677840769,
        "posZ": -0.420000076,
        "rotX": 1.093624E-05,
        "rotY": 180.0,
        "rotZ": -9.5340265E-06,
        "scaleX": 0.0799664259,
        "scaleY": 35.0,
        "scaleZ": 0.160000011
      },
      "Nickname": "Ruin",
      "Description": "You can NOT draw line of sight between the gaps in walls",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": ""
    },
    {
      "GUID": "648368",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": -0.09974817,
        "posY": 0.811257362,
        "posZ": 0.414645761,
        "rotX": 0.000205508957,
        "rotY": 90.0,
        "rotZ": -0.00103382533,
        "scaleX": 0.160000011,
        "scaleY": 35.0,
        "scaleZ": 0.07996643
      },
      "Nickname": "Ruin",
      "Description": "You can NOT draw line of sight between the gaps in walls",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": ""
    },
    {
      "GUID": "d6f229",
      "Name": "Custom_Model",
      "Transform": {
        "posX": -0.311212033,
        "posY": 0.4695249,
        "posZ": -0.450050652,
        "rotX": 359.956451,
        "rotY": 179.483627,
        "rotZ": 0.00105330127,
        "scaleX": 0.164937377,
        "scaleY": 16.4995327,
        "scaleZ": 0.159987018
      },
      "Nickname": "",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 0.444141954,
        "g": 0.444141954,
        "b": 0.444141954
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomMesh": {
        "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009293027/95A2286D63E1AF7BB7CE9B8E33B5F27F9E975DDA/",
        "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009292144/9153E2B34BFF806C0F4E7EEFCD0594B21623FDC3/",
        "NormalURL": "",
        "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009293027/95A2286D63E1AF7BB7CE9B8E33B5F27F9E975DDA/",
        "Convex": false,
        "MaterialIndex": 3,
        "TypeIndex": 0,
        "CustomShader": {
          "SpecularColor": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "SpecularIntensity": 0.0,
          "SpecularSharpness": 2.0,
          "FresnelStrength": 0.0
        },
        "CastShadows": true
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": ""
    },
    {
      "GUID": "a811d0",
      "Name": "Custom_Model",
      "Transform": {
        "posX": -0.474871278,
        "posY": 0.46890226,
        "posZ": -0.141171828,
        "rotX": 0.00461364863,
        "rotY": 271.615753,
        "rotZ": -0.00112781359,
        "scaleX": 0.329737484,
        "scaleY": 16.4999886,
        "scaleZ": 0.0799982
      },
      "Nickname": "",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 0.444141954,
        "g": 0.444141954,
        "b": 0.444141954
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomMesh": {
        "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009293027/95A2286D63E1AF7BB7CE9B8E33B5F27F9E975DDA/",
        "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009292144/9153E2B34BFF806C0F4E7EEFCD0594B21623FDC3/",
        "NormalURL": "",
        "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009293027/95A2286D63E1AF7BB7CE9B8E33B5F27F9E975DDA/",
        "Convex": false,
        "MaterialIndex": 3,
        "TypeIndex": 0,
        "CustomShader": {
          "SpecularColor": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "SpecularIntensity": 0.0,
          "SpecularSharpness": 2.0,
          "FresnelStrength": 0.0
        },
        "CastShadows": true
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": ""
    }
  ]
}]],
  [[{
  "GUID": "38748c",
  "Name": "BlockSquare",
  "Transform": {
    "posX": 2.99746132,
    "posY": 1.0503881,
    "posZ": 11.0003767,
    "rotX": 0.0,
    "rotY": 270.0,
    "rotZ": 0.0,
    "scaleX": 4.0,
    "scaleY": 0.1,
    "scaleZ": 6.0
  },
  "Nickname": "Ruin (2\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
  "Description": "",
  "GMNotes": "",
  "AltLookAngle": {
    "x": 0.0,
    "y": 0.0,
    "z": 0.0
  },
  "ColorDiffuse": {
    "r": 0.232288152,
    "g": 0.22662276,
    "b": 0.351262569
  },
  "LayoutGroupSortIndex": 0,
  "Value": 0,
  "Locked": true,
  "Grid": true,
  "Snap": true,
  "IgnoreFoW": false,
  "MeasureMovement": false,
  "DragSelectable": true,
  "Autoraise": true,
  "Sticky": true,
  "Tooltip": true,
  "GridProjection": false,
  "HideWhenFaceDown": false,
  "Hands": false,
  "LuaScript": "\nBCBtype = \"terrain\"\n",
  "LuaScriptState": "",
  "XmlUI": "",
  "ChildObjects": [
    {
      "GUID": "5465db",
      "Name": "Custom_Model",
      "Transform": {
        "posX": 0.05186952,
        "posY": -0.9508598,
        "posZ": 0.424282759,
        "rotX": 0.0241138525,
        "rotY": 90.00001,
        "rotZ": -2.22614815E-07,
        "scaleX": 0.158333316,
        "scaleY": 9.499966,
        "scaleZ": 0.14669925
      },
      "Nickname": "prison wall 3",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomMesh": {
        "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1852681510007517842/A49F5DB08B4B726084948D1FD79B7D625F24EE07/",
        "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1829033806572958162/ADFC131F71CC6446077F60F87C980A9B9DCF7C12/",
        "NormalURL": "",
        "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1852681510007517842/A49F5DB08B4B726084948D1FD79B7D625F24EE07/",
        "Convex": false,
        "MaterialIndex": 3,
        "TypeIndex": 4,
        "CustomShader": {
          "SpecularColor": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "SpecularIntensity": 0.0,
          "SpecularSharpness": 2.0,
          "FresnelStrength": 0.0
        },
        "CastShadows": true
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": ""
    },
    {
      "GUID": "3b8767",
      "Name": "Custom_Model",
      "Transform": {
        "posX": -0.3898291,
        "posY": -0.7396576,
        "posZ": -0.00557935238,
        "rotX": -2.2365154E-07,
        "rotY": 2.11742186E-15,
        "rotZ": -1.084896E-06,
        "scaleX": 0.237500012,
        "scaleY": 9.5,
        "scaleZ": 0.158333346
      },
      "Nickname": "prison wall 3",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomMesh": {
        "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1852681510007517842/A49F5DB08B4B726084948D1FD79B7D625F24EE07/",
        "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1829033806572958162/ADFC131F71CC6446077F60F87C980A9B9DCF7C12/",
        "NormalURL": "",
        "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1852681510007517842/A49F5DB08B4B726084948D1FD79B7D625F24EE07/",
        "Convex": false,
        "MaterialIndex": 3,
        "TypeIndex": 4,
        "CustomShader": {
          "SpecularColor": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "SpecularIntensity": 0.0,
          "SpecularSharpness": 2.0,
          "FresnelStrength": 0.0
        },
        "CastShadows": true
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": ""
    }
  ]
}]],
  [[{
  "GUID": "bf38b4",
  "Name": "BlockSquare",
  "Transform": {
    "posX": 10.52092,
    "posY": 1.06158924,
    "posZ": -0.2743094,
    "rotX": -8.259468E-09,
    "rotY": 130.999954,
    "rotZ": 0.0006618237,
    "scaleX": 6.0,
    "scaleY": 0.100000016,
    "scaleZ": 12.0
  },
  "Nickname": "Ruin (9\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
  "Description": "",
  "GMNotes": "",
  "AltLookAngle": {
    "x": 0.0,
    "y": 0.0,
    "z": 0.0
  },
  "ColorDiffuse": {
    "r": 0.232399464,
    "g": 0.223999441,
    "b": 0.349999458
  },
  "LayoutGroupSortIndex": 0,
  "Value": 0,
  "Locked": true,
  "Grid": true,
  "Snap": true,
  "IgnoreFoW": false,
  "MeasureMovement": false,
  "DragSelectable": true,
  "Autoraise": true,
  "Sticky": true,
  "Tooltip": true,
  "GridProjection": false,
  "HideWhenFaceDown": false,
  "Hands": false,
  "LuaScript": "\nBCBtype = \"terrain\"\n",
  "LuaScriptState": "",
  "XmlUI": ""
}]],
  [[{
  "GUID": "bfaeb7",
  "Name": "Custom_Assetbundle",
  "Transform": {
    "posX": 8.738447,
    "posY": 1.20641541,
    "posZ": -2.09542274,
    "rotX": 0.000621076848,
    "rotY": 220.6066,
    "rotZ": -9.875067E-06,
    "scaleX": 1.99489653,
    "scaleY": 3.52763486,
    "scaleZ": 1.0000242
  },
  "Nickname": "Ruin (9\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
  "Description": "",
  "GMNotes": "",
  "AltLookAngle": {
    "x": 0.0,
    "y": 0.0,
    "z": 0.0
  },
  "ColorDiffuse": {
    "r": 1.0,
    "g": 1.0,
    "b": 1.0
  },
  "LayoutGroupSortIndex": 0,
  "Value": 0,
  "Locked": true,
  "Grid": true,
  "Snap": true,
  "IgnoreFoW": false,
  "MeasureMovement": false,
  "DragSelectable": true,
  "Autoraise": true,
  "Sticky": true,
  "Tooltip": true,
  "GridProjection": false,
  "HideWhenFaceDown": false,
  "Hands": false,
  "CustomAssetbundle": {
    "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
    "AssetbundleSecondaryURL": "",
    "MaterialIndex": 2,
    "TypeIndex": 1,
    "LoopingEffectIndex": 0
  },
  "LuaScript": "\nBCBtype = \"terrain\"\n",
  "LuaScriptState": "",
  "XmlUI": "",
  "ChildObjects": [
    {
      "GUID": "0d1b87",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": 1.76267076,
        "posY": -0.000449319079,
        "posZ": -0.01457209,
        "rotX": 0.000112515983,
        "rotY": 180.213272,
        "rotZ": 2.12263944E-06,
        "scaleX": 0.40102616,
        "scaleY": 1.0,
        "scaleZ": 0.7999697
      },
      "Nickname": "",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "f321f4",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": -0.0138203735,
            "posY": -0.008904007,
            "posZ": 1.91282463,
            "rotX": 2.52710084E-08,
            "rotY": 89.99715,
            "rotZ": -3.0327833E-06,
            "scaleX": 1.25001657,
            "scaleY": 0.9999999,
            "scaleZ": 1.25002515
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": "",
          "ChildObjects": [
            {
              "GUID": "49d9cf",
              "Name": "Custom_Assetbundle",
              "Transform": {
                "posX": -1.46976483,
                "posY": 0.008956638,
                "posZ": -0.0437401868,
                "rotX": 359.7561,
                "rotY": 180.0035,
                "rotZ": -1.2685734E-05,
                "scaleX": 0.7999891,
                "scaleY": 1.00001287,
                "scaleZ": 0.7999471
              },
              "Nickname": "",
              "Description": "",
              "GMNotes": "",
              "AltLookAngle": {
                "x": 0.0,
                "y": 0.0,
                "z": 0.0
              },
              "ColorDiffuse": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "LayoutGroupSortIndex": 0,
              "Value": 0,
              "Locked": true,
              "Grid": true,
              "Snap": true,
              "IgnoreFoW": false,
              "MeasureMovement": false,
              "DragSelectable": true,
              "Autoraise": true,
              "Sticky": true,
              "Tooltip": true,
              "GridProjection": false,
              "HideWhenFaceDown": false,
              "Hands": false,
              "CustomAssetbundle": {
                "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
                "AssetbundleSecondaryURL": "",
                "MaterialIndex": 2,
                "TypeIndex": 1,
                "LoopingEffectIndex": 0
              },
              "LuaScript": "",
              "LuaScriptState": "",
              "XmlUI": ""
            }
          ]
        }
      ]
    },
    {
      "GUID": "aa4e95",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": -1.81088126,
        "posY": 0.01569178,
        "posZ": 0.037571,
        "rotX": 5.44979E-06,
        "rotY": 269.499969,
        "rotZ": 0.0022164823,
        "scaleX": 0.7999201,
        "scaleY": 0.9999999,
        "scaleZ": 0.401038647
      },
      "Nickname": "",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "2d4667",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": -1.94005382,
            "posY": -0.0366984,
            "posZ": 0.0241482537,
            "rotX": -2.60551053E-10,
            "rotY": 4.798938E-15,
            "rotZ": -0.002110595,
            "scaleX": 1.25001729,
            "scaleY": 1.0,
            "scaleZ": 1.25002539
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": "",
          "ChildObjects": [
            {
              "GUID": "f2635d",
              "Name": "Custom_Assetbundle",
              "Transform": {
                "posX": -1.4476639,
                "posY": 0.0367337279,
                "posZ": 0.0714720041,
                "rotX": -3.90826572E-11,
                "rotY": -1.1715962E-17,
                "rotZ": 3.4351564E-05,
                "scaleX": 0.799989,
                "scaleY": 1.0,
                "scaleZ": 0.7999835
              },
              "Nickname": "",
              "Description": "",
              "GMNotes": "",
              "AltLookAngle": {
                "x": 0.0,
                "y": 0.0,
                "z": 0.0
              },
              "ColorDiffuse": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "LayoutGroupSortIndex": 0,
              "Value": 0,
              "Locked": true,
              "Grid": true,
              "Snap": true,
              "IgnoreFoW": false,
              "MeasureMovement": false,
              "DragSelectable": true,
              "Autoraise": true,
              "Sticky": true,
              "Tooltip": true,
              "GridProjection": false,
              "HideWhenFaceDown": false,
              "Hands": false,
              "CustomAssetbundle": {
                "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
                "AssetbundleSecondaryURL": "",
                "MaterialIndex": 2,
                "TypeIndex": 1,
                "LoopingEffectIndex": 0
              },
              "LuaScript": "",
              "LuaScriptState": "",
              "XmlUI": ""
            }
          ]
        }
      ]
    }
  ]
}]],

}

