-- FTC-GUID: 3f93b5,25933b

    function onLoad()
        self.createButton({
            label = "Load Map",
            font_size = 115,
            color = {0, 1, 0,},
            position = {-0.96, 0.5, 0},
            rotation = {0, 90, 0},
            scale = {1.3, 1, .7},
            width = 570,
            height = 160,
            click_function = "loadMap",
            function_owner = self,
        })

        self.createButton({
            label = "Clear Map",
            font_size = 100,
            position = {1, 0.5, 0},
            rotation = {0, 90, 0},
            scale = {.6, .6, .4},
            width = 530,
            height = 130,
            color = {1, 0, 0},
            click_function = "clearMap",
            function_owner = self,
        })
    end

    -------------------
    -- Prepares the terrain saved into the card from Map Saver tool
    string.split = function(s, delimiter)
        local result = { }
        local from  = 1
        local delim_from, delim_to = string.find( s, delimiter, from  )
        while delim_from do
            table.insert( result, string.sub( s, from , delim_from-1 ) )
            from  = delim_to + 1
            delim_from, delim_to = string.find( s, delimiter, from  )
        end
        table.insert( result, string.sub( s, from  ) )
        return result
    end

	function scriptzoneCallback(zone) --This deletes everything except the things listed, when the scripting zone is briefly spawned.

        local objects = zone.getObjects()

        for i, obj in ipairs(objects) do
            if obj.getGUID() ~= "e7ca6e" --Exclude Map Buidler Table
                and
                obj.getGUID() ~= "6012bf" --...and ForceOrg Table...
                and
                obj.getGUID() ~= "4ee1f2" --...and FTC board matObjSurface
                and
                obj.getGUID() ~= "948ce5" --...and FTC Table
                and
                obj.getGUID() ~= "28865a" --...and FTC Felt Surface
                then
                obj.destruct()
            end
        end
        zone.destruct()
    end
    function loadMap(objectClicked, clickerColor, altClickUsed)
        -------------------
        -- Spawn the scripting zone, which uses the callback above that deletes everything then deletes itself.
        local scriptzoneParams = {                  -- Define the parameters for the scripting zone
            position = {x=0, y=26, z=0},
            --scale = {x=30.15, y=73, z=22.03}, --Kill Team Size
            --scale = {x=30.15, y=73, z=44.04}, --Incursion and Combat Patrol Size
            scale = {x=60.12, y=73, z=44.04}, --Strike Force Size
            --scale = {x=90.07, y=73, z=44.04}, --Onslaught Size
            type = 'ScriptingTrigger',              -- Use the ScriptingTrigger type to spawn a Scripting Zone
            callback_function = scriptzoneCallback, -- Specify the function to call when the zone is created
            callback_owner = self,
            }

		spawnObject(scriptzoneParams)
		-- Then Sspawn the objects stored in the card

        Wait.time(
        function()
            for _, objectJSON in ipairs(objectJSONs) do
                -- Spawn the map from the JSON data
                spawnObjectJSON({
                    json = objectJSON
                })
            end
        end, .5)
    end

    -----------------------------------------------------------------------------------------------------------------
    -- This function runs when the Clear Map button is clicked on the Map Card
    function clearMap(objectClicked, clickerColor, altClickUsed)

        local scriptzoneParams = {                  -- Define the parameters for the scripting zone
            position = {x=0, y=26, z=0},
            --scale = {x=30.15, y=73, z=22.03}, --Kill Team Size
            --scale = {x=30.15, y=73, z=44.04}, --Incursion and Combat Patrol Size
            scale = {x=60.12, y=73, z=44.04}, --Strike Force Size
            --scale = {x=90.07, y=73, z=44.04}, --Onslaught Size
            type = 'ScriptingTrigger',              -- Use the ScriptingTrigger type to spawn a Scripting Zone
            callback_function = scriptzoneCallback, -- Specify the function to call when the zone is created
            callback_owner = self,
            }

    spawnObject(scriptzoneParams)

    end


objectJSONs = {
  [[{
  "GUID": "7f414f",
  "Name": "Custom_Model",
  "Transform": {
    "posX": 0.0019,
    "posY": -10.13,
    "posZ": 0.0029,
    "rotX": 0.0,
    "rotY": 0.0,
    "rotZ": 0.0,
    "scaleX": 1.666,
    "scaleY": 1.06,
    "scaleZ": 1.2206
  },
  "Nickname": "",
  "Description": "",
  "GMNotes": "",
  "AltLookAngle": {
    "x": 0.0,
    "y": 0.0,
    "z": 0.0
  },
  "ColorDiffuse": {
    "r": 1.0,
    "g": 1.0,
    "b": 1.0
  },
  "LayoutGroupSortIndex": 0,
  "Value": 0,
  "Locked": true,
  "Grid": true,
  "Snap": true,
  "IgnoreFoW": false,
  "MeasureMovement": false,
  "DragSelectable": true,
  "Autoraise": true,
  "Sticky": true,
  "Tooltip": true,
  "GridProjection": true,
  "HideWhenFaceDown": false,
  "Hands": false,
  "CustomMesh": {
    "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/879750610978796176/4A5A65543B98BCFBF57E910D06EC984208223D38/",
    "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2044114931095280776/E1E5945811D1F5CE79E1A0B1580133658FC2A9AE/",
    "NormalURL": "",
    "ColliderURL": "",
    "Convex": true,
    "MaterialIndex": 3,
    "TypeIndex": 4,
    "CustomShader": {
      "SpecularColor": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "SpecularIntensity": 0.0,
      "SpecularSharpness": 2.0,
      "FresnelStrength": 0.0
    },
    "CastShadows": true
  },
  "LuaScript": "function onload() \r\n    self.interactable = false\r\n    self.gizmo_selectable = true\r\nend",
  "LuaScriptState": "",
  "XmlUI": ""
}]],

    [[{
      "GUID": "c68681",
      "Name": "BlockSquare",
      "Transform": {
        "posX": 19.0000019,
        "posY": 1.03038812,
        "posZ": 10.998045,
        "rotX": 3.77318855E-07,
        "rotY": 90.0,
        "rotZ": -8.30100248E-07,
        "scaleX": 10.0,
        "scaleY": 0.1,
        "scaleZ": 6.0
      },
      "Nickname": "Ruin (9\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 0.232399642,
        "g": 0.223999619,
        "b": 0.349999636
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "92cd36",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": 0.449801177,
            "posY": 0.811220467,
            "posZ": 0.0833364353,
            "rotX": -0.00016311364,
            "rotY": 269.9985,
            "rotZ": 1.68801562E-05,
            "scaleX": 0.1666667,
            "scaleY": 35.0,
            "scaleZ": 0.100000024
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": "",
          "ChildObjects": [
            {
              "GUID": "1256e4",
              "Name": "Custom_Assetbundle",
              "Transform": {
                "posX": -2.99999118,
                "posY": 2.2406175E-07,
                "posZ": 2.8902914E-05,
                "rotX": -0.000156078939,
                "rotY": 89.95388,
                "rotZ": 0.000159497518,
                "scaleX": 1.0,
                "scaleY": 0.99999994,
                "scaleZ": 1.0
              },
              "Nickname": "",
              "Description": "",
              "GMNotes": "",
              "AltLookAngle": {
                "x": 0.0,
                "y": 0.0,
                "z": 0.0
              },
              "ColorDiffuse": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "LayoutGroupSortIndex": 0,
              "Value": 0,
              "Locked": true,
              "Grid": true,
              "Snap": true,
              "IgnoreFoW": false,
              "MeasureMovement": false,
              "DragSelectable": true,
              "Autoraise": true,
              "Sticky": true,
              "Tooltip": true,
              "GridProjection": false,
              "HideWhenFaceDown": false,
              "Hands": false,
              "CustomAssetbundle": {
                "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
                "AssetbundleSecondaryURL": "",
                "MaterialIndex": 2,
                "TypeIndex": 1,
                "LoopingEffectIndex": 0
              },
              "LuaScript": "",
              "LuaScriptState": "",
              "XmlUI": "",
              "ChildObjects": [
                {
                  "GUID": "d52df9",
                  "Name": "Custom_Assetbundle",
                  "Transform": {
                    "posX": 0.0313409381,
                    "posY": -0.008889672,
                    "posZ": 1.49354625,
                    "rotX": 0.000266103656,
                    "rotY": 270.049561,
                    "rotZ": -0.000201176765,
                    "scaleX": 0.777184,
                    "scaleY": 1.00000012,
                    "scaleZ": 1.00002337
                  },
                  "Nickname": "",
                  "Description": "",
                  "GMNotes": "",
                  "AltLookAngle": {
                    "x": 0.0,
                    "y": 0.0,
                    "z": 0.0
                  },
                  "ColorDiffuse": {
                    "r": 1.0,
                    "g": 1.0,
                    "b": 1.0
                  },
                  "LayoutGroupSortIndex": 0,
                  "Value": 0,
                  "Locked": true,
                  "Grid": true,
                  "Snap": true,
                  "IgnoreFoW": false,
                  "MeasureMovement": false,
                  "DragSelectable": true,
                  "Autoraise": true,
                  "Sticky": true,
                  "Tooltip": true,
                  "GridProjection": false,
                  "HideWhenFaceDown": false,
                  "Hands": false,
                  "CustomAssetbundle": {
                    "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
                    "AssetbundleSecondaryURL": "",
                    "MaterialIndex": 2,
                    "TypeIndex": 1,
                    "LoopingEffectIndex": 0
                  },
                  "LuaScript": "",
                  "LuaScriptState": "",
                  "XmlUI": ""
                }
              ]
            },
            {
              "GUID": "0d8636",
              "Name": "Custom_Assetbundle",
              "Transform": {
                "posX": -2.99680734,
                "posY": -0.008882681,
                "posZ": 4.613297,
                "rotX": 1.72515083E-05,
                "rotY": 90.0015,
                "rotZ": 0.000231667233,
                "scaleX": 2.59712434,
                "scaleY": 0.99999994,
                "scaleZ": 1.00001407
              },
              "Nickname": "",
              "Description": "",
              "GMNotes": "",
              "AltLookAngle": {
                "x": 0.0,
                "y": 0.0,
                "z": 0.0
              },
              "ColorDiffuse": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "LayoutGroupSortIndex": 0,
              "Value": 0,
              "Locked": true,
              "Grid": true,
              "Snap": true,
              "IgnoreFoW": false,
              "MeasureMovement": false,
              "DragSelectable": true,
              "Autoraise": true,
              "Sticky": true,
              "Tooltip": true,
              "GridProjection": false,
              "HideWhenFaceDown": false,
              "Hands": false,
              "CustomAssetbundle": {
                "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
                "AssetbundleSecondaryURL": "",
                "MaterialIndex": 2,
                "TypeIndex": 1,
                "LoopingEffectIndex": 0
              },
              "LuaScript": "",
              "LuaScriptState": "",
              "XmlUI": "",
              "ChildObjects": [
                {
                  "GUID": "c8cce0",
                  "Name": "Custom_Assetbundle",
                  "Transform": {
                    "posX": -1.68906009,
                    "posY": 0.008880546,
                    "posZ": -0.003016905,
                    "rotX": -0.00014031661,
                    "rotY": 0.0148829827,
                    "rotZ": -5.062408E-05,
                    "scaleX": 0.385041267,
                    "scaleY": 0.99999994,
                    "scaleZ": 0.9999859
                  },
                  "Nickname": "",
                  "Description": "",
                  "GMNotes": "",
                  "AltLookAngle": {
                    "x": 0.0,
                    "y": 0.0,
                    "z": 0.0
                  },
                  "ColorDiffuse": {
                    "r": 1.0,
                    "g": 1.0,
                    "b": 1.0
                  },
                  "LayoutGroupSortIndex": 0,
                  "Value": 0,
                  "Locked": false,
                  "Grid": true,
                  "Snap": true,
                  "IgnoreFoW": false,
                  "MeasureMovement": false,
                  "DragSelectable": true,
                  "Autoraise": true,
                  "Sticky": true,
                  "Tooltip": true,
                  "GridProjection": false,
                  "HideWhenFaceDown": false,
                  "Hands": false,
                  "CustomAssetbundle": {
                    "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
                    "AssetbundleSecondaryURL": "",
                    "MaterialIndex": 2,
                    "TypeIndex": 1,
                    "LoopingEffectIndex": 0
                  },
                  "LuaScript": "",
                  "LuaScriptState": "",
                  "XmlUI": ""
                }
              ]
            }
          ]
        }
      ]
    }]],
    [[{
      "GUID": "524973",
      "Name": "BlockSquare",
      "Transform": {
        "posX": 25.0034752,
        "posY": 1.03038788,
        "posZ": 3.99573612,
        "rotX": 2.61128946E-07,
        "rotY": 270.0,
        "rotZ": 1.461016E-07,
        "scaleX": 4.0,
        "scaleY": 0.1,
        "scaleZ": 6.0
      },
      "Nickname": "Ruin (2\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 0.2322883,
        "g": 0.226622909,
        "b": 0.351262718
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "5465db",
          "Name": "Custom_Model",
          "Transform": {
            "posX": 0.05186952,
            "posY": -0.9508598,
            "posZ": 0.424282759,
            "rotX": 0.0241138525,
            "rotY": 90.00001,
            "rotZ": -2.22614815E-07,
            "scaleX": 0.158333316,
            "scaleY": 9.499966,
            "scaleZ": 0.14669925
          },
          "Nickname": "prison wall 3",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1852681510007517842/A49F5DB08B4B726084948D1FD79B7D625F24EE07/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1829033806572958162/ADFC131F71CC6446077F60F87C980A9B9DCF7C12/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1852681510007517842/A49F5DB08B4B726084948D1FD79B7D625F24EE07/",
            "Convex": false,
            "MaterialIndex": 3,
            "TypeIndex": 4,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        },
        {
          "GUID": "3b8767",
          "Name": "Custom_Model",
          "Transform": {
            "posX": -0.3898291,
            "posY": -0.7396576,
            "posZ": -0.00557935238,
            "rotX": -2.2365154E-07,
            "rotY": 2.11742186E-15,
            "rotZ": -1.084896E-06,
            "scaleX": 0.237500012,
            "scaleY": 9.5,
            "scaleZ": 0.158333346
          },
          "Nickname": "prison wall 3",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1852681510007517842/A49F5DB08B4B726084948D1FD79B7D625F24EE07/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1829033806572958162/ADFC131F71CC6446077F60F87C980A9B9DCF7C12/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1852681510007517842/A49F5DB08B4B726084948D1FD79B7D625F24EE07/",
            "Convex": false,
            "MaterialIndex": 3,
            "TypeIndex": 4,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        }
      ]
    }]],
    [[{
      "GUID": "d35254",
      "Name": "BlockSquare",
      "Transform": {
        "posX": -25.0034752,
        "posY": 1.03038788,
        "posZ": -3.995736,
        "rotX": 2.23651568E-07,
        "rotY": 90.0,
        "rotZ": 1.084896E-06,
        "scaleX": 4.0,
        "scaleY": 0.1,
        "scaleZ": 6.0
      },
      "Nickname": "Ruin (2\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 0.232288331,
        "g": 0.226622939,
        "b": 0.351262748
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "5465db",
          "Name": "Custom_Model",
          "Transform": {
            "posX": 0.05186952,
            "posY": -0.9508598,
            "posZ": 0.424282759,
            "rotX": 0.0241138525,
            "rotY": 90.00001,
            "rotZ": -2.22614815E-07,
            "scaleX": 0.158333316,
            "scaleY": 9.499966,
            "scaleZ": 0.14669925
          },
          "Nickname": "prison wall 3",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1852681510007517842/A49F5DB08B4B726084948D1FD79B7D625F24EE07/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1829033806572958162/ADFC131F71CC6446077F60F87C980A9B9DCF7C12/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1852681510007517842/A49F5DB08B4B726084948D1FD79B7D625F24EE07/",
            "Convex": false,
            "MaterialIndex": 3,
            "TypeIndex": 4,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        },
        {
          "GUID": "3b8767",
          "Name": "Custom_Model",
          "Transform": {
            "posX": -0.3898291,
            "posY": -0.7396576,
            "posZ": -0.00557935238,
            "rotX": -2.2365154E-07,
            "rotY": 2.11742186E-15,
            "rotZ": -1.084896E-06,
            "scaleX": 0.237500012,
            "scaleY": 9.5,
            "scaleZ": 0.158333346
          },
          "Nickname": "prison wall 3",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1852681510007517842/A49F5DB08B4B726084948D1FD79B7D625F24EE07/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1829033806572958162/ADFC131F71CC6446077F60F87C980A9B9DCF7C12/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1852681510007517842/A49F5DB08B4B726084948D1FD79B7D625F24EE07/",
            "Convex": false,
            "MaterialIndex": 3,
            "TypeIndex": 4,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        }
      ]
    }]],
    [[{
      "GUID": "ff9002",
      "Name": "BlockSquare",
      "Transform": {
        "posX": -19.0,
        "posY": 1.030388,
        "posZ": -10.9980431,
        "rotX": -3.756165E-07,
        "rotY": 270.0,
        "rotZ": -7.450388E-08,
        "scaleX": 10.0,
        "scaleY": 0.1,
        "scaleZ": 6.0
      },
      "Nickname": "Ruin (9\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 0.232399672,
        "g": 0.223999649,
        "b": 0.3499997
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "92cd36",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": 0.449801177,
            "posY": 0.811220467,
            "posZ": 0.0833364353,
            "rotX": -0.00016311364,
            "rotY": 269.9985,
            "rotZ": 1.68801562E-05,
            "scaleX": 0.1666667,
            "scaleY": 35.0,
            "scaleZ": 0.100000024
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": "",
          "ChildObjects": [
            {
              "GUID": "1256e4",
              "Name": "Custom_Assetbundle",
              "Transform": {
                "posX": -2.99999118,
                "posY": 2.2406175E-07,
                "posZ": 2.8902914E-05,
                "rotX": -0.000156078939,
                "rotY": 89.95388,
                "rotZ": 0.000159497518,
                "scaleX": 1.0,
                "scaleY": 0.99999994,
                "scaleZ": 1.0
              },
              "Nickname": "",
              "Description": "",
              "GMNotes": "",
              "AltLookAngle": {
                "x": 0.0,
                "y": 0.0,
                "z": 0.0
              },
              "ColorDiffuse": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "LayoutGroupSortIndex": 0,
              "Value": 0,
              "Locked": true,
              "Grid": true,
              "Snap": true,
              "IgnoreFoW": false,
              "MeasureMovement": false,
              "DragSelectable": true,
              "Autoraise": true,
              "Sticky": true,
              "Tooltip": true,
              "GridProjection": false,
              "HideWhenFaceDown": false,
              "Hands": false,
              "CustomAssetbundle": {
                "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
                "AssetbundleSecondaryURL": "",
                "MaterialIndex": 2,
                "TypeIndex": 1,
                "LoopingEffectIndex": 0
              },
              "LuaScript": "",
              "LuaScriptState": "",
              "XmlUI": "",
              "ChildObjects": [
                {
                  "GUID": "d52df9",
                  "Name": "Custom_Assetbundle",
                  "Transform": {
                    "posX": 0.0313409381,
                    "posY": -0.008889672,
                    "posZ": 1.49354625,
                    "rotX": 0.000266103656,
                    "rotY": 270.049561,
                    "rotZ": -0.000201176765,
                    "scaleX": 0.777184,
                    "scaleY": 1.00000012,
                    "scaleZ": 1.00002337
                  },
                  "Nickname": "",
                  "Description": "",
                  "GMNotes": "",
                  "AltLookAngle": {
                    "x": 0.0,
                    "y": 0.0,
                    "z": 0.0
                  },
                  "ColorDiffuse": {
                    "r": 1.0,
                    "g": 1.0,
                    "b": 1.0
                  },
                  "LayoutGroupSortIndex": 0,
                  "Value": 0,
                  "Locked": true,
                  "Grid": true,
                  "Snap": true,
                  "IgnoreFoW": false,
                  "MeasureMovement": false,
                  "DragSelectable": true,
                  "Autoraise": true,
                  "Sticky": true,
                  "Tooltip": true,
                  "GridProjection": false,
                  "HideWhenFaceDown": false,
                  "Hands": false,
                  "CustomAssetbundle": {
                    "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
                    "AssetbundleSecondaryURL": "",
                    "MaterialIndex": 2,
                    "TypeIndex": 1,
                    "LoopingEffectIndex": 0
                  },
                  "LuaScript": "",
                  "LuaScriptState": "",
                  "XmlUI": ""
                }
              ]
            },
            {
              "GUID": "0d8636",
              "Name": "Custom_Assetbundle",
              "Transform": {
                "posX": -2.99680734,
                "posY": -0.008882681,
                "posZ": 4.613297,
                "rotX": 1.72515083E-05,
                "rotY": 90.0015,
                "rotZ": 0.000231667233,
                "scaleX": 2.59712434,
                "scaleY": 0.99999994,
                "scaleZ": 1.00001407
              },
              "Nickname": "",
              "Description": "",
              "GMNotes": "",
              "AltLookAngle": {
                "x": 0.0,
                "y": 0.0,
                "z": 0.0
              },
              "ColorDiffuse": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "LayoutGroupSortIndex": 0,
              "Value": 0,
              "Locked": true,
              "Grid": true,
              "Snap": true,
              "IgnoreFoW": false,
              "MeasureMovement": false,
              "DragSelectable": true,
              "Autoraise": true,
              "Sticky": true,
              "Tooltip": true,
              "GridProjection": false,
              "HideWhenFaceDown": false,
              "Hands": false,
              "CustomAssetbundle": {
                "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
                "AssetbundleSecondaryURL": "",
                "MaterialIndex": 2,
                "TypeIndex": 1,
                "LoopingEffectIndex": 0
              },
              "LuaScript": "",
              "LuaScriptState": "",
              "XmlUI": "",
              "ChildObjects": [
                {
                  "GUID": "c8cce0",
                  "Name": "Custom_Assetbundle",
                  "Transform": {
                    "posX": -1.68906009,
                    "posY": 0.008880546,
                    "posZ": -0.003016905,
                    "rotX": -0.00014031661,
                    "rotY": 0.0148829827,
                    "rotZ": -5.062408E-05,
                    "scaleX": 0.385041267,
                    "scaleY": 0.99999994,
                    "scaleZ": 0.9999859
                  },
                  "Nickname": "",
                  "Description": "",
                  "GMNotes": "",
                  "AltLookAngle": {
                    "x": 0.0,
                    "y": 0.0,
                    "z": 0.0
                  },
                  "ColorDiffuse": {
                    "r": 1.0,
                    "g": 1.0,
                    "b": 1.0
                  },
                  "LayoutGroupSortIndex": 0,
                  "Value": 0,
                  "Locked": false,
                  "Grid": true,
                  "Snap": true,
                  "IgnoreFoW": false,
                  "MeasureMovement": false,
                  "DragSelectable": true,
                  "Autoraise": true,
                  "Sticky": true,
                  "Tooltip": true,
                  "GridProjection": false,
                  "HideWhenFaceDown": false,
                  "Hands": false,
                  "CustomAssetbundle": {
                    "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
                    "AssetbundleSecondaryURL": "",
                    "MaterialIndex": 2,
                    "TypeIndex": 1,
                    "LoopingEffectIndex": 0
                  },
                  "LuaScript": "",
                  "LuaScriptState": "",
                  "XmlUI": ""
                }
              ]
            }
          ]
        }
      ]
    }]],
    [[{
      "GUID": "089fa1",
      "Name": "BlockSquare",
      "Transform": {
        "posX": -5.00209427,
        "posY": 1.03031993,
        "posZ": 15.4999971,
        "rotX": 0.0006012109,
        "rotY": 359.935883,
        "rotZ": -0.000919850543,
        "scaleX": 10.004199,
        "scaleY": 0.1,
        "scaleZ": 5.0
      },
      "Nickname": "Ruin (9\")  [sup]Barricade parts of this terrain feature are considered as 2\" high. Models may only be placed on the bottom level of this terrain feature[/sup]",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 0.232399613,
        "g": 0.22399959,
        "b": 0.3499996
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "f2a7d0",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": -0.09974817,
            "posY": 0.6778383,
            "posZ": -0.420000076,
            "rotX": 1.07729184E-05,
            "rotY": 180.0,
            "rotZ": -6.33625541E-06,
            "scaleX": 0.0799664259,
            "scaleY": 35.0,
            "scaleZ": 0.160000011
          },
          "Nickname": "Ruin",
          "Description": "You can NOT draw line of sight between the gaps in walls",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "\nBCBtype = \"terrain\"\n",
          "LuaScriptState": "",
          "XmlUI": ""
        },
        {
          "GUID": "84487a",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": -0.0967601761,
            "posY": 0.499988765,
            "posZ": -0.002801514,
            "rotX": 0.0002737262,
            "rotY": 269.995819,
            "rotZ": -2.01892526E-05,
            "scaleX": 0.22936438,
            "scaleY": 35.0000534,
            "scaleZ": 0.09995896
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        },
        {
          "GUID": "fb9714",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": 0.1788471,
            "posY": 0.4999888,
            "posZ": -0.4317932,
            "rotX": 0.000266336749,
            "rotY": 179.998566,
            "rotZ": -2.07037938E-05,
            "scaleX": 0.1486693,
            "scaleY": 35.0000534,
            "scaleZ": 0.200001866
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        },
        {
          "GUID": "1ec7ad",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": 0.450021058,
            "posY": 0.677840769,
            "posZ": -0.420000076,
            "rotX": 1.093624E-05,
            "rotY": 180.0,
            "rotZ": -9.5340265E-06,
            "scaleX": 0.0799664259,
            "scaleY": 35.0,
            "scaleZ": 0.160000011
          },
          "Nickname": "Ruin",
          "Description": "You can NOT draw line of sight between the gaps in walls",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "\nBCBtype = \"terrain\"\n",
          "LuaScriptState": "",
          "XmlUI": ""
        },
        {
          "GUID": "648368",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": -0.09974817,
            "posY": 0.811257362,
            "posZ": 0.414645761,
            "rotX": 0.000205508957,
            "rotY": 90.0,
            "rotZ": -0.00103382533,
            "scaleX": 0.160000011,
            "scaleY": 35.0,
            "scaleZ": 0.07996643
          },
          "Nickname": "Ruin",
          "Description": "You can NOT draw line of sight between the gaps in walls",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "\nBCBtype = \"terrain\"\n",
          "LuaScriptState": "",
          "XmlUI": ""
        },
        {
          "GUID": "b21c07",
          "Name": "Custom_Model",
          "Transform": {
            "posX": -0.473036766,
            "posY": 0.474120915,
            "posZ": -0.141439483,
            "rotX": -2.097335E-05,
            "rotY": 270.085083,
            "rotZ": -1.08989216E-05,
            "scaleX": 0.3299993,
            "scaleY": 16.5,
            "scaleZ": 0.07996651
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 0.444141954,
            "g": 0.444141954,
            "b": 0.444141954
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009293027/95A2286D63E1AF7BB7CE9B8E33B5F27F9E975DDA/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009292144/9153E2B34BFF806C0F4E7EEFCD0594B21623FDC3/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009293027/95A2286D63E1AF7BB7CE9B8E33B5F27F9E975DDA/",
            "Convex": false,
            "MaterialIndex": 3,
            "TypeIndex": 0,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        },
        {
          "GUID": "f635cf",
          "Name": "Custom_Model",
          "Transform": {
            "posX": -0.31176427,
            "posY": 0.4740541,
            "posZ": -0.44883424,
            "rotX": 0.0006022117,
            "rotY": 180.062454,
            "rotZ": -0.0009191112,
            "scaleX": 0.164930835,
            "scaleY": 16.5,
            "scaleZ": 0.159999788
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 0.444141954,
            "g": 0.444141954,
            "b": 0.444141954
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009293027/95A2286D63E1AF7BB7CE9B8E33B5F27F9E975DDA/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009292144/9153E2B34BFF806C0F4E7EEFCD0594B21623FDC3/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009293027/95A2286D63E1AF7BB7CE9B8E33B5F27F9E975DDA/",
            "Convex": false,
            "MaterialIndex": 3,
            "TypeIndex": 0,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        }
      ]
    }]],
    [[{
      "GUID": "a50e70",
      "Name": "BlockSquare",
      "Transform": {
        "posX": -2.99746132,
        "posY": 1.03,
        "posZ": -11.0003767,
        "rotX": 0.0,
        "rotY": 90.0,
        "rotZ": 0.0,
        "scaleX": 4.0,
        "scaleY": 0.1,
        "scaleZ": 6.0
      },
      "Nickname": "Ruin (2\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 0.2322883,
        "g": 0.226622909,
        "b": 0.351262718
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "5465db",
          "Name": "Custom_Model",
          "Transform": {
            "posX": 0.05186952,
            "posY": -0.9508598,
            "posZ": 0.424282759,
            "rotX": 0.0241138525,
            "rotY": 90.00001,
            "rotZ": -2.22614815E-07,
            "scaleX": 0.158333316,
            "scaleY": 9.499966,
            "scaleZ": 0.14669925
          },
          "Nickname": "prison wall 3",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1852681510007517842/A49F5DB08B4B726084948D1FD79B7D625F24EE07/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1829033806572958162/ADFC131F71CC6446077F60F87C980A9B9DCF7C12/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1852681510007517842/A49F5DB08B4B726084948D1FD79B7D625F24EE07/",
            "Convex": false,
            "MaterialIndex": 3,
            "TypeIndex": 4,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        },
        {
          "GUID": "3b8767",
          "Name": "Custom_Model",
          "Transform": {
            "posX": -0.3898291,
            "posY": -0.7396576,
            "posZ": -0.00557935238,
            "rotX": -2.2365154E-07,
            "rotY": 2.11742186E-15,
            "rotZ": -1.084896E-06,
            "scaleX": 0.237500012,
            "scaleY": 9.5,
            "scaleZ": 0.158333346
          },
          "Nickname": "prison wall 3",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1852681510007517842/A49F5DB08B4B726084948D1FD79B7D625F24EE07/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1829033806572958162/ADFC131F71CC6446077F60F87C980A9B9DCF7C12/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1852681510007517842/A49F5DB08B4B726084948D1FD79B7D625F24EE07/",
            "Convex": false,
            "MaterialIndex": 3,
            "TypeIndex": 4,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        }
      ]
    }]],
    [[{
      "GUID": "698925",
      "Name": "BlockSquare",
      "Transform": {
        "posX": 4.996993,
        "posY": 1.03038216,
        "posZ": -15.4976273,
        "rotX": 0.000217578636,
        "rotY": 179.953232,
        "rotZ": -0.00032751105,
        "scaleX": 10.004199,
        "scaleY": 0.1,
        "scaleZ": 5.0
      },
      "Nickname": "Ruin (9\")  [sup]Barricade parts of this terrain feature are considered as 2\" high. Models may only be placed on the bottom level of this terrain feature[/sup]",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 0.232399583,
        "g": 0.22399956,
        "b": 0.349999577
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "f2a7d0",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": -0.09974817,
            "posY": 0.6778383,
            "posZ": -0.420000076,
            "rotX": 1.07729184E-05,
            "rotY": 180.0,
            "rotZ": -6.33625541E-06,
            "scaleX": 0.0799664259,
            "scaleY": 35.0,
            "scaleZ": 0.160000011
          },
          "Nickname": "Ruin",
          "Description": "You can NOT draw line of sight between the gaps in walls",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "\nBCBtype = \"terrain\"\n",
          "LuaScriptState": "",
          "XmlUI": ""
        },
        {
          "GUID": "84487a",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": -0.0967601761,
            "posY": 0.499988765,
            "posZ": -0.002801514,
            "rotX": 0.0002737262,
            "rotY": 269.995819,
            "rotZ": -2.01892526E-05,
            "scaleX": 0.22936438,
            "scaleY": 35.0000534,
            "scaleZ": 0.09995896
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        },
        {
          "GUID": "fb9714",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": 0.1788471,
            "posY": 0.4999888,
            "posZ": -0.4317932,
            "rotX": 0.000266336749,
            "rotY": 179.998566,
            "rotZ": -2.07037938E-05,
            "scaleX": 0.1486693,
            "scaleY": 35.0000534,
            "scaleZ": 0.200001866
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        },
        {
          "GUID": "1ec7ad",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": 0.450021058,
            "posY": 0.677840769,
            "posZ": -0.420000076,
            "rotX": 1.093624E-05,
            "rotY": 180.0,
            "rotZ": -9.5340265E-06,
            "scaleX": 0.0799664259,
            "scaleY": 35.0,
            "scaleZ": 0.160000011
          },
          "Nickname": "Ruin",
          "Description": "You can NOT draw line of sight between the gaps in walls",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "\nBCBtype = \"terrain\"\n",
          "LuaScriptState": "",
          "XmlUI": ""
        },
        {
          "GUID": "648368",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": -0.09974817,
            "posY": 0.811257362,
            "posZ": 0.414645761,
            "rotX": 0.000205508957,
            "rotY": 90.0,
            "rotZ": -0.00103382533,
            "scaleX": 0.160000011,
            "scaleY": 35.0,
            "scaleZ": 0.07996643
          },
          "Nickname": "Ruin",
          "Description": "You can NOT draw line of sight between the gaps in walls",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "\nBCBtype = \"terrain\"\n",
          "LuaScriptState": "",
          "XmlUI": ""
        },
        {
          "GUID": "d6f229",
          "Name": "Custom_Model",
          "Transform": {
            "posX": -0.311212033,
            "posY": 0.4695249,
            "posZ": -0.450050652,
            "rotX": 359.956451,
            "rotY": 179.483627,
            "rotZ": 0.00105330127,
            "scaleX": 0.164937377,
            "scaleY": 16.4995327,
            "scaleZ": 0.159987018
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 0.444141954,
            "g": 0.444141954,
            "b": 0.444141954
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009293027/95A2286D63E1AF7BB7CE9B8E33B5F27F9E975DDA/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009292144/9153E2B34BFF806C0F4E7EEFCD0594B21623FDC3/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009293027/95A2286D63E1AF7BB7CE9B8E33B5F27F9E975DDA/",
            "Convex": false,
            "MaterialIndex": 3,
            "TypeIndex": 0,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        },
        {
          "GUID": "a811d0",
          "Name": "Custom_Model",
          "Transform": {
            "posX": -0.474871278,
            "posY": 0.46890226,
            "posZ": -0.141171828,
            "rotX": 0.00461364863,
            "rotY": 271.615753,
            "rotZ": -0.00112781359,
            "scaleX": 0.329737484,
            "scaleY": 16.4999886,
            "scaleZ": 0.0799982
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 0.444141954,
            "g": 0.444141954,
            "b": 0.444141954
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009293027/95A2286D63E1AF7BB7CE9B8E33B5F27F9E975DDA/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009292144/9153E2B34BFF806C0F4E7EEFCD0594B21623FDC3/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009293027/95A2286D63E1AF7BB7CE9B8E33B5F27F9E975DDA/",
            "Convex": false,
            "MaterialIndex": 3,
            "TypeIndex": 0,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        }
      ]
    }]],
    [[{
      "GUID": "d5aa92",
      "Name": "BlockSquare",
      "Transform": {
        "posX": 2.99686956,
        "posY": 1.03038812,
        "posZ": 10.9992714,
        "rotX": -2.509569E-07,
        "rotY": 269.9794,
        "rotZ": -2.936203E-08,
        "scaleX": 4.0,
        "scaleY": 0.1,
        "scaleZ": 6.0
      },
      "Nickname": "Ruin (2\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 0.232288271,
        "g": 0.22662288,
        "b": 0.3512627
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "5465db",
          "Name": "Custom_Model",
          "Transform": {
            "posX": 0.05186952,
            "posY": -0.9508598,
            "posZ": 0.424282759,
            "rotX": 0.0241138525,
            "rotY": 90.00001,
            "rotZ": -2.22614815E-07,
            "scaleX": 0.158333316,
            "scaleY": 9.499966,
            "scaleZ": 0.14669925
          },
          "Nickname": "prison wall 3",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1852681510007517842/A49F5DB08B4B726084948D1FD79B7D625F24EE07/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1829033806572958162/ADFC131F71CC6446077F60F87C980A9B9DCF7C12/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1852681510007517842/A49F5DB08B4B726084948D1FD79B7D625F24EE07/",
            "Convex": false,
            "MaterialIndex": 3,
            "TypeIndex": 4,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        },
        {
          "GUID": "3b8767",
          "Name": "Custom_Model",
          "Transform": {
            "posX": -0.3898291,
            "posY": -0.7396576,
            "posZ": -0.00557935238,
            "rotX": -2.2365154E-07,
            "rotY": 2.11742186E-15,
            "rotZ": -1.084896E-06,
            "scaleX": 0.237500012,
            "scaleY": 9.5,
            "scaleZ": 0.158333346
          },
          "Nickname": "prison wall 3",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1852681510007517842/A49F5DB08B4B726084948D1FD79B7D625F24EE07/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1829033806572958162/ADFC131F71CC6446077F60F87C980A9B9DCF7C12/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1852681510007517842/A49F5DB08B4B726084948D1FD79B7D625F24EE07/",
            "Convex": false,
            "MaterialIndex": 3,
            "TypeIndex": 4,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        }
      ]
    }]],
    [[{
      "GUID": "20e9fc",
      "Name": "BlockSquare",
      "Transform": {
        "posX": 10.5214491,
        "posY": 1.04,
        "posZ": -0.274778068,
        "rotX": 0.0,
        "rotY": 130.9991,
        "rotZ": 8.710663E-05,
        "scaleX": 6.00000048,
        "scaleY": 0.100000009,
        "scaleZ": 12.0
      },
      "Nickname": "Ruin (9\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 0.232399613,
        "g": 0.22399959,
        "b": 0.3499996
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": ""
    }]],
    [[{
      "GUID": "f75cac",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": -8.738447,
        "posY": 1.0547967,
        "posZ": 2.09542274,
        "rotX": 0.000621076848,
        "rotY": 40.60659,
        "rotZ": -9.875054E-06,
        "scaleX": 1.99489653,
        "scaleY": 3.52763486,
        "scaleZ": 1.0000242
      },
      "Nickname": "Ruin (9\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "0d1b87",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": 1.76267076,
            "posY": -0.000449319079,
            "posZ": -0.01457209,
            "rotX": 0.000112515983,
            "rotY": 180.213272,
            "rotZ": 2.12263944E-06,
            "scaleX": 0.40102616,
            "scaleY": 1.0,
            "scaleZ": 0.7999697
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": "",
          "ChildObjects": [
            {
              "GUID": "f321f4",
              "Name": "Custom_Assetbundle",
              "Transform": {
                "posX": -0.0138203735,
                "posY": -0.008904007,
                "posZ": 1.91282463,
                "rotX": 2.52710084E-08,
                "rotY": 89.99715,
                "rotZ": -3.0327833E-06,
                "scaleX": 1.25001657,
                "scaleY": 0.9999999,
                "scaleZ": 1.25002515
              },
              "Nickname": "",
              "Description": "",
              "GMNotes": "",
              "AltLookAngle": {
                "x": 0.0,
                "y": 0.0,
                "z": 0.0
              },
              "ColorDiffuse": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "LayoutGroupSortIndex": 0,
              "Value": 0,
              "Locked": true,
              "Grid": true,
              "Snap": true,
              "IgnoreFoW": false,
              "MeasureMovement": false,
              "DragSelectable": true,
              "Autoraise": true,
              "Sticky": true,
              "Tooltip": true,
              "GridProjection": false,
              "HideWhenFaceDown": false,
              "Hands": false,
              "CustomAssetbundle": {
                "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
                "AssetbundleSecondaryURL": "",
                "MaterialIndex": 2,
                "TypeIndex": 1,
                "LoopingEffectIndex": 0
              },
              "LuaScript": "",
              "LuaScriptState": "",
              "XmlUI": "",
              "ChildObjects": [
                {
                  "GUID": "49d9cf",
                  "Name": "Custom_Assetbundle",
                  "Transform": {
                    "posX": -1.46976483,
                    "posY": 0.008956638,
                    "posZ": -0.0437401868,
                    "rotX": 359.7561,
                    "rotY": 180.0035,
                    "rotZ": -1.2685734E-05,
                    "scaleX": 0.7999891,
                    "scaleY": 1.00001287,
                    "scaleZ": 0.7999471
                  },
                  "Nickname": "",
                  "Description": "",
                  "GMNotes": "",
                  "AltLookAngle": {
                    "x": 0.0,
                    "y": 0.0,
                    "z": 0.0
                  },
                  "ColorDiffuse": {
                    "r": 1.0,
                    "g": 1.0,
                    "b": 1.0
                  },
                  "LayoutGroupSortIndex": 0,
                  "Value": 0,
                  "Locked": true,
                  "Grid": true,
                  "Snap": true,
                  "IgnoreFoW": false,
                  "MeasureMovement": false,
                  "DragSelectable": true,
                  "Autoraise": true,
                  "Sticky": true,
                  "Tooltip": true,
                  "GridProjection": false,
                  "HideWhenFaceDown": false,
                  "Hands": false,
                  "CustomAssetbundle": {
                    "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
                    "AssetbundleSecondaryURL": "",
                    "MaterialIndex": 2,
                    "TypeIndex": 1,
                    "LoopingEffectIndex": 0
                  },
                  "LuaScript": "",
                  "LuaScriptState": "",
                  "XmlUI": ""
                }
              ]
            }
          ]
        },
        {
          "GUID": "aa4e95",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": -1.81088126,
            "posY": 0.01569178,
            "posZ": 0.037571,
            "rotX": 5.44979E-06,
            "rotY": 269.499969,
            "rotZ": 0.0022164823,
            "scaleX": 0.7999201,
            "scaleY": 0.9999999,
            "scaleZ": 0.401038647
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": "",
          "ChildObjects": [
            {
              "GUID": "2d4667",
              "Name": "Custom_Assetbundle",
              "Transform": {
                "posX": -1.94005382,
                "posY": -0.0366984,
                "posZ": 0.0241482537,
                "rotX": -2.60551053E-10,
                "rotY": 4.798938E-15,
                "rotZ": -0.002110595,
                "scaleX": 1.25001729,
                "scaleY": 1.0,
                "scaleZ": 1.25002539
              },
              "Nickname": "",
              "Description": "",
              "GMNotes": "",
              "AltLookAngle": {
                "x": 0.0,
                "y": 0.0,
                "z": 0.0
              },
              "ColorDiffuse": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "LayoutGroupSortIndex": 0,
              "Value": 0,
              "Locked": true,
              "Grid": true,
              "Snap": true,
              "IgnoreFoW": false,
              "MeasureMovement": false,
              "DragSelectable": true,
              "Autoraise": true,
              "Sticky": true,
              "Tooltip": true,
              "GridProjection": false,
              "HideWhenFaceDown": false,
              "Hands": false,
              "CustomAssetbundle": {
                "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
                "AssetbundleSecondaryURL": "",
                "MaterialIndex": 2,
                "TypeIndex": 1,
                "LoopingEffectIndex": 0
              },
              "LuaScript": "",
              "LuaScriptState": "",
              "XmlUI": "",
              "ChildObjects": [
                {
                  "GUID": "f2635d",
                  "Name": "Custom_Assetbundle",
                  "Transform": {
                    "posX": -1.4476639,
                    "posY": 0.0367337279,
                    "posZ": 0.0714720041,
                    "rotX": -3.90826572E-11,
                    "rotY": -1.1715962E-17,
                    "rotZ": 3.4351564E-05,
                    "scaleX": 0.799989,
                    "scaleY": 1.0,
                    "scaleZ": 0.7999835
                  },
                  "Nickname": "",
                  "Description": "",
                  "GMNotes": "",
                  "AltLookAngle": {
                    "x": 0.0,
                    "y": 0.0,
                    "z": 0.0
                  },
                  "ColorDiffuse": {
                    "r": 1.0,
                    "g": 1.0,
                    "b": 1.0
                  },
                  "LayoutGroupSortIndex": 0,
                  "Value": 0,
                  "Locked": true,
                  "Grid": true,
                  "Snap": true,
                  "IgnoreFoW": false,
                  "MeasureMovement": false,
                  "DragSelectable": true,
                  "Autoraise": true,
                  "Sticky": true,
                  "Tooltip": true,
                  "GridProjection": false,
                  "HideWhenFaceDown": false,
                  "Hands": false,
                  "CustomAssetbundle": {
                    "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
                    "AssetbundleSecondaryURL": "",
                    "MaterialIndex": 2,
                    "TypeIndex": 1,
                    "LoopingEffectIndex": 0
                  },
                  "LuaScript": "",
                  "LuaScriptState": "",
                  "XmlUI": ""
                }
              ]
            }
          ]
        }
      ]
    }]],
    [[{
      "GUID": "e35bfc",
      "Name": "BlockSquare",
      "Transform": {
        "posX": -10.52092,
        "posY": 1.04120111,
        "posZ": 0.2743094,
        "rotX": -8.233413E-09,
        "rotY": 310.999939,
        "rotZ": 0.0006618238,
        "scaleX": 6.0,
        "scaleY": 0.100000016,
        "scaleZ": 12.0
      },
      "Nickname": "Ruin (9\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 0.232399613,
        "g": 0.22399959,
        "b": 0.3499996
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": ""
    }]],
    [[{
      "GUID": "0d0ba1",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": 8.795708,
        "posY": 1.09527373,
        "posZ": -2.221815,
        "rotX": 3.84340137E-06,
        "rotY": 220.831558,
        "rotZ": 0.0005180294,
        "scaleX": 1.99489653,
        "scaleY": 3.52763486,
        "scaleZ": 1.0000242
      },
      "Nickname": "Ruin (9\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "0d1b87",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": 1.76267076,
            "posY": -0.000449319079,
            "posZ": -0.01457209,
            "rotX": 0.000112515983,
            "rotY": 180.213272,
            "rotZ": 2.12263944E-06,
            "scaleX": 0.40102616,
            "scaleY": 1.0,
            "scaleZ": 0.7999697
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": "",
          "ChildObjects": [
            {
              "GUID": "f321f4",
              "Name": "Custom_Assetbundle",
              "Transform": {
                "posX": -0.0138203735,
                "posY": -0.008904007,
                "posZ": 1.91282463,
                "rotX": 2.52710084E-08,
                "rotY": 89.99715,
                "rotZ": -3.0327833E-06,
                "scaleX": 1.25001657,
                "scaleY": 0.9999999,
                "scaleZ": 1.25002515
              },
              "Nickname": "",
              "Description": "",
              "GMNotes": "",
              "AltLookAngle": {
                "x": 0.0,
                "y": 0.0,
                "z": 0.0
              },
              "ColorDiffuse": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "LayoutGroupSortIndex": 0,
              "Value": 0,
              "Locked": true,
              "Grid": true,
              "Snap": true,
              "IgnoreFoW": false,
              "MeasureMovement": false,
              "DragSelectable": true,
              "Autoraise": true,
              "Sticky": true,
              "Tooltip": true,
              "GridProjection": false,
              "HideWhenFaceDown": false,
              "Hands": false,
              "CustomAssetbundle": {
                "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
                "AssetbundleSecondaryURL": "",
                "MaterialIndex": 2,
                "TypeIndex": 1,
                "LoopingEffectIndex": 0
              },
              "LuaScript": "",
              "LuaScriptState": "",
              "XmlUI": "",
              "ChildObjects": [
                {
                  "GUID": "49d9cf",
                  "Name": "Custom_Assetbundle",
                  "Transform": {
                    "posX": -1.46976483,
                    "posY": 0.008956638,
                    "posZ": -0.0437401868,
                    "rotX": 359.7561,
                    "rotY": 180.0035,
                    "rotZ": -1.2685734E-05,
                    "scaleX": 0.7999891,
                    "scaleY": 1.00001287,
                    "scaleZ": 0.7999471
                  },
                  "Nickname": "",
                  "Description": "",
                  "GMNotes": "",
                  "AltLookAngle": {
                    "x": 0.0,
                    "y": 0.0,
                    "z": 0.0
                  },
                  "ColorDiffuse": {
                    "r": 1.0,
                    "g": 1.0,
                    "b": 1.0
                  },
                  "LayoutGroupSortIndex": 0,
                  "Value": 0,
                  "Locked": true,
                  "Grid": true,
                  "Snap": true,
                  "IgnoreFoW": false,
                  "MeasureMovement": false,
                  "DragSelectable": true,
                  "Autoraise": true,
                  "Sticky": true,
                  "Tooltip": true,
                  "GridProjection": false,
                  "HideWhenFaceDown": false,
                  "Hands": false,
                  "CustomAssetbundle": {
                    "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
                    "AssetbundleSecondaryURL": "",
                    "MaterialIndex": 2,
                    "TypeIndex": 1,
                    "LoopingEffectIndex": 0
                  },
                  "LuaScript": "",
                  "LuaScriptState": "",
                  "XmlUI": ""
                }
              ]
            }
          ]
        },
        {
          "GUID": "aa4e95",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": -1.81088126,
            "posY": 0.01569178,
            "posZ": 0.037571,
            "rotX": 5.44979E-06,
            "rotY": 269.499969,
            "rotZ": 0.0022164823,
            "scaleX": 0.7999201,
            "scaleY": 0.9999999,
            "scaleZ": 0.401038647
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": "",
          "ChildObjects": [
            {
              "GUID": "2d4667",
              "Name": "Custom_Assetbundle",
              "Transform": {
                "posX": -1.94005382,
                "posY": -0.0366984,
                "posZ": 0.0241482537,
                "rotX": -2.60551053E-10,
                "rotY": 4.798938E-15,
                "rotZ": -0.002110595,
                "scaleX": 1.25001729,
                "scaleY": 1.0,
                "scaleZ": 1.25002539
              },
              "Nickname": "",
              "Description": "",
              "GMNotes": "",
              "AltLookAngle": {
                "x": 0.0,
                "y": 0.0,
                "z": 0.0
              },
              "ColorDiffuse": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "LayoutGroupSortIndex": 0,
              "Value": 0,
              "Locked": true,
              "Grid": true,
              "Snap": true,
              "IgnoreFoW": false,
              "MeasureMovement": false,
              "DragSelectable": true,
              "Autoraise": true,
              "Sticky": true,
              "Tooltip": true,
              "GridProjection": false,
              "HideWhenFaceDown": false,
              "Hands": false,
              "CustomAssetbundle": {
                "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
                "AssetbundleSecondaryURL": "",
                "MaterialIndex": 2,
                "TypeIndex": 1,
                "LoopingEffectIndex": 0
              },
              "LuaScript": "",
              "LuaScriptState": "",
              "XmlUI": "",
              "ChildObjects": [
                {
                  "GUID": "f2635d",
                  "Name": "Custom_Assetbundle",
                  "Transform": {
                    "posX": -1.4476639,
                    "posY": 0.0367337279,
                    "posZ": 0.0714720041,
                    "rotX": -3.90826572E-11,
                    "rotY": -1.1715962E-17,
                    "rotZ": 3.4351564E-05,
                    "scaleX": 0.799989,
                    "scaleY": 1.0,
                    "scaleZ": 0.7999835
                  },
                  "Nickname": "",
                  "Description": "",
                  "GMNotes": "",
                  "AltLookAngle": {
                    "x": 0.0,
                    "y": 0.0,
                    "z": 0.0
                  },
                  "ColorDiffuse": {
                    "r": 1.0,
                    "g": 1.0,
                    "b": 1.0
                  },
                  "LayoutGroupSortIndex": 0,
                  "Value": 0,
                  "Locked": true,
                  "Grid": true,
                  "Snap": true,
                  "IgnoreFoW": false,
                  "MeasureMovement": false,
                  "DragSelectable": true,
                  "Autoraise": true,
                  "Sticky": true,
                  "Tooltip": true,
                  "GridProjection": false,
                  "HideWhenFaceDown": false,
                  "Hands": false,
                  "CustomAssetbundle": {
                    "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
                    "AssetbundleSecondaryURL": "",
                    "MaterialIndex": 2,
                    "TypeIndex": 1,
                    "LoopingEffectIndex": 0
                  },
                  "LuaScript": "",
                  "LuaScriptState": "",
                  "XmlUI": ""
                }
              ]
            }
          ]
        }
      ]
    }]],
    [[{
      "GUID": "12f429",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": -21.0095863,
        "posY": 1.08040118,
        "posZ": 17.5605869,
        "rotX": 0.000285807357,
        "rotY": 180.0,
        "rotZ": -2.24723681E-05,
        "scaleX": 1.00000083,
        "scaleY": 3.50000525,
        "scaleZ": 1.00000989
      },
      "Nickname": "Ruin (9\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "7ba0f2",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": -1.56072688,
            "posY": 0.008887906,
            "posZ": 0.03778963,
            "rotX": -0.000174122673,
            "rotY": 89.99761,
            "rotZ": -0.000297388673,
            "scaleX": 0.799992442,
            "scaleY": 0.99999845,
            "scaleZ": 0.799999654
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": "",
          "ChildObjects": [
            {
              "GUID": "cf3166",
              "Name": "Custom_Assetbundle",
              "Transform": {
                "posX": -3.208033,
                "posY": -0.00889108051,
                "posZ": -0.06094007,
                "rotX": -0.0009949082,
                "rotY": 0.00237349072,
                "rotZ": -1.24788721E-06,
                "scaleX": 2.04888988,
                "scaleY": 1.00000155,
                "scaleZ": 1.2500335
              },
              "Nickname": "",
              "Description": "",
              "GMNotes": "",
              "AltLookAngle": {
                "x": 0.0,
                "y": 0.0,
                "z": 0.0
              },
              "ColorDiffuse": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "LayoutGroupSortIndex": 0,
              "Value": 0,
              "Locked": true,
              "Grid": true,
              "Snap": true,
              "IgnoreFoW": false,
              "MeasureMovement": false,
              "DragSelectable": true,
              "Autoraise": true,
              "Sticky": true,
              "Tooltip": true,
              "GridProjection": false,
              "HideWhenFaceDown": false,
              "Hands": false,
              "CustomAssetbundle": {
                "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
                "AssetbundleSecondaryURL": "",
                "MaterialIndex": 2,
                "TypeIndex": 1,
                "LoopingEffectIndex": 0
              },
              "LuaScript": "",
              "LuaScriptState": "",
              "XmlUI": "",
              "ChildObjects": [
                {
                  "GUID": "f0f588",
                  "Name": "Custom_Assetbundle",
                  "Transform": {
                    "posX": -1.55960786,
                    "posY": 0.008890893,
                    "posZ": 9.536488E-07,
                    "rotX": 0.0009938283,
                    "rotY": 1.7468775E-10,
                    "rotZ": 2.01420535E-05,
                    "scaleX": 0.488069355,
                    "scaleY": 0.999998331,
                    "scaleZ": 0.79997915
                  },
                  "Nickname": "",
                  "Description": "",
                  "GMNotes": "",
                  "AltLookAngle": {
                    "x": 0.0,
                    "y": 0.0,
                    "z": 0.0
                  },
                  "ColorDiffuse": {
                    "r": 1.0,
                    "g": 1.0,
                    "b": 1.0
                  },
                  "LayoutGroupSortIndex": 0,
                  "Value": 0,
                  "Locked": true,
                  "Grid": true,
                  "Snap": true,
                  "IgnoreFoW": false,
                  "MeasureMovement": false,
                  "DragSelectable": true,
                  "Autoraise": true,
                  "Sticky": true,
                  "Tooltip": true,
                  "GridProjection": false,
                  "HideWhenFaceDown": false,
                  "Hands": false,
                  "CustomAssetbundle": {
                    "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
                    "AssetbundleSecondaryURL": "",
                    "MaterialIndex": 2,
                    "TypeIndex": 1,
                    "LoopingEffectIndex": 0
                  },
                  "LuaScript": "",
                  "LuaScriptState": "",
                  "XmlUI": ""
                }
              ]
            }
          ]
        },
        {
          "GUID": "5cc9a0",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": 1.490176,
            "posY": 0.008887364,
            "posZ": 0.0387950651,
            "rotX": -7.385185E-05,
            "rotY": 0.0234002285,
            "rotZ": -0.00102425076,
            "scaleX": 0.8,
            "scaleY": 0.9999984,
            "scaleZ": 0.799992442
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        },
        {
          "GUID": "084faf",
          "Name": "BlockSquare",
          "Transform": {
            "posX": 0.990412533,
            "posY": -0.0142829167,
            "posZ": 4.560542,
            "rotX": -2.21657538E-05,
            "rotY": 89.99999,
            "rotZ": -0.000285564747,
            "scaleX": 9.999901,
            "scaleY": 0.0285713859,
            "scaleZ": 5.99999571
          },
          "Nickname": "Ruin (9\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 0.232399762,
            "g": 0.223999739,
            "b": 0.3499998
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "LuaScript": "\nBCBtype = \"terrain\"\n",
          "LuaScriptState": "",
          "XmlUI": ""
        }
      ]
    }]],
    [[{
      "GUID": "d09531",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": 21.0,
        "posY": 1.08040679,
        "posZ": -17.5,
        "rotX": 0.000286971917,
        "rotY": 0.0,
        "rotZ": -2.17540473E-05,
        "scaleX": 1.00000083,
        "scaleY": 3.50000525,
        "scaleZ": 1.00000989
      },
      "Nickname": "Ruin (9\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "7ba0f2",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": -1.56072688,
            "posY": 0.008887906,
            "posZ": 0.03778963,
            "rotX": -0.000174122673,
            "rotY": 89.99761,
            "rotZ": -0.000297388673,
            "scaleX": 0.799992442,
            "scaleY": 0.99999845,
            "scaleZ": 0.799999654
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": "",
          "ChildObjects": [
            {
              "GUID": "cf3166",
              "Name": "Custom_Assetbundle",
              "Transform": {
                "posX": -3.208033,
                "posY": -0.00889108051,
                "posZ": -0.06094007,
                "rotX": -0.0009949082,
                "rotY": 0.00237349072,
                "rotZ": -1.24788721E-06,
                "scaleX": 2.04888988,
                "scaleY": 1.00000155,
                "scaleZ": 1.2500335
              },
              "Nickname": "",
              "Description": "",
              "GMNotes": "",
              "AltLookAngle": {
                "x": 0.0,
                "y": 0.0,
                "z": 0.0
              },
              "ColorDiffuse": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "LayoutGroupSortIndex": 0,
              "Value": 0,
              "Locked": true,
              "Grid": true,
              "Snap": true,
              "IgnoreFoW": false,
              "MeasureMovement": false,
              "DragSelectable": true,
              "Autoraise": true,
              "Sticky": true,
              "Tooltip": true,
              "GridProjection": false,
              "HideWhenFaceDown": false,
              "Hands": false,
              "CustomAssetbundle": {
                "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
                "AssetbundleSecondaryURL": "",
                "MaterialIndex": 2,
                "TypeIndex": 1,
                "LoopingEffectIndex": 0
              },
              "LuaScript": "",
              "LuaScriptState": "",
              "XmlUI": "",
              "ChildObjects": [
                {
                  "GUID": "f0f588",
                  "Name": "Custom_Assetbundle",
                  "Transform": {
                    "posX": -1.55960786,
                    "posY": 0.008890893,
                    "posZ": 9.536488E-07,
                    "rotX": 0.0009938283,
                    "rotY": 1.7468775E-10,
                    "rotZ": 2.01420535E-05,
                    "scaleX": 0.488069355,
                    "scaleY": 0.999998331,
                    "scaleZ": 0.79997915
                  },
                  "Nickname": "",
                  "Description": "",
                  "GMNotes": "",
                  "AltLookAngle": {
                    "x": 0.0,
                    "y": 0.0,
                    "z": 0.0
                  },
                  "ColorDiffuse": {
                    "r": 1.0,
                    "g": 1.0,
                    "b": 1.0
                  },
                  "LayoutGroupSortIndex": 0,
                  "Value": 0,
                  "Locked": true,
                  "Grid": true,
                  "Snap": true,
                  "IgnoreFoW": false,
                  "MeasureMovement": false,
                  "DragSelectable": true,
                  "Autoraise": true,
                  "Sticky": true,
                  "Tooltip": true,
                  "GridProjection": false,
                  "HideWhenFaceDown": false,
                  "Hands": false,
                  "CustomAssetbundle": {
                    "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
                    "AssetbundleSecondaryURL": "",
                    "MaterialIndex": 2,
                    "TypeIndex": 1,
                    "LoopingEffectIndex": 0
                  },
                  "LuaScript": "",
                  "LuaScriptState": "",
                  "XmlUI": ""
                }
              ]
            }
          ]
        },
        {
          "GUID": "5cc9a0",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": 1.490176,
            "posY": 0.008887364,
            "posZ": 0.0387950651,
            "rotX": -7.385185E-05,
            "rotY": 0.0234002285,
            "rotZ": -0.00102425076,
            "scaleX": 0.8,
            "scaleY": 0.9999984,
            "scaleZ": 0.799992442
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        },
        {
          "GUID": "084faf",
          "Name": "BlockSquare",
          "Transform": {
            "posX": 0.990412533,
            "posY": -0.0142829167,
            "posZ": 4.560542,
            "rotX": -2.21657538E-05,
            "rotY": 89.99999,
            "rotZ": -0.000285564747,
            "scaleX": 9.999901,
            "scaleY": 0.0285713859,
            "scaleZ": 5.99999571
          },
          "Nickname": "Ruin (9\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 0.232399762,
            "g": 0.223999739,
            "b": 0.3499998
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "LuaScript": "\nBCBtype = \"terrain\"\n",
          "LuaScriptState": "",
          "XmlUI": ""
        }
      ]
    }]]
}

