-- FTC-GUID: 5b3029
            
    function onLoad()
      self.createButton({
          label = "Load Map",
          font_size = 115,
          color = {0, 1, 0,},
          position = {-0.96, 0.5, 0},
          rotation = {0, 90, 0},
          scale = {1.3, 1, .7},
          width = 570,
          height = 160,
          click_function = "loadMap",
          function_owner = self,
      })	
  
      self.createButton({
          label = "Clear Map",
          font_size = 100,
          position = {1, 0.5, 0},
          rotation = {0, 90, 0},
          scale = {.6, .6, .4},
          width = 530,
          height = 130,
          color = {1, 0, 0},
          click_function = "clearMap",
          function_owner = self,
      })
  end
  
  -------------------
  -- Prepares the terrain saved into the card from Map Saver tool
  string.split = function(s, delimiter)
      local result = { }
      local from  = 1
      local delim_from, delim_to = string.find( s, delimiter, from  )
      while delim_from do
          table.insert( result, string.sub( s, from , delim_from-1 ) )
          from  = delim_to + 1
          delim_from, delim_to = string.find( s, delimiter, from  )
      end
      table.insert( result, string.sub( s, from  ) )
      return result
  end

function scriptzoneCallback(zone) --This deletes everything except the things listed, when the scripting zone is briefly spawned.

      local objects = zone.getObjects()
      
      for i, obj in ipairs(objects) do
          if obj.getGUID() ~= "e7ca6e" --Exclude Map Buidler Table
              and 
              obj.getGUID() ~= "6012bf" --...and ForceOrg Table...
              and 
              obj.getGUID() ~= "4ee1f2" --...and FTC board matObjSurface
              and
              obj.getGUID() ~= "948ce5" --...and FTC Table
              and
              obj.getGUID() ~= "28865a" --...and FTC Felt Surface
              then 
              obj.destruct()
          end  
      end
      zone.destruct()
  end
  function loadMap(objectClicked, clickerColor, altClickUsed)
      -------------------
      -- Spawn the scripting zone, which uses the callback above that deletes everything then deletes itself.
      local scriptzoneParams = {                  -- Define the parameters for the scripting zone
          position = {x=0, y=26, z=0},
          --scale = {x=30.15, y=73, z=22.03}, --Kill Team Size
          --scale = {x=30.15, y=73, z=44.04}, --Incursion and Combat Patrol Size
          scale = {x=60.12, y=73, z=44.04}, --Strike Force Size
          --scale = {x=90.07, y=73, z=44.04}, --Onslaught Size
          type = 'ScriptingTrigger',              -- Use the ScriptingTrigger type to spawn a Scripting Zone
          callback_function = scriptzoneCallback, -- Specify the function to call when the zone is created
          callback_owner = self,
          }

  spawnObject(scriptzoneParams)
  -- Then Sspawn the objects stored in the card
  
      Wait.time(
      function()
          for _, objectJSON in ipairs(objectJSONs) do 
              -- Spawn the map from the JSON data
              spawnObjectJSON({
                  json = objectJSON
              })
          end
      end, .5)
  end
  
  -----------------------------------------------------------------------------------------------------------------
  -- This function runs when the Clear Map button is clicked on the Map Card
  function clearMap(objectClicked, clickerColor, altClickUsed)

      local scriptzoneParams = {                  -- Define the parameters for the scripting zone
          position = {x=0, y=26, z=0},
          --scale = {x=30.15, y=73, z=22.03}, --Kill Team Size
          --scale = {x=30.15, y=73, z=44.04}, --Incursion and Combat Patrol Size
          scale = {x=60.12, y=73, z=44.04}, --Strike Force Size
          --scale = {x=90.07, y=73, z=44.04}, --Onslaught Size
          type = 'ScriptingTrigger',              -- Use the ScriptingTrigger type to spawn a Scripting Zone
          callback_function = scriptzoneCallback, -- Specify the function to call when the zone is created
          callback_owner = self,
          }

  spawnObject(scriptzoneParams)
  
  end
      

objectJSONs = {
[[{
"GUID": "7f414f",
"Name": "Custom_Model",
"Transform": {
  "posX": 0.0019,
  "posY": -10.13,
  "posZ": 0.0029,
  "rotX": 0.0,
  "rotY": 0.0,
  "rotZ": 0.0,
  "scaleX": 1.666,
  "scaleY": 1.06,
  "scaleZ": 1.2206
},
"Nickname": "",
"Description": "",
"GMNotes": "",
"AltLookAngle": {
  "x": 0.0,
  "y": 0.0,
  "z": 0.0
},
"ColorDiffuse": {
  "r": 1.0,
  "g": 1.0,
  "b": 1.0
},
"LayoutGroupSortIndex": 0,
"Value": 0,
"Locked": true,
"Grid": true,
"Snap": true,
"IgnoreFoW": false,
"MeasureMovement": false,
"DragSelectable": true,
"Autoraise": true,
"Sticky": true,
"Tooltip": true,
"GridProjection": true,
"HideWhenFaceDown": false,
"Hands": false,
"CustomMesh": {
  "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/879750610978796176/4A5A65543B98BCFBF57E910D06EC984208223D38/",
  "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1043093746445935246/14E522400874F5749E765D7CC148F6DD5D2769F1/",
  "NormalURL": "",
  "ColliderURL": "",
  "Convex": true,
  "MaterialIndex": 3,
  "TypeIndex": 4,
  "CustomShader": {
    "SpecularColor": {
      "r": 1.0,
      "g": 1.0,
      "b": 1.0
    },
    "SpecularIntensity": 0.0,
    "SpecularSharpness": 2.0,
    "FresnelStrength": 0.0
  },
  "CastShadows": true
},
"LuaScript": "function onload() \r\n    self.interactable = false\r\n    self.gizmo_selectable = true\r\nend",
"LuaScriptState": "",
"XmlUI": ""
}]],
[[{
"GUID": "3e2adb",
"Name": "Custom_Model",
"Transform": {
  "posX": -14.83356,
  "posY": 0.97,
  "posZ": -1.06241,
  "rotX": 0.0,
  "rotY": 137.0,
  "rotZ": 0.0,
  "scaleX": 1.0,
  "scaleY": 1.0,
  "scaleZ": 1.0
},
"Nickname": "TWO STOREY RUIN",
"Description": "",
"GMNotes": "",
"AltLookAngle": {
  "x": 0.0,
  "y": 0.0,
  "z": 0.0
},
"ColorDiffuse": {
  "r": 1.0,
  "g": 1.0,
  "b": 1.0
},
"LayoutGroupSortIndex": 0,
"Value": 0,
"Locked": true,
"Grid": true,
"Snap": true,
"IgnoreFoW": false,
"MeasureMovement": false,
"DragSelectable": true,
"Autoraise": true,
"Sticky": true,
"Tooltip": true,
"GridProjection": false,
"HideWhenFaceDown": false,
"Hands": false,
"CustomMesh": {
  "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700191697866339/512A215790C3FB9D46B89208BDB234D98D8C3350/",
  "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794552248/6D9B9FB570E97EA80128D58CD4A0EB295F654306/",
  "NormalURL": "",
  "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912201570/3CFC9BAA671D43615F4A56A37B443F1819EA1672/",
  "Convex": true,
  "MaterialIndex": 1,
  "TypeIndex": 0,
  "CastShadows": true
},
"LuaScript": "\nBCBtype = \"terrain\"\n",
"LuaScriptState": "",
"XmlUI": "",
"States": {
  "2": {
    "GUID": "37b6f7",
    "Name": "Custom_Model",
    "Transform": {
      "posX": -26.4610939,
      "posY": 0.994030356,
      "posZ": -1.02261841,
      "rotX": 0.0,
      "rotY": 270.0,
      "rotZ": 0.0,
      "scaleX": 1.0,
      "scaleY": 1.0,
      "scaleZ": 1.0
    },
    "Nickname": "TWO STOREY RUIN",
    "Description": "",
    "GMNotes": "",
    "AltLookAngle": {
      "x": 0.0,
      "y": 0.0,
      "z": 0.0
    },
    "ColorDiffuse": {
      "r": 1.0,
      "g": 1.0,
      "b": 1.0
    },
    "LayoutGroupSortIndex": 0,
    "Value": 0,
    "Locked": true,
    "Grid": true,
    "Snap": true,
    "IgnoreFoW": false,
    "MeasureMovement": false,
    "DragSelectable": true,
    "Autoraise": true,
    "Sticky": true,
    "Tooltip": true,
    "GridProjection": false,
    "HideWhenFaceDown": false,
    "Hands": false,
    "CustomMesh": {
      "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700191697866339/512A215790C3FB9D46B89208BDB234D98D8C3350/",
      "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794552248/6D9B9FB570E97EA80128D58CD4A0EB295F654306/",
      "NormalURL": "",
      "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912201570/3CFC9BAA671D43615F4A56A37B443F1819EA1672/",
      "Convex": true,
      "MaterialIndex": 1,
      "TypeIndex": 0,
      "CastShadows": true
    },
    "LuaScript": "",
    "LuaScriptState": "",
    "XmlUI": "",
    "ChildObjects": [
      {
        "GUID": "6452c2",
        "Name": "CardCustom",
        "Transform": {
          "posX": 2.13760066,
          "posY": 0.0,
          "posZ": -5.12226,
          "rotX": -0.000240696449,
          "rotY": 179.999969,
          "rotZ": 0.000153086949,
          "scaleX": 2.7929132,
          "scaleY": 0.065,
          "scaleZ": 3.91000128
        },
        "Nickname": "",
        "Description": "",
        "GMNotes": "",
        "AltLookAngle": {
          "x": 0.0,
          "y": 0.0,
          "z": 0.0
        },
        "ColorDiffuse": {
          "r": 0.713235259,
          "g": 0.713235259,
          "b": 0.713235259
        },
        "LayoutGroupSortIndex": 0,
        "Value": 0,
        "Locked": true,
        "Grid": true,
        "Snap": true,
        "IgnoreFoW": false,
        "MeasureMovement": false,
        "DragSelectable": true,
        "Autoraise": true,
        "Sticky": true,
        "Tooltip": true,
        "GridProjection": false,
        "HideWhenFaceDown": true,
        "Hands": true,
        "CardID": 30400,
        "SidewaysCard": false,
        "CustomDeck": {
          "304": {
            "FaceURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794548479/1334E2934F85878167A301C71EBDE0DD7AB39D9C/",
            "BackURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794548479/1334E2934F85878167A301C71EBDE0DD7AB39D9C/",
            "NumWidth": 1,
            "NumHeight": 1,
            "BackIsHidden": true,
            "UniqueBack": false,
            "Type": 0
          }
        },
        "LuaScript": "",
        "LuaScriptState": "",
        "XmlUI": ""
      }
    ]
  }
},
"ChildObjects": [
  {
    "GUID": "bfb4a7",
    "Name": "Custom_Model",
    "Transform": {
      "posX": 1.9836092,
      "posY": 3.21452641,
      "posZ": -1.94255877,
      "rotX": 359.992676,
      "rotY": 359.895325,
      "rotZ": 0.003873905,
      "scaleX": 1.0,
      "scaleY": 1.0,
      "scaleZ": 0.9999999
    },
    "Nickname": "",
    "Description": "",
    "GMNotes": "",
    "AltLookAngle": {
      "x": 0.0,
      "y": 0.0,
      "z": 0.0
    },
    "ColorDiffuse": {
      "r": 0.6627451,
      "g": 0.6627451,
      "b": 0.6627451
    },
    "LayoutGroupSortIndex": 0,
    "Value": 0,
    "Locked": true,
    "Grid": true,
    "Snap": true,
    "IgnoreFoW": false,
    "MeasureMovement": false,
    "DragSelectable": true,
    "Autoraise": true,
    "Sticky": true,
    "Tooltip": true,
    "GridProjection": false,
    "HideWhenFaceDown": false,
    "Hands": false,
    "CustomMesh": {
      "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2050876934859026362/8EDA2E480DFEC1B0B885AB4633074F004E96648D/",
      "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794554175/892D44213E132546A15A01E898CEE59F66ACFE5D/",
      "NormalURL": "",
      "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/2050876934859026362/8EDA2E480DFEC1B0B885AB4633074F004E96648D/",
      "Convex": false,
      "MaterialIndex": 1,
      "TypeIndex": 0,
      "CastShadows": true
    },
    "LuaScript": "",
    "LuaScriptState": "",
    "XmlUI": "",
    "PhysicsMaterial": {
      "StaticFriction": 1.0,
      "DynamicFriction": 0.7,
      "Bounciness": 0.0,
      "FrictionCombine": 0,
      "BounceCombine": 0
    },
    "Rigidbody": {
      "Mass": 1.0,
      "Drag": 0.1,
      "AngularDrag": 0.1,
      "UseGravity": true
    },
    "ChildObjects": [
      {
        "GUID": "3f2d4d",
        "Name": "CardCustom",
        "Transform": {
          "posX": -0.9610308,
          "posY": 0.0725631043,
          "posZ": 0.6029997,
          "rotX": -2.20303335E-07,
          "rotY": 90.08806,
          "rotZ": -2.3364754E-07,
          "scaleX": 0.9084988,
          "scaleY": 0.065,
          "scaleZ": 0.635936439
        },
        "Nickname": "",
        "Description": "",
        "GMNotes": "",
        "AltLookAngle": {
          "x": 0.0,
          "y": 0.0,
          "z": 0.0
        },
        "ColorDiffuse": {
          "r": 0.713235259,
          "g": 0.713235259,
          "b": 0.713235259
        },
        "LayoutGroupSortIndex": 0,
        "Value": 0,
        "Locked": false,
        "Grid": true,
        "Snap": true,
        "IgnoreFoW": false,
        "MeasureMovement": false,
        "DragSelectable": true,
        "Autoraise": true,
        "Sticky": true,
        "Tooltip": true,
        "GridProjection": false,
        "HideWhenFaceDown": true,
        "Hands": true,
        "CardID": 400,
        "SidewaysCard": false,
        "CustomDeck": {
          "4": {
            "FaceURL": "https://steamusercontent-a.akamaihd.net/ugc/2050876934859079198/D1FA4B09D02FEBA5BB9755137AAD285462824318/",
            "BackURL": "https://steamusercontent-a.akamaihd.net/ugc/2050876934859079198/D1FA4B09D02FEBA5BB9755137AAD285462824318/",
            "NumWidth": 1,
            "NumHeight": 1,
            "BackIsHidden": true,
            "UniqueBack": false,
            "Type": 1
          }
        },
        "LuaScript": "",
        "LuaScriptState": "",
        "XmlUI": ""
      }
    ]
  },
  {
    "GUID": "5bbf29",
    "Name": "CardCustom",
    "Transform": {
      "posX": 2.14234233,
      "posY": 0.0,
      "posZ": -5.122262,
      "rotX": -8.797401E-08,
      "rotY": 180.0,
      "rotZ": -3.280339E-07,
      "scaleX": 2.79291272,
      "scaleY": 0.065,
      "scaleZ": 3.91000056
    },
    "Nickname": "",
    "Description": "",
    "GMNotes": "",
    "AltLookAngle": {
      "x": 0.0,
      "y": 0.0,
      "z": 0.0
    },
    "ColorDiffuse": {
      "r": 0.713235259,
      "g": 0.713235259,
      "b": 0.713235259
    },
    "LayoutGroupSortIndex": 0,
    "Value": 0,
    "Locked": true,
    "Grid": true,
    "Snap": true,
    "IgnoreFoW": false,
    "MeasureMovement": false,
    "DragSelectable": true,
    "Autoraise": true,
    "Sticky": true,
    "Tooltip": true,
    "GridProjection": false,
    "HideWhenFaceDown": true,
    "Hands": true,
    "CardID": 30400,
    "SidewaysCard": false,
    "CustomDeck": {
      "304": {
        "FaceURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794548479/1334E2934F85878167A301C71EBDE0DD7AB39D9C/",
        "BackURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794548479/1334E2934F85878167A301C71EBDE0DD7AB39D9C/",
        "NumWidth": 1,
        "NumHeight": 1,
        "BackIsHidden": true,
        "UniqueBack": false,
        "Type": 0
      }
    },
    "LuaScript": "",
    "LuaScriptState": "",
    "XmlUI": ""
  }
]
}]],
[[{
"GUID": "e844f8",
"Name": "Custom_Model",
"Transform": {
  "posX": -19.8415871,
  "posY": 0.97,
  "posZ": -10.5294256,
  "rotX": 0.0,
  "rotY": 317.0,
  "rotZ": 0.0,
  "scaleX": 1.0,
  "scaleY": 1.0,
  "scaleZ": 1.0
},
"Nickname": "THREE STOREY RUIN",
"Description": "",
"GMNotes": "",
"AltLookAngle": {
  "x": 0.0,
  "y": 0.0,
  "z": 0.0
},
"ColorDiffuse": {
  "r": 1.0,
  "g": 1.0,
  "b": 1.0
},
"LayoutGroupSortIndex": 0,
"Value": 0,
"Locked": true,
"Grid": true,
"Snap": true,
"IgnoreFoW": false,
"MeasureMovement": false,
"DragSelectable": true,
"Autoraise": true,
"Sticky": true,
"Tooltip": true,
"GridProjection": false,
"HideWhenFaceDown": false,
"Hands": false,
"CustomMesh": {
  "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794615637/3243BEE6343D5C13E960186B86AC320A41183927/",
  "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794552248/6D9B9FB570E97EA80128D58CD4A0EB295F654306/",
  "NormalURL": "",
  "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912201570/3CFC9BAA671D43615F4A56A37B443F1819EA1672/",
  "Convex": true,
  "MaterialIndex": 1,
  "TypeIndex": 0,
  "CastShadows": true
},
"LuaScript": "",
"LuaScriptState": "",
"XmlUI": "",
"States": {
  "2": {
    "GUID": "5c2d0f",
    "Name": "Custom_Model",
    "Transform": {
      "posX": 15.0,
      "posY": 0.97,
      "posZ": 15.0,
      "rotX": 0.0,
      "rotY": 90.0,
      "rotZ": 0.0,
      "scaleX": 1.0,
      "scaleY": 1.0,
      "scaleZ": 1.0
    },
    "Nickname": "THREE STOREY RUIN",
    "Description": "",
    "GMNotes": "",
    "AltLookAngle": {
      "x": 0.0,
      "y": 0.0,
      "z": 0.0
    },
    "ColorDiffuse": {
      "r": 1.0,
      "g": 1.0,
      "b": 1.0
    },
    "LayoutGroupSortIndex": 0,
    "Value": 0,
    "Locked": true,
    "Grid": true,
    "Snap": true,
    "IgnoreFoW": false,
    "MeasureMovement": false,
    "DragSelectable": true,
    "Autoraise": true,
    "Sticky": true,
    "Tooltip": true,
    "GridProjection": false,
    "HideWhenFaceDown": false,
    "Hands": false,
    "CustomMesh": {
      "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794615637/3243BEE6343D5C13E960186B86AC320A41183927/",
      "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794552248/6D9B9FB570E97EA80128D58CD4A0EB295F654306/",
      "NormalURL": "",
      "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912201570/3CFC9BAA671D43615F4A56A37B443F1819EA1672/",
      "Convex": true,
      "MaterialIndex": 1,
      "TypeIndex": 0,
      "CastShadows": true
    },
    "LuaScript": "",
    "LuaScriptState": "",
    "XmlUI": "",
    "ChildObjects": [
      {
        "GUID": "a55a24",
        "Name": "Custom_Model",
        "Transform": {
          "posX": -0.009057048,
          "posY": 2.94,
          "posZ": 0.0138750086,
          "rotX": 359.983917,
          "rotY": 359.972229,
          "rotZ": -0.001307647,
          "scaleX": 0.9999999,
          "scaleY": 1.0,
          "scaleZ": 1.0
        },
        "Nickname": "THREE STOREY RUIN",
        "Description": "TERRAIN CATEGORY: [c6c930]Area terrain[-]\r\nTERRAIN TRAITS: [1F87FF]Scaleable, Breachable, Light cover, Defensible , Obscuring[-]",
        "GMNotes": "",
        "AltLookAngle": {
          "x": 0.0,
          "y": 0.0,
          "z": 0.0
        },
        "ColorDiffuse": {
          "r": 0.6602787,
          "g": 0.6602787,
          "b": 0.6602787
        },
        "LayoutGroupSortIndex": 0,
        "Value": 0,
        "Locked": true,
        "Grid": true,
        "Snap": true,
        "IgnoreFoW": false,
        "MeasureMovement": false,
        "DragSelectable": true,
        "Autoraise": true,
        "Sticky": true,
        "Tooltip": true,
        "GridProjection": false,
        "HideWhenFaceDown": false,
        "Hands": false,
        "CustomMesh": {
          "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912108869/1AFAF16694B0CBEF6CD222334144FCAA7581FBDA/",
          "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794554175/892D44213E132546A15A01E898CEE59F66ACFE5D/",
          "NormalURL": "",
          "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912108869/1AFAF16694B0CBEF6CD222334144FCAA7581FBDA/",
          "Convex": false,
          "MaterialIndex": 1,
          "TypeIndex": 0,
          "CastShadows": true
        },
        "LuaScript": "",
        "LuaScriptState": "",
        "XmlUI": ""
      },
      {
        "GUID": "1a6bd4",
        "Name": "CardCustom",
        "Transform": {
          "posX": -2.14004683,
          "posY": -6.198883E-06,
          "posZ": -5.049985,
          "rotX": -4.020952E-05,
          "rotY": 0.000525924552,
          "rotZ": 6.76622E-05,
          "scaleX": 2.79291344,
          "scaleY": 0.065,
          "scaleZ": 3.91000152
        },
        "Nickname": "",
        "Description": "",
        "GMNotes": "",
        "AltLookAngle": {
          "x": 0.0,
          "y": 0.0,
          "z": 0.0
        },
        "ColorDiffuse": {
          "r": 0.713235259,
          "g": 0.713235259,
          "b": 0.713235259
        },
        "LayoutGroupSortIndex": 0,
        "Value": 0,
        "Locked": true,
        "Grid": true,
        "Snap": true,
        "IgnoreFoW": false,
        "MeasureMovement": false,
        "DragSelectable": true,
        "Autoraise": true,
        "Sticky": true,
        "Tooltip": true,
        "GridProjection": false,
        "HideWhenFaceDown": true,
        "Hands": true,
        "CardID": 30400,
        "SidewaysCard": false,
        "CustomDeck": {
          "304": {
            "FaceURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794548479/1334E2934F85878167A301C71EBDE0DD7AB39D9C/",
            "BackURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794548479/1334E2934F85878167A301C71EBDE0DD7AB39D9C/",
            "NumWidth": 1,
            "NumHeight": 1,
            "BackIsHidden": true,
            "UniqueBack": false,
            "Type": 0
          }
        },
        "LuaScript": "",
        "LuaScriptState": "",
        "XmlUI": ""
      }
    ]
  },
  "3": {
    "GUID": "c62e13",
    "Name": "Custom_Model",
    "Transform": {
      "posX": 15.0,
      "posY": 0.97,
      "posZ": 15.0,
      "rotX": 0.0,
      "rotY": 90.0,
      "rotZ": 0.0,
      "scaleX": 1.0,
      "scaleY": 1.0,
      "scaleZ": 1.0
    },
    "Nickname": "THREE STOREY RUIN",
    "Description": "",
    "GMNotes": "",
    "AltLookAngle": {
      "x": 0.0,
      "y": 0.0,
      "z": 0.0
    },
    "ColorDiffuse": {
      "r": 1.0,
      "g": 1.0,
      "b": 1.0
    },
    "LayoutGroupSortIndex": 0,
    "Value": 0,
    "Locked": true,
    "Grid": true,
    "Snap": true,
    "IgnoreFoW": false,
    "MeasureMovement": false,
    "DragSelectable": true,
    "Autoraise": true,
    "Sticky": true,
    "Tooltip": true,
    "GridProjection": false,
    "HideWhenFaceDown": false,
    "Hands": false,
    "CustomMesh": {
      "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794615637/3243BEE6343D5C13E960186B86AC320A41183927/",
      "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794552248/6D9B9FB570E97EA80128D58CD4A0EB295F654306/",
      "NormalURL": "",
      "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912201570/3CFC9BAA671D43615F4A56A37B443F1819EA1672/",
      "Convex": true,
      "MaterialIndex": 1,
      "TypeIndex": 0,
      "CastShadows": true
    },
    "LuaScript": "",
    "LuaScriptState": "",
    "XmlUI": "",
    "ChildObjects": [
      {
        "GUID": "6452c2",
        "Name": "CardCustom",
        "Transform": {
          "posX": -2.136197,
          "posY": -2.58482532E-06,
          "posZ": -5.054414,
          "rotX": 2.19344838E-05,
          "rotY": -0.00102452841,
          "rotZ": 0.000121076075,
          "scaleX": 2.792914,
          "scaleY": 0.065,
          "scaleZ": 3.91000152
        },
        "Nickname": "",
        "Description": "",
        "GMNotes": "",
        "AltLookAngle": {
          "x": 0.0,
          "y": 0.0,
          "z": 0.0
        },
        "ColorDiffuse": {
          "r": 0.713235259,
          "g": 0.713235259,
          "b": 0.713235259
        },
        "LayoutGroupSortIndex": 0,
        "Value": 0,
        "Locked": true,
        "Grid": true,
        "Snap": true,
        "IgnoreFoW": false,
        "MeasureMovement": false,
        "DragSelectable": true,
        "Autoraise": true,
        "Sticky": true,
        "Tooltip": true,
        "GridProjection": false,
        "HideWhenFaceDown": true,
        "Hands": true,
        "CardID": 30400,
        "SidewaysCard": false,
        "CustomDeck": {
          "304": {
            "FaceURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794548479/1334E2934F85878167A301C71EBDE0DD7AB39D9C/",
            "BackURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794548479/1334E2934F85878167A301C71EBDE0DD7AB39D9C/",
            "NumWidth": 1,
            "NumHeight": 1,
            "BackIsHidden": true,
            "UniqueBack": false,
            "Type": 0
          }
        },
        "LuaScript": "",
        "LuaScriptState": "",
        "XmlUI": ""
      }
    ]
  }
},
"ChildObjects": [
  {
    "GUID": "44e827",
    "Name": "Custom_Model",
    "Transform": {
      "posX": -0.009095477,
      "posY": 2.93908525,
      "posZ": 0.0147003159,
      "rotX": 5.70142856E-06,
      "rotY": 359.971069,
      "rotZ": 3.73948278E-05,
      "scaleX": 1.0,
      "scaleY": 1.0,
      "scaleZ": 1.0
    },
    "Nickname": "THREE STOREY RUIN",
    "Description": "TERRAIN CATEGORY: [c6c930]Area terrain[-]\r\nTERRAIN TRAITS: [1F87FF]Scaleable, Breachable, Light cover, Defensible , Obscuring[-]",
    "GMNotes": "",
    "AltLookAngle": {
      "x": 0.0,
      "y": 0.0,
      "z": 0.0
    },
    "ColorDiffuse": {
      "r": 0.6602787,
      "g": 0.6602787,
      "b": 0.6602787
    },
    "LayoutGroupSortIndex": 0,
    "Value": 0,
    "Locked": true,
    "Grid": true,
    "Snap": true,
    "IgnoreFoW": false,
    "MeasureMovement": false,
    "DragSelectable": true,
    "Autoraise": true,
    "Sticky": true,
    "Tooltip": true,
    "GridProjection": false,
    "HideWhenFaceDown": false,
    "Hands": false,
    "CustomMesh": {
      "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912108869/1AFAF16694B0CBEF6CD222334144FCAA7581FBDA/",
      "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794554175/892D44213E132546A15A01E898CEE59F66ACFE5D/",
      "NormalURL": "",
      "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912108869/1AFAF16694B0CBEF6CD222334144FCAA7581FBDA/",
      "Convex": false,
      "MaterialIndex": 3,
      "TypeIndex": 0,
      "CustomShader": {
        "SpecularColor": {
          "r": 1.0,
          "g": 1.0,
          "b": 1.0
        },
        "SpecularIntensity": 0.0,
        "SpecularSharpness": 2.0,
        "FresnelStrength": 0.0
      },
      "CastShadows": true
    },
    "LuaScript": "",
    "LuaScriptState": "",
    "XmlUI": ""
  },
  {
    "GUID": "fe5571",
    "Name": "Custom_Model",
    "Transform": {
      "posX": 0.0031952688,
      "posY": -0.010915041,
      "posZ": -0.00828582,
      "rotX": -1.12302146E-07,
      "rotY": 359.986023,
      "rotZ": 4.90050879E-05,
      "scaleX": 1.00000012,
      "scaleY": 1.0,
      "scaleZ": 1.00000012
    },
    "Nickname": "THREE STOREY RUIN",
    "Description": "TERRAIN CATEGORY: [c6c930]Area terrain[-]\r\nTERRAIN TRAITS: [1F87FF]Scaleable, Breachable, Light cover, Defensible , Obscuring[-]",
    "GMNotes": "",
    "AltLookAngle": {
      "x": 0.0,
      "y": 0.0,
      "z": 0.0
    },
    "ColorDiffuse": {
      "r": 0.6602787,
      "g": 0.6602787,
      "b": 0.6602787
    },
    "LayoutGroupSortIndex": 0,
    "Value": 0,
    "Locked": true,
    "Grid": true,
    "Snap": true,
    "IgnoreFoW": false,
    "MeasureMovement": false,
    "DragSelectable": true,
    "Autoraise": true,
    "Sticky": true,
    "Tooltip": true,
    "GridProjection": false,
    "HideWhenFaceDown": false,
    "Hands": false,
    "CustomMesh": {
      "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938911722433/FB1384DC6E77D19E0DD0DD6B0FDAE370AE82B53C/",
      "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794554175/892D44213E132546A15A01E898CEE59F66ACFE5D/",
      "NormalURL": "",
      "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938911722433/FB1384DC6E77D19E0DD0DD6B0FDAE370AE82B53C/",
      "Convex": false,
      "MaterialIndex": 1,
      "TypeIndex": 0,
      "CastShadows": true
    },
    "LuaScript": "",
    "LuaScriptState": "",
    "XmlUI": ""
  },
  {
    "GUID": "1a6bd4",
    "Name": "CardCustom",
    "Transform": {
      "posX": -2.13999915,
      "posY": 0.0,
      "posZ": -5.05,
      "rotX": 1.0694115E-06,
      "rotY": -3.08322788E-15,
      "rotZ": -3.30379748E-07,
      "scaleX": 2.792913,
      "scaleY": 0.065,
      "scaleZ": 3.910001
    },
    "Nickname": "",
    "Description": "",
    "GMNotes": "",
    "AltLookAngle": {
      "x": 0.0,
      "y": 0.0,
      "z": 0.0
    },
    "ColorDiffuse": {
      "r": 0.713235259,
      "g": 0.713235259,
      "b": 0.713235259
    },
    "LayoutGroupSortIndex": 0,
    "Value": 0,
    "Locked": true,
    "Grid": true,
    "Snap": true,
    "IgnoreFoW": false,
    "MeasureMovement": false,
    "DragSelectable": true,
    "Autoraise": true,
    "Sticky": true,
    "Tooltip": true,
    "GridProjection": false,
    "HideWhenFaceDown": true,
    "Hands": true,
    "CardID": 30400,
    "SidewaysCard": false,
    "CustomDeck": {
      "304": {
        "FaceURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794548479/1334E2934F85878167A301C71EBDE0DD7AB39D9C/",
        "BackURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794548479/1334E2934F85878167A301C71EBDE0DD7AB39D9C/",
        "NumWidth": 1,
        "NumHeight": 1,
        "BackIsHidden": true,
        "UniqueBack": false,
        "Type": 0
      }
    },
    "LuaScript": "",
    "LuaScriptState": "",
    "XmlUI": ""
  }
]
}]],
[[{
"GUID": "13eed9",
"Name": "Custom_Model",
"Transform": {
  "posX": -19.85,
  "posY": 0.97,
  "posZ": 10.48,
  "rotX": 0.0,
  "rotY": 223.0,
  "rotZ": 0.0,
  "scaleX": 1.0,
  "scaleY": 1.0,
  "scaleZ": 1.0
},
"Nickname": "TWO STOREY RUIN",
"Description": "",
"GMNotes": "",
"AltLookAngle": {
  "x": 0.0,
  "y": 0.0,
  "z": 0.0
},
"ColorDiffuse": {
  "r": 1.0,
  "g": 1.0,
  "b": 1.0
},
"LayoutGroupSortIndex": 0,
"Value": 0,
"Locked": true,
"Grid": true,
"Snap": true,
"IgnoreFoW": false,
"MeasureMovement": false,
"DragSelectable": true,
"Autoraise": true,
"Sticky": true,
"Tooltip": true,
"GridProjection": false,
"HideWhenFaceDown": false,
"Hands": false,
"CustomMesh": {
  "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700191697866339/512A215790C3FB9D46B89208BDB234D98D8C3350/",
  "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794552248/6D9B9FB570E97EA80128D58CD4A0EB295F654306/",
  "NormalURL": "",
  "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912201570/3CFC9BAA671D43615F4A56A37B443F1819EA1672/",
  "Convex": true,
  "MaterialIndex": 1,
  "TypeIndex": 0,
  "CastShadows": true
},
"LuaScript": "\nBCBtype = \"terrain\"\n",
"LuaScriptState": "",
"XmlUI": "",
"States": {
  "2": {
    "GUID": "862289",
    "Name": "Custom_Model",
    "Transform": {
      "posX": -27.2564983,
      "posY": 0.994030356,
      "posZ": 11.64174,
      "rotX": 0.0,
      "rotY": 270.0,
      "rotZ": 0.0,
      "scaleX": 1.0,
      "scaleY": 1.0,
      "scaleZ": 1.0
    },
    "Nickname": "TWO STOREY RUIN",
    "Description": "",
    "GMNotes": "",
    "AltLookAngle": {
      "x": 0.0,
      "y": 0.0,
      "z": 0.0
    },
    "ColorDiffuse": {
      "r": 1.0,
      "g": 1.0,
      "b": 1.0
    },
    "LayoutGroupSortIndex": 0,
    "Value": 0,
    "Locked": true,
    "Grid": true,
    "Snap": true,
    "IgnoreFoW": false,
    "MeasureMovement": false,
    "DragSelectable": true,
    "Autoraise": true,
    "Sticky": true,
    "Tooltip": true,
    "GridProjection": false,
    "HideWhenFaceDown": false,
    "Hands": false,
    "CustomMesh": {
      "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700191697866339/512A215790C3FB9D46B89208BDB234D98D8C3350/",
      "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794552248/6D9B9FB570E97EA80128D58CD4A0EB295F654306/",
      "NormalURL": "",
      "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912201570/3CFC9BAA671D43615F4A56A37B443F1819EA1672/",
      "Convex": true,
      "MaterialIndex": 1,
      "TypeIndex": 0,
      "CastShadows": true
    },
    "LuaScript": "",
    "LuaScriptState": "",
    "XmlUI": "",
    "ChildObjects": [
      {
        "GUID": "6452c2",
        "Name": "CardCustom",
        "Transform": {
          "posX": 2.13760066,
          "posY": 0.0,
          "posZ": -5.12226,
          "rotX": -0.000240696449,
          "rotY": 179.999969,
          "rotZ": 0.000153086949,
          "scaleX": 2.7929132,
          "scaleY": 0.065,
          "scaleZ": 3.91000128
        },
        "Nickname": "",
        "Description": "",
        "GMNotes": "",
        "AltLookAngle": {
          "x": 0.0,
          "y": 0.0,
          "z": 0.0
        },
        "ColorDiffuse": {
          "r": 0.713235259,
          "g": 0.713235259,
          "b": 0.713235259
        },
        "LayoutGroupSortIndex": 0,
        "Value": 0,
        "Locked": true,
        "Grid": true,
        "Snap": true,
        "IgnoreFoW": false,
        "MeasureMovement": false,
        "DragSelectable": true,
        "Autoraise": true,
        "Sticky": true,
        "Tooltip": true,
        "GridProjection": false,
        "HideWhenFaceDown": true,
        "Hands": true,
        "CardID": 30400,
        "SidewaysCard": false,
        "CustomDeck": {
          "304": {
            "FaceURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794548479/1334E2934F85878167A301C71EBDE0DD7AB39D9C/",
            "BackURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794548479/1334E2934F85878167A301C71EBDE0DD7AB39D9C/",
            "NumWidth": 1,
            "NumHeight": 1,
            "BackIsHidden": true,
            "UniqueBack": false,
            "Type": 0
          }
        },
        "LuaScript": "",
        "LuaScriptState": "",
        "XmlUI": ""
      }
    ]
  }
},
"ChildObjects": [
  {
    "GUID": "bfb4a7",
    "Name": "Custom_Model",
    "Transform": {
      "posX": 1.9836092,
      "posY": 3.21452641,
      "posZ": -1.94255877,
      "rotX": 359.992676,
      "rotY": 359.895325,
      "rotZ": 0.003873905,
      "scaleX": 1.0,
      "scaleY": 1.0,
      "scaleZ": 0.9999999
    },
    "Nickname": "",
    "Description": "",
    "GMNotes": "",
    "AltLookAngle": {
      "x": 0.0,
      "y": 0.0,
      "z": 0.0
    },
    "ColorDiffuse": {
      "r": 0.6627451,
      "g": 0.6627451,
      "b": 0.6627451
    },
    "LayoutGroupSortIndex": 0,
    "Value": 0,
    "Locked": true,
    "Grid": true,
    "Snap": true,
    "IgnoreFoW": false,
    "MeasureMovement": false,
    "DragSelectable": true,
    "Autoraise": true,
    "Sticky": true,
    "Tooltip": true,
    "GridProjection": false,
    "HideWhenFaceDown": false,
    "Hands": false,
    "CustomMesh": {
      "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2050876934859026362/8EDA2E480DFEC1B0B885AB4633074F004E96648D/",
      "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794554175/892D44213E132546A15A01E898CEE59F66ACFE5D/",
      "NormalURL": "",
      "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/2050876934859026362/8EDA2E480DFEC1B0B885AB4633074F004E96648D/",
      "Convex": false,
      "MaterialIndex": 1,
      "TypeIndex": 0,
      "CastShadows": true
    },
    "LuaScript": "",
    "LuaScriptState": "",
    "XmlUI": "",
    "PhysicsMaterial": {
      "StaticFriction": 1.0,
      "DynamicFriction": 0.7,
      "Bounciness": 0.0,
      "FrictionCombine": 0,
      "BounceCombine": 0
    },
    "Rigidbody": {
      "Mass": 1.0,
      "Drag": 0.1,
      "AngularDrag": 0.1,
      "UseGravity": true
    },
    "ChildObjects": [
      {
        "GUID": "3f2d4d",
        "Name": "CardCustom",
        "Transform": {
          "posX": -0.9610308,
          "posY": 0.0725631043,
          "posZ": 0.6029997,
          "rotX": -2.20303335E-07,
          "rotY": 90.08806,
          "rotZ": -2.3364754E-07,
          "scaleX": 0.9084988,
          "scaleY": 0.065,
          "scaleZ": 0.635936439
        },
        "Nickname": "",
        "Description": "",
        "GMNotes": "",
        "AltLookAngle": {
          "x": 0.0,
          "y": 0.0,
          "z": 0.0
        },
        "ColorDiffuse": {
          "r": 0.713235259,
          "g": 0.713235259,
          "b": 0.713235259
        },
        "LayoutGroupSortIndex": 0,
        "Value": 0,
        "Locked": false,
        "Grid": true,
        "Snap": true,
        "IgnoreFoW": false,
        "MeasureMovement": false,
        "DragSelectable": true,
        "Autoraise": true,
        "Sticky": true,
        "Tooltip": true,
        "GridProjection": false,
        "HideWhenFaceDown": true,
        "Hands": true,
        "CardID": 400,
        "SidewaysCard": false,
        "CustomDeck": {
          "4": {
            "FaceURL": "https://steamusercontent-a.akamaihd.net/ugc/2050876934859079198/D1FA4B09D02FEBA5BB9755137AAD285462824318/",
            "BackURL": "https://steamusercontent-a.akamaihd.net/ugc/2050876934859079198/D1FA4B09D02FEBA5BB9755137AAD285462824318/",
            "NumWidth": 1,
            "NumHeight": 1,
            "BackIsHidden": true,
            "UniqueBack": false,
            "Type": 1
          }
        },
        "LuaScript": "",
        "LuaScriptState": "",
        "XmlUI": ""
      }
    ]
  },
  {
    "GUID": "5bbf29",
    "Name": "CardCustom",
    "Transform": {
      "posX": 2.14234233,
      "posY": 0.0,
      "posZ": -5.122262,
      "rotX": -8.797401E-08,
      "rotY": 180.0,
      "rotZ": -3.280339E-07,
      "scaleX": 2.79291272,
      "scaleY": 0.065,
      "scaleZ": 3.91000056
    },
    "Nickname": "",
    "Description": "",
    "GMNotes": "",
    "AltLookAngle": {
      "x": 0.0,
      "y": 0.0,
      "z": 0.0
    },
    "ColorDiffuse": {
      "r": 0.713235259,
      "g": 0.713235259,
      "b": 0.713235259
    },
    "LayoutGroupSortIndex": 0,
    "Value": 0,
    "Locked": true,
    "Grid": true,
    "Snap": true,
    "IgnoreFoW": false,
    "MeasureMovement": false,
    "DragSelectable": true,
    "Autoraise": true,
    "Sticky": true,
    "Tooltip": true,
    "GridProjection": false,
    "HideWhenFaceDown": true,
    "Hands": true,
    "CardID": 30400,
    "SidewaysCard": false,
    "CustomDeck": {
      "304": {
        "FaceURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794548479/1334E2934F85878167A301C71EBDE0DD7AB39D9C/",
        "BackURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794548479/1334E2934F85878167A301C71EBDE0DD7AB39D9C/",
        "NumWidth": 1,
        "NumHeight": 1,
        "BackIsHidden": true,
        "UniqueBack": false,
        "Type": 0
      }
    },
    "LuaScript": "",
    "LuaScriptState": "",
    "XmlUI": ""
  }
]
}]],
[[{
"GUID": "5685a1",
"Name": "Custom_Model",
"Transform": {
  "posX": -6.4585,
  "posY": 0.97,
  "posZ": -8.02214,
  "rotX": 0.0,
  "rotY": 165.5,
  "rotZ": 0.0,
  "scaleX": 1.0,
  "scaleY": 1.0,
  "scaleZ": 1.0
},
"Nickname": "THREE STOREY RUIN",
"Description": "",
"GMNotes": "",
"AltLookAngle": {
  "x": 0.0,
  "y": 0.0,
  "z": 0.0
},
"ColorDiffuse": {
  "r": 1.0,
  "g": 1.0,
  "b": 1.0
},
"LayoutGroupSortIndex": 0,
"Value": 0,
"Locked": true,
"Grid": true,
"Snap": true,
"IgnoreFoW": false,
"MeasureMovement": false,
"DragSelectable": true,
"Autoraise": true,
"Sticky": true,
"Tooltip": true,
"GridProjection": false,
"HideWhenFaceDown": false,
"Hands": false,
"CustomMesh": {
  "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794615637/3243BEE6343D5C13E960186B86AC320A41183927/",
  "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794552248/6D9B9FB570E97EA80128D58CD4A0EB295F654306/",
  "NormalURL": "",
  "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912201570/3CFC9BAA671D43615F4A56A37B443F1819EA1672/",
  "Convex": true,
  "MaterialIndex": 1,
  "TypeIndex": 0,
  "CastShadows": true
},
"LuaScript": "",
"LuaScriptState": "",
"XmlUI": "",
"States": {
  "2": {
    "GUID": "5c2d0f",
    "Name": "Custom_Model",
    "Transform": {
      "posX": 15.0,
      "posY": 0.97,
      "posZ": 15.0,
      "rotX": 0.0,
      "rotY": 90.0,
      "rotZ": 0.0,
      "scaleX": 1.0,
      "scaleY": 1.0,
      "scaleZ": 1.0
    },
    "Nickname": "THREE STOREY RUIN",
    "Description": "",
    "GMNotes": "",
    "AltLookAngle": {
      "x": 0.0,
      "y": 0.0,
      "z": 0.0
    },
    "ColorDiffuse": {
      "r": 1.0,
      "g": 1.0,
      "b": 1.0
    },
    "LayoutGroupSortIndex": 0,
    "Value": 0,
    "Locked": true,
    "Grid": true,
    "Snap": true,
    "IgnoreFoW": false,
    "MeasureMovement": false,
    "DragSelectable": true,
    "Autoraise": true,
    "Sticky": true,
    "Tooltip": true,
    "GridProjection": false,
    "HideWhenFaceDown": false,
    "Hands": false,
    "CustomMesh": {
      "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794615637/3243BEE6343D5C13E960186B86AC320A41183927/",
      "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794552248/6D9B9FB570E97EA80128D58CD4A0EB295F654306/",
      "NormalURL": "",
      "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912201570/3CFC9BAA671D43615F4A56A37B443F1819EA1672/",
      "Convex": true,
      "MaterialIndex": 1,
      "TypeIndex": 0,
      "CastShadows": true
    },
    "LuaScript": "",
    "LuaScriptState": "",
    "XmlUI": "",
    "ChildObjects": [
      {
        "GUID": "a55a24",
        "Name": "Custom_Model",
        "Transform": {
          "posX": -0.009057048,
          "posY": 2.94,
          "posZ": 0.0138750086,
          "rotX": 359.983917,
          "rotY": 359.972229,
          "rotZ": -0.001307647,
          "scaleX": 0.9999999,
          "scaleY": 1.0,
          "scaleZ": 1.0
        },
        "Nickname": "THREE STOREY RUIN",
        "Description": "TERRAIN CATEGORY: [c6c930]Area terrain[-]\r\nTERRAIN TRAITS: [1F87FF]Scaleable, Breachable, Light cover, Defensible , Obscuring[-]",
        "GMNotes": "",
        "AltLookAngle": {
          "x": 0.0,
          "y": 0.0,
          "z": 0.0
        },
        "ColorDiffuse": {
          "r": 0.6602787,
          "g": 0.6602787,
          "b": 0.6602787
        },
        "LayoutGroupSortIndex": 0,
        "Value": 0,
        "Locked": true,
        "Grid": true,
        "Snap": true,
        "IgnoreFoW": false,
        "MeasureMovement": false,
        "DragSelectable": true,
        "Autoraise": true,
        "Sticky": true,
        "Tooltip": true,
        "GridProjection": false,
        "HideWhenFaceDown": false,
        "Hands": false,
        "CustomMesh": {
          "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912108869/1AFAF16694B0CBEF6CD222334144FCAA7581FBDA/",
          "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794554175/892D44213E132546A15A01E898CEE59F66ACFE5D/",
          "NormalURL": "",
          "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912108869/1AFAF16694B0CBEF6CD222334144FCAA7581FBDA/",
          "Convex": false,
          "MaterialIndex": 1,
          "TypeIndex": 0,
          "CastShadows": true
        },
        "LuaScript": "",
        "LuaScriptState": "",
        "XmlUI": ""
      },
      {
        "GUID": "1a6bd4",
        "Name": "CardCustom",
        "Transform": {
          "posX": -2.14004683,
          "posY": -6.198883E-06,
          "posZ": -5.049985,
          "rotX": -4.020952E-05,
          "rotY": 0.000525924552,
          "rotZ": 6.76622E-05,
          "scaleX": 2.79291344,
          "scaleY": 0.065,
          "scaleZ": 3.91000152
        },
        "Nickname": "",
        "Description": "",
        "GMNotes": "",
        "AltLookAngle": {
          "x": 0.0,
          "y": 0.0,
          "z": 0.0
        },
        "ColorDiffuse": {
          "r": 0.713235259,
          "g": 0.713235259,
          "b": 0.713235259
        },
        "LayoutGroupSortIndex": 0,
        "Value": 0,
        "Locked": true,
        "Grid": true,
        "Snap": true,
        "IgnoreFoW": false,
        "MeasureMovement": false,
        "DragSelectable": true,
        "Autoraise": true,
        "Sticky": true,
        "Tooltip": true,
        "GridProjection": false,
        "HideWhenFaceDown": true,
        "Hands": true,
        "CardID": 30400,
        "SidewaysCard": false,
        "CustomDeck": {
          "304": {
            "FaceURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794548479/1334E2934F85878167A301C71EBDE0DD7AB39D9C/",
            "BackURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794548479/1334E2934F85878167A301C71EBDE0DD7AB39D9C/",
            "NumWidth": 1,
            "NumHeight": 1,
            "BackIsHidden": true,
            "UniqueBack": false,
            "Type": 0
          }
        },
        "LuaScript": "",
        "LuaScriptState": "",
        "XmlUI": ""
      }
    ]
  },
  "3": {
    "GUID": "c62e13",
    "Name": "Custom_Model",
    "Transform": {
      "posX": 15.0,
      "posY": 0.97,
      "posZ": 15.0,
      "rotX": 0.0,
      "rotY": 90.0,
      "rotZ": 0.0,
      "scaleX": 1.0,
      "scaleY": 1.0,
      "scaleZ": 1.0
    },
    "Nickname": "THREE STOREY RUIN",
    "Description": "",
    "GMNotes": "",
    "AltLookAngle": {
      "x": 0.0,
      "y": 0.0,
      "z": 0.0
    },
    "ColorDiffuse": {
      "r": 1.0,
      "g": 1.0,
      "b": 1.0
    },
    "LayoutGroupSortIndex": 0,
    "Value": 0,
    "Locked": true,
    "Grid": true,
    "Snap": true,
    "IgnoreFoW": false,
    "MeasureMovement": false,
    "DragSelectable": true,
    "Autoraise": true,
    "Sticky": true,
    "Tooltip": true,
    "GridProjection": false,
    "HideWhenFaceDown": false,
    "Hands": false,
    "CustomMesh": {
      "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794615637/3243BEE6343D5C13E960186B86AC320A41183927/",
      "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794552248/6D9B9FB570E97EA80128D58CD4A0EB295F654306/",
      "NormalURL": "",
      "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912201570/3CFC9BAA671D43615F4A56A37B443F1819EA1672/",
      "Convex": true,
      "MaterialIndex": 1,
      "TypeIndex": 0,
      "CastShadows": true
    },
    "LuaScript": "",
    "LuaScriptState": "",
    "XmlUI": "",
    "ChildObjects": [
      {
        "GUID": "6452c2",
        "Name": "CardCustom",
        "Transform": {
          "posX": -2.136197,
          "posY": -2.58482532E-06,
          "posZ": -5.054414,
          "rotX": 2.19344838E-05,
          "rotY": -0.00102452841,
          "rotZ": 0.000121076075,
          "scaleX": 2.792914,
          "scaleY": 0.065,
          "scaleZ": 3.91000152
        },
        "Nickname": "",
        "Description": "",
        "GMNotes": "",
        "AltLookAngle": {
          "x": 0.0,
          "y": 0.0,
          "z": 0.0
        },
        "ColorDiffuse": {
          "r": 0.713235259,
          "g": 0.713235259,
          "b": 0.713235259
        },
        "LayoutGroupSortIndex": 0,
        "Value": 0,
        "Locked": true,
        "Grid": true,
        "Snap": true,
        "IgnoreFoW": false,
        "MeasureMovement": false,
        "DragSelectable": true,
        "Autoraise": true,
        "Sticky": true,
        "Tooltip": true,
        "GridProjection": false,
        "HideWhenFaceDown": true,
        "Hands": true,
        "CardID": 30400,
        "SidewaysCard": false,
        "CustomDeck": {
          "304": {
            "FaceURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794548479/1334E2934F85878167A301C71EBDE0DD7AB39D9C/",
            "BackURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794548479/1334E2934F85878167A301C71EBDE0DD7AB39D9C/",
            "NumWidth": 1,
            "NumHeight": 1,
            "BackIsHidden": true,
            "UniqueBack": false,
            "Type": 0
          }
        },
        "LuaScript": "",
        "LuaScriptState": "",
        "XmlUI": ""
      }
    ]
  }
},
"ChildObjects": [
  {
    "GUID": "44e827",
    "Name": "Custom_Model",
    "Transform": {
      "posX": -0.009095477,
      "posY": 2.93908525,
      "posZ": 0.0147003159,
      "rotX": 5.70142856E-06,
      "rotY": 359.971069,
      "rotZ": 3.73948278E-05,
      "scaleX": 1.0,
      "scaleY": 1.0,
      "scaleZ": 1.0
    },
    "Nickname": "THREE STOREY RUIN",
    "Description": "TERRAIN CATEGORY: [c6c930]Area terrain[-]\r\nTERRAIN TRAITS: [1F87FF]Scaleable, Breachable, Light cover, Defensible , Obscuring[-]",
    "GMNotes": "",
    "AltLookAngle": {
      "x": 0.0,
      "y": 0.0,
      "z": 0.0
    },
    "ColorDiffuse": {
      "r": 0.6602787,
      "g": 0.6602787,
      "b": 0.6602787
    },
    "LayoutGroupSortIndex": 0,
    "Value": 0,
    "Locked": true,
    "Grid": true,
    "Snap": true,
    "IgnoreFoW": false,
    "MeasureMovement": false,
    "DragSelectable": true,
    "Autoraise": true,
    "Sticky": true,
    "Tooltip": true,
    "GridProjection": false,
    "HideWhenFaceDown": false,
    "Hands": false,
    "CustomMesh": {
      "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912108869/1AFAF16694B0CBEF6CD222334144FCAA7581FBDA/",
      "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794554175/892D44213E132546A15A01E898CEE59F66ACFE5D/",
      "NormalURL": "",
      "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912108869/1AFAF16694B0CBEF6CD222334144FCAA7581FBDA/",
      "Convex": false,
      "MaterialIndex": 3,
      "TypeIndex": 0,
      "CustomShader": {
        "SpecularColor": {
          "r": 1.0,
          "g": 1.0,
          "b": 1.0
        },
        "SpecularIntensity": 0.0,
        "SpecularSharpness": 2.0,
        "FresnelStrength": 0.0
      },
      "CastShadows": true
    },
    "LuaScript": "",
    "LuaScriptState": "",
    "XmlUI": ""
  },
  {
    "GUID": "fe5571",
    "Name": "Custom_Model",
    "Transform": {
      "posX": 0.0031952688,
      "posY": -0.010915041,
      "posZ": -0.00828582,
      "rotX": -1.12302146E-07,
      "rotY": 359.986023,
      "rotZ": 4.90050879E-05,
      "scaleX": 1.00000012,
      "scaleY": 1.0,
      "scaleZ": 1.00000012
    },
    "Nickname": "THREE STOREY RUIN",
    "Description": "TERRAIN CATEGORY: [c6c930]Area terrain[-]\r\nTERRAIN TRAITS: [1F87FF]Scaleable, Breachable, Light cover, Defensible , Obscuring[-]",
    "GMNotes": "",
    "AltLookAngle": {
      "x": 0.0,
      "y": 0.0,
      "z": 0.0
    },
    "ColorDiffuse": {
      "r": 0.6602787,
      "g": 0.6602787,
      "b": 0.6602787
    },
    "LayoutGroupSortIndex": 0,
    "Value": 0,
    "Locked": true,
    "Grid": true,
    "Snap": true,
    "IgnoreFoW": false,
    "MeasureMovement": false,
    "DragSelectable": true,
    "Autoraise": true,
    "Sticky": true,
    "Tooltip": true,
    "GridProjection": false,
    "HideWhenFaceDown": false,
    "Hands": false,
    "CustomMesh": {
      "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938911722433/FB1384DC6E77D19E0DD0DD6B0FDAE370AE82B53C/",
      "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794554175/892D44213E132546A15A01E898CEE59F66ACFE5D/",
      "NormalURL": "",
      "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938911722433/FB1384DC6E77D19E0DD0DD6B0FDAE370AE82B53C/",
      "Convex": false,
      "MaterialIndex": 1,
      "TypeIndex": 0,
      "CastShadows": true
    },
    "LuaScript": "",
    "LuaScriptState": "",
    "XmlUI": ""
  },
  {
    "GUID": "1a6bd4",
    "Name": "CardCustom",
    "Transform": {
      "posX": -2.13999915,
      "posY": 0.0,
      "posZ": -5.05,
      "rotX": 1.0694115E-06,
      "rotY": -3.08322788E-15,
      "rotZ": -3.30379748E-07,
      "scaleX": 2.792913,
      "scaleY": 0.065,
      "scaleZ": 3.910001
    },
    "Nickname": "",
    "Description": "",
    "GMNotes": "",
    "AltLookAngle": {
      "x": 0.0,
      "y": 0.0,
      "z": 0.0
    },
    "ColorDiffuse": {
      "r": 0.713235259,
      "g": 0.713235259,
      "b": 0.713235259
    },
    "LayoutGroupSortIndex": 0,
    "Value": 0,
    "Locked": true,
    "Grid": true,
    "Snap": true,
    "IgnoreFoW": false,
    "MeasureMovement": false,
    "DragSelectable": true,
    "Autoraise": true,
    "Sticky": true,
    "Tooltip": true,
    "GridProjection": false,
    "HideWhenFaceDown": true,
    "Hands": true,
    "CardID": 30400,
    "SidewaysCard": false,
    "CustomDeck": {
      "304": {
        "FaceURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794548479/1334E2934F85878167A301C71EBDE0DD7AB39D9C/",
        "BackURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794548479/1334E2934F85878167A301C71EBDE0DD7AB39D9C/",
        "NumWidth": 1,
        "NumHeight": 1,
        "BackIsHidden": true,
        "UniqueBack": false,
        "Type": 0
      }
    },
    "LuaScript": "",
    "LuaScriptState": "",
    "XmlUI": ""
  }
]
}]],
[[{
"GUID": "a7ed10",
"Name": "Custom_Model",
"Transform": {
  "posX": -6.517142,
  "posY": 3.49,
  "posZ": 6.243064,
  "rotX": -0.000258142565,
  "rotY": 0.0,
  "rotZ": -0.000154085821,
  "scaleX": 0.44,
  "scaleY": 0.440000743,
  "scaleZ": 0.52
},
"Nickname": "Container",
"Description": "",
"GMNotes": "",
"AltLookAngle": {
  "x": 0.0,
  "y": 0.0,
  "z": 0.0
},
"ColorDiffuse": {
  "r": 0.203920752,
  "g": 0.18431291,
  "b": 0.180391341
},
"LayoutGroupSortIndex": 0,
"Value": 0,
"Locked": true,
"Grid": true,
"Snap": true,
"IgnoreFoW": false,
"MeasureMovement": false,
"DragSelectable": true,
"Autoraise": true,
"Sticky": true,
"Tooltip": true,
"GridProjection": false,
"HideWhenFaceDown": false,
"Hands": false,
"CustomMesh": {
  "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1018320153794846738/DF21B27B996BAF4470C34C55391A5F586443F54D/",
  "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1018320153794846900/2AD6701546E10D9B7C6328FDEAA057765BB42FAC/",
  "NormalURL": "https://steamusercontent-a.akamaihd.net/ugc/1018320153794847254/DBB28E40ADDFF4719B17E1CEDDE73850398E1F89/",
  "ColliderURL": "",
  "Convex": true,
  "MaterialIndex": 3,
  "TypeIndex": 0,
  "CastShadows": true
},
"LuaScript": "",
"LuaScriptState": "",
"XmlUI": "",
"ChildObjects": [
  {
    "GUID": "322faa",
    "Name": "Custom_Model",
    "Transform": {
      "posX": -3.350733E-05,
      "posY": -5.703194,
      "posZ": -2.281413E-05,
      "rotX": 0.00025679465,
      "rotY": 0.0035871095,
      "rotZ": 0.000154398775,
      "scaleX": 1.00081849,
      "scaleY": 1.0,
      "scaleZ": 1.00081849
    },
    "Nickname": "Armoured Container | [CC99CC]Obstacle[-]                           [00BFFF]Light Cover, Scaleable, Exposed Position[-]                    2.5\" height/width, 5\" length",
    "Description": "",
    "GMNotes": "",
    "AltLookAngle": {
      "x": 0.0,
      "y": 0.0,
      "z": 0.0
    },
    "ColorDiffuse": {
      "r": 0.203921527,
      "g": 0.184313685,
      "b": 0.180392116
    },
    "LayoutGroupSortIndex": 0,
    "Value": 0,
    "Locked": true,
    "Grid": true,
    "Snap": true,
    "IgnoreFoW": false,
    "MeasureMovement": false,
    "DragSelectable": true,
    "Autoraise": true,
    "Sticky": true,
    "Tooltip": true,
    "GridProjection": false,
    "HideWhenFaceDown": false,
    "Hands": false,
    "CustomMesh": {
      "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1018320153794846738/DF21B27B996BAF4470C34C55391A5F586443F54D/",
      "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1018320153794846900/2AD6701546E10D9B7C6328FDEAA057765BB42FAC/",
      "NormalURL": "https://steamusercontent-a.akamaihd.net/ugc/1018320153794847254/DBB28E40ADDFF4719B17E1CEDDE73850398E1F89/",
      "ColliderURL": "",
      "Convex": true,
      "MaterialIndex": 3,
      "TypeIndex": 0,
      "CastShadows": true
    },
    "LuaScript": "",
    "LuaScriptState": "",
    "XmlUI": ""
  }
]
}]],
[[{
"GUID": "b2c547",
"Name": "Custom_Model",
"Transform": {
  "posX": -6.04303932,
  "posY": 0.97,
  "posZ": 12.2459564,
  "rotX": 0.0,
  "rotY": 255.0,
  "rotZ": 0.0,
  "scaleX": 1.0,
  "scaleY": 1.0,
  "scaleZ": 1.0
},
"Nickname": "TWO STOREY RUIN",
"Description": "",
"GMNotes": "",
"AltLookAngle": {
  "x": 0.0,
  "y": 0.0,
  "z": 0.0
},
"ColorDiffuse": {
  "r": 1.0,
  "g": 1.0,
  "b": 1.0
},
"LayoutGroupSortIndex": 0,
"Value": 0,
"Locked": true,
"Grid": true,
"Snap": true,
"IgnoreFoW": false,
"MeasureMovement": false,
"DragSelectable": true,
"Autoraise": true,
"Sticky": true,
"Tooltip": true,
"GridProjection": false,
"HideWhenFaceDown": false,
"Hands": false,
"CustomMesh": {
  "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700191697866339/512A215790C3FB9D46B89208BDB234D98D8C3350/",
  "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794552248/6D9B9FB570E97EA80128D58CD4A0EB295F654306/",
  "NormalURL": "",
  "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912201570/3CFC9BAA671D43615F4A56A37B443F1819EA1672/",
  "Convex": true,
  "MaterialIndex": 1,
  "TypeIndex": 0,
  "CastShadows": true
},
"LuaScript": "\nBCBtype = \"terrain\"\n",
"LuaScriptState": "",
"XmlUI": "",
"States": {
  "2": {
    "GUID": "72b111",
    "Name": "Custom_Model",
    "Transform": {
      "posX": -10.71,
      "posY": 0.97,
      "posZ": 14.49,
      "rotX": 0.0,
      "rotY": 270.0,
      "rotZ": 0.0,
      "scaleX": 1.0,
      "scaleY": 1.0,
      "scaleZ": 1.0
    },
    "Nickname": "TWO STOREY RUIN",
    "Description": "",
    "GMNotes": "",
    "AltLookAngle": {
      "x": 0.0,
      "y": 0.0,
      "z": 0.0
    },
    "ColorDiffuse": {
      "r": 1.0,
      "g": 1.0,
      "b": 1.0
    },
    "LayoutGroupSortIndex": 0,
    "Value": 0,
    "Locked": true,
    "Grid": true,
    "Snap": true,
    "IgnoreFoW": false,
    "MeasureMovement": false,
    "DragSelectable": true,
    "Autoraise": true,
    "Sticky": true,
    "Tooltip": true,
    "GridProjection": false,
    "HideWhenFaceDown": false,
    "Hands": false,
    "CustomMesh": {
      "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700191697866339/512A215790C3FB9D46B89208BDB234D98D8C3350/",
      "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794552248/6D9B9FB570E97EA80128D58CD4A0EB295F654306/",
      "NormalURL": "",
      "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912201570/3CFC9BAA671D43615F4A56A37B443F1819EA1672/",
      "Convex": true,
      "MaterialIndex": 1,
      "TypeIndex": 0,
      "CastShadows": true
    },
    "LuaScript": "",
    "LuaScriptState": "",
    "XmlUI": "",
    "ChildObjects": [
      {
        "GUID": "6452c2",
        "Name": "CardCustom",
        "Transform": {
          "posX": 2.13760066,
          "posY": 0.0,
          "posZ": -5.12226,
          "rotX": -0.000240696449,
          "rotY": 179.999969,
          "rotZ": 0.000153086949,
          "scaleX": 2.7929132,
          "scaleY": 0.065,
          "scaleZ": 3.91000128
        },
        "Nickname": "",
        "Description": "",
        "GMNotes": "",
        "AltLookAngle": {
          "x": 0.0,
          "y": 0.0,
          "z": 0.0
        },
        "ColorDiffuse": {
          "r": 0.713235259,
          "g": 0.713235259,
          "b": 0.713235259
        },
        "LayoutGroupSortIndex": 0,
        "Value": 0,
        "Locked": true,
        "Grid": true,
        "Snap": true,
        "IgnoreFoW": false,
        "MeasureMovement": false,
        "DragSelectable": true,
        "Autoraise": true,
        "Sticky": true,
        "Tooltip": true,
        "GridProjection": false,
        "HideWhenFaceDown": true,
        "Hands": true,
        "CardID": 30400,
        "SidewaysCard": false,
        "CustomDeck": {
          "304": {
            "FaceURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794548479/1334E2934F85878167A301C71EBDE0DD7AB39D9C/",
            "BackURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794548479/1334E2934F85878167A301C71EBDE0DD7AB39D9C/",
            "NumWidth": 1,
            "NumHeight": 1,
            "BackIsHidden": true,
            "UniqueBack": false,
            "Type": 0
          }
        },
        "LuaScript": "",
        "LuaScriptState": "",
        "XmlUI": ""
      }
    ]
  }
},
"ChildObjects": [
  {
    "GUID": "bfb4a7",
    "Name": "Custom_Model",
    "Transform": {
      "posX": 1.9836092,
      "posY": 3.21452641,
      "posZ": -1.94255877,
      "rotX": 359.992676,
      "rotY": 359.895325,
      "rotZ": 0.003873905,
      "scaleX": 1.0,
      "scaleY": 1.0,
      "scaleZ": 0.9999999
    },
    "Nickname": "",
    "Description": "",
    "GMNotes": "",
    "AltLookAngle": {
      "x": 0.0,
      "y": 0.0,
      "z": 0.0
    },
    "ColorDiffuse": {
      "r": 0.6627451,
      "g": 0.6627451,
      "b": 0.6627451
    },
    "LayoutGroupSortIndex": 0,
    "Value": 0,
    "Locked": true,
    "Grid": true,
    "Snap": true,
    "IgnoreFoW": false,
    "MeasureMovement": false,
    "DragSelectable": true,
    "Autoraise": true,
    "Sticky": true,
    "Tooltip": true,
    "GridProjection": false,
    "HideWhenFaceDown": false,
    "Hands": false,
    "CustomMesh": {
      "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2050876934859026362/8EDA2E480DFEC1B0B885AB4633074F004E96648D/",
      "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794554175/892D44213E132546A15A01E898CEE59F66ACFE5D/",
      "NormalURL": "",
      "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/2050876934859026362/8EDA2E480DFEC1B0B885AB4633074F004E96648D/",
      "Convex": false,
      "MaterialIndex": 1,
      "TypeIndex": 0,
      "CastShadows": true
    },
    "LuaScript": "",
    "LuaScriptState": "",
    "XmlUI": "",
    "PhysicsMaterial": {
      "StaticFriction": 1.0,
      "DynamicFriction": 0.7,
      "Bounciness": 0.0,
      "FrictionCombine": 0,
      "BounceCombine": 0
    },
    "Rigidbody": {
      "Mass": 1.0,
      "Drag": 0.1,
      "AngularDrag": 0.1,
      "UseGravity": true
    },
    "ChildObjects": [
      {
        "GUID": "3f2d4d",
        "Name": "CardCustom",
        "Transform": {
          "posX": -0.9610308,
          "posY": 0.0725631043,
          "posZ": 0.6029997,
          "rotX": -2.20303335E-07,
          "rotY": 90.08806,
          "rotZ": -2.3364754E-07,
          "scaleX": 0.9084988,
          "scaleY": 0.065,
          "scaleZ": 0.635936439
        },
        "Nickname": "",
        "Description": "",
        "GMNotes": "",
        "AltLookAngle": {
          "x": 0.0,
          "y": 0.0,
          "z": 0.0
        },
        "ColorDiffuse": {
          "r": 0.713235259,
          "g": 0.713235259,
          "b": 0.713235259
        },
        "LayoutGroupSortIndex": 0,
        "Value": 0,
        "Locked": false,
        "Grid": true,
        "Snap": true,
        "IgnoreFoW": false,
        "MeasureMovement": false,
        "DragSelectable": true,
        "Autoraise": true,
        "Sticky": true,
        "Tooltip": true,
        "GridProjection": false,
        "HideWhenFaceDown": true,
        "Hands": true,
        "CardID": 400,
        "SidewaysCard": false,
        "CustomDeck": {
          "4": {
            "FaceURL": "https://steamusercontent-a.akamaihd.net/ugc/2050876934859079198/D1FA4B09D02FEBA5BB9755137AAD285462824318/",
            "BackURL": "https://steamusercontent-a.akamaihd.net/ugc/2050876934859079198/D1FA4B09D02FEBA5BB9755137AAD285462824318/",
            "NumWidth": 1,
            "NumHeight": 1,
            "BackIsHidden": true,
            "UniqueBack": false,
            "Type": 1
          }
        },
        "LuaScript": "",
        "LuaScriptState": "",
        "XmlUI": ""
      }
    ]
  },
  {
    "GUID": "5bbf29",
    "Name": "CardCustom",
    "Transform": {
      "posX": 2.14234233,
      "posY": 0.0,
      "posZ": -5.122262,
      "rotX": -8.797401E-08,
      "rotY": 180.0,
      "rotZ": -3.280339E-07,
      "scaleX": 2.79291272,
      "scaleY": 0.065,
      "scaleZ": 3.91000056
    },
    "Nickname": "",
    "Description": "",
    "GMNotes": "",
    "AltLookAngle": {
      "x": 0.0,
      "y": 0.0,
      "z": 0.0
    },
    "ColorDiffuse": {
      "r": 0.713235259,
      "g": 0.713235259,
      "b": 0.713235259
    },
    "LayoutGroupSortIndex": 0,
    "Value": 0,
    "Locked": true,
    "Grid": true,
    "Snap": true,
    "IgnoreFoW": false,
    "MeasureMovement": false,
    "DragSelectable": true,
    "Autoraise": true,
    "Sticky": true,
    "Tooltip": true,
    "GridProjection": false,
    "HideWhenFaceDown": true,
    "Hands": true,
    "CardID": 30400,
    "SidewaysCard": false,
    "CustomDeck": {
      "304": {
        "FaceURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794548479/1334E2934F85878167A301C71EBDE0DD7AB39D9C/",
        "BackURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794548479/1334E2934F85878167A301C71EBDE0DD7AB39D9C/",
        "NumWidth": 1,
        "NumHeight": 1,
        "BackIsHidden": true,
        "UniqueBack": false,
        "Type": 0
      }
    },
    "LuaScript": "",
    "LuaScriptState": "",
    "XmlUI": ""
  }
]
}]],
[[{
"GUID": "308385",
"Name": "Custom_Model",
"Transform": {
  "posX": 6.04,
  "posY": 0.97,
  "posZ": -12.25,
  "rotX": 0.0,
  "rotY": 75.0,
  "rotZ": 0.0,
  "scaleX": 1.0,
  "scaleY": 1.0,
  "scaleZ": 1.0
},
"Nickname": "TWO STOREY RUIN",
"Description": "",
"GMNotes": "",
"AltLookAngle": {
  "x": 0.0,
  "y": 0.0,
  "z": 0.0
},
"ColorDiffuse": {
  "r": 1.0,
  "g": 1.0,
  "b": 1.0
},
"LayoutGroupSortIndex": 0,
"Value": 0,
"Locked": true,
"Grid": true,
"Snap": true,
"IgnoreFoW": false,
"MeasureMovement": false,
"DragSelectable": true,
"Autoraise": true,
"Sticky": true,
"Tooltip": true,
"GridProjection": false,
"HideWhenFaceDown": false,
"Hands": false,
"CustomMesh": {
  "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700191697866339/512A215790C3FB9D46B89208BDB234D98D8C3350/",
  "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794552248/6D9B9FB570E97EA80128D58CD4A0EB295F654306/",
  "NormalURL": "",
  "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912201570/3CFC9BAA671D43615F4A56A37B443F1819EA1672/",
  "Convex": true,
  "MaterialIndex": 1,
  "TypeIndex": 0,
  "CastShadows": true
},
"LuaScript": "\nBCBtype = \"terrain\"\n",
"LuaScriptState": "",
"XmlUI": "",
"States": {
  "2": {
    "GUID": "34f371",
    "Name": "Custom_Model",
    "Transform": {
      "posX": -5.31420565,
      "posY": 0.994030356,
      "posZ": -19.4556,
      "rotX": 0.0,
      "rotY": 270.0,
      "rotZ": 0.0,
      "scaleX": 1.0,
      "scaleY": 1.0,
      "scaleZ": 1.0
    },
    "Nickname": "TWO STOREY RUIN",
    "Description": "",
    "GMNotes": "",
    "AltLookAngle": {
      "x": 0.0,
      "y": 0.0,
      "z": 0.0
    },
    "ColorDiffuse": {
      "r": 1.0,
      "g": 1.0,
      "b": 1.0
    },
    "LayoutGroupSortIndex": 0,
    "Value": 0,
    "Locked": true,
    "Grid": true,
    "Snap": true,
    "IgnoreFoW": false,
    "MeasureMovement": false,
    "DragSelectable": true,
    "Autoraise": true,
    "Sticky": true,
    "Tooltip": true,
    "GridProjection": false,
    "HideWhenFaceDown": false,
    "Hands": false,
    "CustomMesh": {
      "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700191697866339/512A215790C3FB9D46B89208BDB234D98D8C3350/",
      "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794552248/6D9B9FB570E97EA80128D58CD4A0EB295F654306/",
      "NormalURL": "",
      "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912201570/3CFC9BAA671D43615F4A56A37B443F1819EA1672/",
      "Convex": true,
      "MaterialIndex": 1,
      "TypeIndex": 0,
      "CastShadows": true
    },
    "LuaScript": "",
    "LuaScriptState": "",
    "XmlUI": "",
    "ChildObjects": [
      {
        "GUID": "6452c2",
        "Name": "CardCustom",
        "Transform": {
          "posX": 2.13760066,
          "posY": 0.0,
          "posZ": -5.12226,
          "rotX": -0.000240696449,
          "rotY": 179.999969,
          "rotZ": 0.000153086949,
          "scaleX": 2.7929132,
          "scaleY": 0.065,
          "scaleZ": 3.91000128
        },
        "Nickname": "",
        "Description": "",
        "GMNotes": "",
        "AltLookAngle": {
          "x": 0.0,
          "y": 0.0,
          "z": 0.0
        },
        "ColorDiffuse": {
          "r": 0.713235259,
          "g": 0.713235259,
          "b": 0.713235259
        },
        "LayoutGroupSortIndex": 0,
        "Value": 0,
        "Locked": true,
        "Grid": true,
        "Snap": true,
        "IgnoreFoW": false,
        "MeasureMovement": false,
        "DragSelectable": true,
        "Autoraise": true,
        "Sticky": true,
        "Tooltip": true,
        "GridProjection": false,
        "HideWhenFaceDown": true,
        "Hands": true,
        "CardID": 30400,
        "SidewaysCard": false,
        "CustomDeck": {
          "304": {
            "FaceURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794548479/1334E2934F85878167A301C71EBDE0DD7AB39D9C/",
            "BackURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794548479/1334E2934F85878167A301C71EBDE0DD7AB39D9C/",
            "NumWidth": 1,
            "NumHeight": 1,
            "BackIsHidden": true,
            "UniqueBack": false,
            "Type": 0
          }
        },
        "LuaScript": "",
        "LuaScriptState": "",
        "XmlUI": ""
      }
    ]
  }
},
"ChildObjects": [
  {
    "GUID": "bfb4a7",
    "Name": "Custom_Model",
    "Transform": {
      "posX": 1.9836092,
      "posY": 3.21452641,
      "posZ": -1.94255877,
      "rotX": 359.992676,
      "rotY": 359.895325,
      "rotZ": 0.003873905,
      "scaleX": 1.0,
      "scaleY": 1.0,
      "scaleZ": 0.9999999
    },
    "Nickname": "",
    "Description": "",
    "GMNotes": "",
    "AltLookAngle": {
      "x": 0.0,
      "y": 0.0,
      "z": 0.0
    },
    "ColorDiffuse": {
      "r": 0.6627451,
      "g": 0.6627451,
      "b": 0.6627451
    },
    "LayoutGroupSortIndex": 0,
    "Value": 0,
    "Locked": true,
    "Grid": true,
    "Snap": true,
    "IgnoreFoW": false,
    "MeasureMovement": false,
    "DragSelectable": true,
    "Autoraise": true,
    "Sticky": true,
    "Tooltip": true,
    "GridProjection": false,
    "HideWhenFaceDown": false,
    "Hands": false,
    "CustomMesh": {
      "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2050876934859026362/8EDA2E480DFEC1B0B885AB4633074F004E96648D/",
      "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794554175/892D44213E132546A15A01E898CEE59F66ACFE5D/",
      "NormalURL": "",
      "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/2050876934859026362/8EDA2E480DFEC1B0B885AB4633074F004E96648D/",
      "Convex": false,
      "MaterialIndex": 1,
      "TypeIndex": 0,
      "CastShadows": true
    },
    "LuaScript": "",
    "LuaScriptState": "",
    "XmlUI": "",
    "PhysicsMaterial": {
      "StaticFriction": 1.0,
      "DynamicFriction": 0.7,
      "Bounciness": 0.0,
      "FrictionCombine": 0,
      "BounceCombine": 0
    },
    "Rigidbody": {
      "Mass": 1.0,
      "Drag": 0.1,
      "AngularDrag": 0.1,
      "UseGravity": true
    },
    "ChildObjects": [
      {
        "GUID": "3f2d4d",
        "Name": "CardCustom",
        "Transform": {
          "posX": -0.9610308,
          "posY": 0.0725631043,
          "posZ": 0.6029997,
          "rotX": -2.20303335E-07,
          "rotY": 90.08806,
          "rotZ": -2.3364754E-07,
          "scaleX": 0.9084988,
          "scaleY": 0.065,
          "scaleZ": 0.635936439
        },
        "Nickname": "",
        "Description": "",
        "GMNotes": "",
        "AltLookAngle": {
          "x": 0.0,
          "y": 0.0,
          "z": 0.0
        },
        "ColorDiffuse": {
          "r": 0.713235259,
          "g": 0.713235259,
          "b": 0.713235259
        },
        "LayoutGroupSortIndex": 0,
        "Value": 0,
        "Locked": false,
        "Grid": true,
        "Snap": true,
        "IgnoreFoW": false,
        "MeasureMovement": false,
        "DragSelectable": true,
        "Autoraise": true,
        "Sticky": true,
        "Tooltip": true,
        "GridProjection": false,
        "HideWhenFaceDown": true,
        "Hands": true,
        "CardID": 400,
        "SidewaysCard": false,
        "CustomDeck": {
          "4": {
            "FaceURL": "https://steamusercontent-a.akamaihd.net/ugc/2050876934859079198/D1FA4B09D02FEBA5BB9755137AAD285462824318/",
            "BackURL": "https://steamusercontent-a.akamaihd.net/ugc/2050876934859079198/D1FA4B09D02FEBA5BB9755137AAD285462824318/",
            "NumWidth": 1,
            "NumHeight": 1,
            "BackIsHidden": true,
            "UniqueBack": false,
            "Type": 1
          }
        },
        "LuaScript": "",
        "LuaScriptState": "",
        "XmlUI": ""
      }
    ]
  },
  {
    "GUID": "5bbf29",
    "Name": "CardCustom",
    "Transform": {
      "posX": 2.14234233,
      "posY": 0.0,
      "posZ": -5.122262,
      "rotX": -8.797401E-08,
      "rotY": 180.0,
      "rotZ": -3.280339E-07,
      "scaleX": 2.79291272,
      "scaleY": 0.065,
      "scaleZ": 3.91000056
    },
    "Nickname": "",
    "Description": "",
    "GMNotes": "",
    "AltLookAngle": {
      "x": 0.0,
      "y": 0.0,
      "z": 0.0
    },
    "ColorDiffuse": {
      "r": 0.713235259,
      "g": 0.713235259,
      "b": 0.713235259
    },
    "LayoutGroupSortIndex": 0,
    "Value": 0,
    "Locked": true,
    "Grid": true,
    "Snap": true,
    "IgnoreFoW": false,
    "MeasureMovement": false,
    "DragSelectable": true,
    "Autoraise": true,
    "Sticky": true,
    "Tooltip": true,
    "GridProjection": false,
    "HideWhenFaceDown": true,
    "Hands": true,
    "CardID": 30400,
    "SidewaysCard": false,
    "CustomDeck": {
      "304": {
        "FaceURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794548479/1334E2934F85878167A301C71EBDE0DD7AB39D9C/",
        "BackURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794548479/1334E2934F85878167A301C71EBDE0DD7AB39D9C/",
        "NumWidth": 1,
        "NumHeight": 1,
        "BackIsHidden": true,
        "UniqueBack": false,
        "Type": 0
      }
    },
    "LuaScript": "",
    "LuaScriptState": "",
    "XmlUI": ""
  }
]
}]],
[[{
"GUID": "209460",
"Name": "Custom_Model",
"Transform": {
  "posX": 6.46,
  "posY": 0.97,
  "posZ": 8.02,
  "rotX": 0.0,
  "rotY": 345.5,
  "rotZ": 0.0,
  "scaleX": 1.0,
  "scaleY": 1.0,
  "scaleZ": 1.0
},
"Nickname": "THREE STOREY RUIN",
"Description": "",
"GMNotes": "",
"AltLookAngle": {
  "x": 0.0,
  "y": 0.0,
  "z": 0.0
},
"ColorDiffuse": {
  "r": 1.0,
  "g": 1.0,
  "b": 1.0
},
"LayoutGroupSortIndex": 0,
"Value": 0,
"Locked": true,
"Grid": true,
"Snap": true,
"IgnoreFoW": false,
"MeasureMovement": false,
"DragSelectable": true,
"Autoraise": true,
"Sticky": true,
"Tooltip": true,
"GridProjection": false,
"HideWhenFaceDown": false,
"Hands": false,
"CustomMesh": {
  "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794615637/3243BEE6343D5C13E960186B86AC320A41183927/",
  "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794552248/6D9B9FB570E97EA80128D58CD4A0EB295F654306/",
  "NormalURL": "",
  "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912201570/3CFC9BAA671D43615F4A56A37B443F1819EA1672/",
  "Convex": true,
  "MaterialIndex": 1,
  "TypeIndex": 0,
  "CastShadows": true
},
"LuaScript": "",
"LuaScriptState": "",
"XmlUI": "",
"States": {
  "2": {
    "GUID": "5c2d0f",
    "Name": "Custom_Model",
    "Transform": {
      "posX": 15.0,
      "posY": 0.97,
      "posZ": 15.0,
      "rotX": 0.0,
      "rotY": 90.0,
      "rotZ": 0.0,
      "scaleX": 1.0,
      "scaleY": 1.0,
      "scaleZ": 1.0
    },
    "Nickname": "THREE STOREY RUIN",
    "Description": "",
    "GMNotes": "",
    "AltLookAngle": {
      "x": 0.0,
      "y": 0.0,
      "z": 0.0
    },
    "ColorDiffuse": {
      "r": 1.0,
      "g": 1.0,
      "b": 1.0
    },
    "LayoutGroupSortIndex": 0,
    "Value": 0,
    "Locked": true,
    "Grid": true,
    "Snap": true,
    "IgnoreFoW": false,
    "MeasureMovement": false,
    "DragSelectable": true,
    "Autoraise": true,
    "Sticky": true,
    "Tooltip": true,
    "GridProjection": false,
    "HideWhenFaceDown": false,
    "Hands": false,
    "CustomMesh": {
      "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794615637/3243BEE6343D5C13E960186B86AC320A41183927/",
      "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794552248/6D9B9FB570E97EA80128D58CD4A0EB295F654306/",
      "NormalURL": "",
      "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912201570/3CFC9BAA671D43615F4A56A37B443F1819EA1672/",
      "Convex": true,
      "MaterialIndex": 1,
      "TypeIndex": 0,
      "CastShadows": true
    },
    "LuaScript": "",
    "LuaScriptState": "",
    "XmlUI": "",
    "ChildObjects": [
      {
        "GUID": "a55a24",
        "Name": "Custom_Model",
        "Transform": {
          "posX": -0.009057048,
          "posY": 2.94,
          "posZ": 0.0138750086,
          "rotX": 359.983917,
          "rotY": 359.972229,
          "rotZ": -0.001307647,
          "scaleX": 0.9999999,
          "scaleY": 1.0,
          "scaleZ": 1.0
        },
        "Nickname": "THREE STOREY RUIN",
        "Description": "TERRAIN CATEGORY: [c6c930]Area terrain[-]\r\nTERRAIN TRAITS: [1F87FF]Scaleable, Breachable, Light cover, Defensible , Obscuring[-]",
        "GMNotes": "",
        "AltLookAngle": {
          "x": 0.0,
          "y": 0.0,
          "z": 0.0
        },
        "ColorDiffuse": {
          "r": 0.6602787,
          "g": 0.6602787,
          "b": 0.6602787
        },
        "LayoutGroupSortIndex": 0,
        "Value": 0,
        "Locked": true,
        "Grid": true,
        "Snap": true,
        "IgnoreFoW": false,
        "MeasureMovement": false,
        "DragSelectable": true,
        "Autoraise": true,
        "Sticky": true,
        "Tooltip": true,
        "GridProjection": false,
        "HideWhenFaceDown": false,
        "Hands": false,
        "CustomMesh": {
          "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912108869/1AFAF16694B0CBEF6CD222334144FCAA7581FBDA/",
          "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794554175/892D44213E132546A15A01E898CEE59F66ACFE5D/",
          "NormalURL": "",
          "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912108869/1AFAF16694B0CBEF6CD222334144FCAA7581FBDA/",
          "Convex": false,
          "MaterialIndex": 1,
          "TypeIndex": 0,
          "CastShadows": true
        },
        "LuaScript": "",
        "LuaScriptState": "",
        "XmlUI": ""
      },
      {
        "GUID": "1a6bd4",
        "Name": "CardCustom",
        "Transform": {
          "posX": -2.14004683,
          "posY": -6.198883E-06,
          "posZ": -5.049985,
          "rotX": -4.020952E-05,
          "rotY": 0.000525924552,
          "rotZ": 6.76622E-05,
          "scaleX": 2.79291344,
          "scaleY": 0.065,
          "scaleZ": 3.91000152
        },
        "Nickname": "",
        "Description": "",
        "GMNotes": "",
        "AltLookAngle": {
          "x": 0.0,
          "y": 0.0,
          "z": 0.0
        },
        "ColorDiffuse": {
          "r": 0.713235259,
          "g": 0.713235259,
          "b": 0.713235259
        },
        "LayoutGroupSortIndex": 0,
        "Value": 0,
        "Locked": true,
        "Grid": true,
        "Snap": true,
        "IgnoreFoW": false,
        "MeasureMovement": false,
        "DragSelectable": true,
        "Autoraise": true,
        "Sticky": true,
        "Tooltip": true,
        "GridProjection": false,
        "HideWhenFaceDown": true,
        "Hands": true,
        "CardID": 30400,
        "SidewaysCard": false,
        "CustomDeck": {
          "304": {
            "FaceURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794548479/1334E2934F85878167A301C71EBDE0DD7AB39D9C/",
            "BackURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794548479/1334E2934F85878167A301C71EBDE0DD7AB39D9C/",
            "NumWidth": 1,
            "NumHeight": 1,
            "BackIsHidden": true,
            "UniqueBack": false,
            "Type": 0
          }
        },
        "LuaScript": "",
        "LuaScriptState": "",
        "XmlUI": ""
      }
    ]
  },
  "3": {
    "GUID": "c62e13",
    "Name": "Custom_Model",
    "Transform": {
      "posX": 15.0,
      "posY": 0.97,
      "posZ": 15.0,
      "rotX": 0.0,
      "rotY": 90.0,
      "rotZ": 0.0,
      "scaleX": 1.0,
      "scaleY": 1.0,
      "scaleZ": 1.0
    },
    "Nickname": "THREE STOREY RUIN",
    "Description": "",
    "GMNotes": "",
    "AltLookAngle": {
      "x": 0.0,
      "y": 0.0,
      "z": 0.0
    },
    "ColorDiffuse": {
      "r": 1.0,
      "g": 1.0,
      "b": 1.0
    },
    "LayoutGroupSortIndex": 0,
    "Value": 0,
    "Locked": true,
    "Grid": true,
    "Snap": true,
    "IgnoreFoW": false,
    "MeasureMovement": false,
    "DragSelectable": true,
    "Autoraise": true,
    "Sticky": true,
    "Tooltip": true,
    "GridProjection": false,
    "HideWhenFaceDown": false,
    "Hands": false,
    "CustomMesh": {
      "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794615637/3243BEE6343D5C13E960186B86AC320A41183927/",
      "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794552248/6D9B9FB570E97EA80128D58CD4A0EB295F654306/",
      "NormalURL": "",
      "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912201570/3CFC9BAA671D43615F4A56A37B443F1819EA1672/",
      "Convex": true,
      "MaterialIndex": 1,
      "TypeIndex": 0,
      "CastShadows": true
    },
    "LuaScript": "",
    "LuaScriptState": "",
    "XmlUI": "",
    "ChildObjects": [
      {
        "GUID": "6452c2",
        "Name": "CardCustom",
        "Transform": {
          "posX": -2.136197,
          "posY": -2.58482532E-06,
          "posZ": -5.054414,
          "rotX": 2.19344838E-05,
          "rotY": -0.00102452841,
          "rotZ": 0.000121076075,
          "scaleX": 2.792914,
          "scaleY": 0.065,
          "scaleZ": 3.91000152
        },
        "Nickname": "",
        "Description": "",
        "GMNotes": "",
        "AltLookAngle": {
          "x": 0.0,
          "y": 0.0,
          "z": 0.0
        },
        "ColorDiffuse": {
          "r": 0.713235259,
          "g": 0.713235259,
          "b": 0.713235259
        },
        "LayoutGroupSortIndex": 0,
        "Value": 0,
        "Locked": true,
        "Grid": true,
        "Snap": true,
        "IgnoreFoW": false,
        "MeasureMovement": false,
        "DragSelectable": true,
        "Autoraise": true,
        "Sticky": true,
        "Tooltip": true,
        "GridProjection": false,
        "HideWhenFaceDown": true,
        "Hands": true,
        "CardID": 30400,
        "SidewaysCard": false,
        "CustomDeck": {
          "304": {
            "FaceURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794548479/1334E2934F85878167A301C71EBDE0DD7AB39D9C/",
            "BackURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794548479/1334E2934F85878167A301C71EBDE0DD7AB39D9C/",
            "NumWidth": 1,
            "NumHeight": 1,
            "BackIsHidden": true,
            "UniqueBack": false,
            "Type": 0
          }
        },
        "LuaScript": "",
        "LuaScriptState": "",
        "XmlUI": ""
      }
    ]
  }
},
"ChildObjects": [
  {
    "GUID": "44e827",
    "Name": "Custom_Model",
    "Transform": {
      "posX": -0.009095477,
      "posY": 2.93908525,
      "posZ": 0.0147003159,
      "rotX": 5.70142856E-06,
      "rotY": 359.971069,
      "rotZ": 3.73948278E-05,
      "scaleX": 1.0,
      "scaleY": 1.0,
      "scaleZ": 1.0
    },
    "Nickname": "THREE STOREY RUIN",
    "Description": "TERRAIN CATEGORY: [c6c930]Area terrain[-]\r\nTERRAIN TRAITS: [1F87FF]Scaleable, Breachable, Light cover, Defensible , Obscuring[-]",
    "GMNotes": "",
    "AltLookAngle": {
      "x": 0.0,
      "y": 0.0,
      "z": 0.0
    },
    "ColorDiffuse": {
      "r": 0.6602787,
      "g": 0.6602787,
      "b": 0.6602787
    },
    "LayoutGroupSortIndex": 0,
    "Value": 0,
    "Locked": true,
    "Grid": true,
    "Snap": true,
    "IgnoreFoW": false,
    "MeasureMovement": false,
    "DragSelectable": true,
    "Autoraise": true,
    "Sticky": true,
    "Tooltip": true,
    "GridProjection": false,
    "HideWhenFaceDown": false,
    "Hands": false,
    "CustomMesh": {
      "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912108869/1AFAF16694B0CBEF6CD222334144FCAA7581FBDA/",
      "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794554175/892D44213E132546A15A01E898CEE59F66ACFE5D/",
      "NormalURL": "",
      "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912108869/1AFAF16694B0CBEF6CD222334144FCAA7581FBDA/",
      "Convex": false,
      "MaterialIndex": 3,
      "TypeIndex": 0,
      "CustomShader": {
        "SpecularColor": {
          "r": 1.0,
          "g": 1.0,
          "b": 1.0
        },
        "SpecularIntensity": 0.0,
        "SpecularSharpness": 2.0,
        "FresnelStrength": 0.0
      },
      "CastShadows": true
    },
    "LuaScript": "",
    "LuaScriptState": "",
    "XmlUI": ""
  },
  {
    "GUID": "fe5571",
    "Name": "Custom_Model",
    "Transform": {
      "posX": 0.0031952688,
      "posY": -0.010915041,
      "posZ": -0.00828582,
      "rotX": -1.12302146E-07,
      "rotY": 359.986023,
      "rotZ": 4.90050879E-05,
      "scaleX": 1.00000012,
      "scaleY": 1.0,
      "scaleZ": 1.00000012
    },
    "Nickname": "THREE STOREY RUIN",
    "Description": "TERRAIN CATEGORY: [c6c930]Area terrain[-]\r\nTERRAIN TRAITS: [1F87FF]Scaleable, Breachable, Light cover, Defensible , Obscuring[-]",
    "GMNotes": "",
    "AltLookAngle": {
      "x": 0.0,
      "y": 0.0,
      "z": 0.0
    },
    "ColorDiffuse": {
      "r": 0.6602787,
      "g": 0.6602787,
      "b": 0.6602787
    },
    "LayoutGroupSortIndex": 0,
    "Value": 0,
    "Locked": true,
    "Grid": true,
    "Snap": true,
    "IgnoreFoW": false,
    "MeasureMovement": false,
    "DragSelectable": true,
    "Autoraise": true,
    "Sticky": true,
    "Tooltip": true,
    "GridProjection": false,
    "HideWhenFaceDown": false,
    "Hands": false,
    "CustomMesh": {
      "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938911722433/FB1384DC6E77D19E0DD0DD6B0FDAE370AE82B53C/",
      "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794554175/892D44213E132546A15A01E898CEE59F66ACFE5D/",
      "NormalURL": "",
      "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938911722433/FB1384DC6E77D19E0DD0DD6B0FDAE370AE82B53C/",
      "Convex": false,
      "MaterialIndex": 1,
      "TypeIndex": 0,
      "CastShadows": true
    },
    "LuaScript": "",
    "LuaScriptState": "",
    "XmlUI": ""
  },
  {
    "GUID": "1a6bd4",
    "Name": "CardCustom",
    "Transform": {
      "posX": -2.13999915,
      "posY": 0.0,
      "posZ": -5.05,
      "rotX": 1.0694115E-06,
      "rotY": -3.08322788E-15,
      "rotZ": -3.30379748E-07,
      "scaleX": 2.792913,
      "scaleY": 0.065,
      "scaleZ": 3.910001
    },
    "Nickname": "",
    "Description": "",
    "GMNotes": "",
    "AltLookAngle": {
      "x": 0.0,
      "y": 0.0,
      "z": 0.0
    },
    "ColorDiffuse": {
      "r": 0.713235259,
      "g": 0.713235259,
      "b": 0.713235259
    },
    "LayoutGroupSortIndex": 0,
    "Value": 0,
    "Locked": true,
    "Grid": true,
    "Snap": true,
    "IgnoreFoW": false,
    "MeasureMovement": false,
    "DragSelectable": true,
    "Autoraise": true,
    "Sticky": true,
    "Tooltip": true,
    "GridProjection": false,
    "HideWhenFaceDown": true,
    "Hands": true,
    "CardID": 30400,
    "SidewaysCard": false,
    "CustomDeck": {
      "304": {
        "FaceURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794548479/1334E2934F85878167A301C71EBDE0DD7AB39D9C/",
        "BackURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794548479/1334E2934F85878167A301C71EBDE0DD7AB39D9C/",
        "NumWidth": 1,
        "NumHeight": 1,
        "BackIsHidden": true,
        "UniqueBack": false,
        "Type": 0
      }
    },
    "LuaScript": "",
    "LuaScriptState": "",
    "XmlUI": ""
  }
]
}]],
[[{
"GUID": "96c10c",
"Name": "Custom_Model",
"Transform": {
  "posX": 6.52,
  "posY": 3.4897964,
  "posZ": -6.24,
  "rotX": -0.0002602451,
  "rotY": 180.0,
  "rotZ": -0.000154657711,
  "scaleX": 0.44,
  "scaleY": 0.440000743,
  "scaleZ": 0.52
},
"Nickname": "Container",
"Description": "",
"GMNotes": "",
"AltLookAngle": {
  "x": 0.0,
  "y": 0.0,
  "z": 0.0
},
"ColorDiffuse": {
  "r": 0.203920752,
  "g": 0.18431291,
  "b": 0.180391341
},
"LayoutGroupSortIndex": 0,
"Value": 0,
"Locked": true,
"Grid": true,
"Snap": true,
"IgnoreFoW": false,
"MeasureMovement": false,
"DragSelectable": true,
"Autoraise": true,
"Sticky": true,
"Tooltip": true,
"GridProjection": false,
"HideWhenFaceDown": false,
"Hands": false,
"CustomMesh": {
  "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1018320153794846738/DF21B27B996BAF4470C34C55391A5F586443F54D/",
  "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1018320153794846900/2AD6701546E10D9B7C6328FDEAA057765BB42FAC/",
  "NormalURL": "https://steamusercontent-a.akamaihd.net/ugc/1018320153794847254/DBB28E40ADDFF4719B17E1CEDDE73850398E1F89/",
  "ColliderURL": "",
  "Convex": true,
  "MaterialIndex": 3,
  "TypeIndex": 0,
  "CastShadows": true
},
"LuaScript": "",
"LuaScriptState": "",
"XmlUI": "",
"ChildObjects": [
  {
    "GUID": "322faa",
    "Name": "Custom_Model",
    "Transform": {
      "posX": -3.350733E-05,
      "posY": -5.703194,
      "posZ": -2.281413E-05,
      "rotX": 0.00025679465,
      "rotY": 0.0035871095,
      "rotZ": 0.000154398775,
      "scaleX": 1.00081849,
      "scaleY": 1.0,
      "scaleZ": 1.00081849
    },
    "Nickname": "Armoured Container | [CC99CC]Obstacle[-]                           [00BFFF]Light Cover, Scaleable, Exposed Position[-]                    2.5\" height/width, 5\" length",
    "Description": "",
    "GMNotes": "",
    "AltLookAngle": {
      "x": 0.0,
      "y": 0.0,
      "z": 0.0
    },
    "ColorDiffuse": {
      "r": 0.203921527,
      "g": 0.184313685,
      "b": 0.180392116
    },
    "LayoutGroupSortIndex": 0,
    "Value": 0,
    "Locked": true,
    "Grid": true,
    "Snap": true,
    "IgnoreFoW": false,
    "MeasureMovement": false,
    "DragSelectable": true,
    "Autoraise": true,
    "Sticky": true,
    "Tooltip": true,
    "GridProjection": false,
    "HideWhenFaceDown": false,
    "Hands": false,
    "CustomMesh": {
      "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1018320153794846738/DF21B27B996BAF4470C34C55391A5F586443F54D/",
      "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1018320153794846900/2AD6701546E10D9B7C6328FDEAA057765BB42FAC/",
      "NormalURL": "https://steamusercontent-a.akamaihd.net/ugc/1018320153794847254/DBB28E40ADDFF4719B17E1CEDDE73850398E1F89/",
      "ColliderURL": "",
      "Convex": true,
      "MaterialIndex": 3,
      "TypeIndex": 0,
      "CastShadows": true
    },
    "LuaScript": "",
    "LuaScriptState": "",
    "XmlUI": ""
  }
]
}]],
[[{
"GUID": "ac2528",
"Name": "Custom_Model",
"Transform": {
  "posX": 19.8520126,
  "posY": 0.97,
  "posZ": -10.4793749,
  "rotX": 0.0,
  "rotY": 43.0,
  "rotZ": 0.0,
  "scaleX": 1.0,
  "scaleY": 1.0,
  "scaleZ": 1.0
},
"Nickname": "TWO STOREY RUIN",
"Description": "",
"GMNotes": "",
"AltLookAngle": {
  "x": 0.0,
  "y": 0.0,
  "z": 0.0
},
"ColorDiffuse": {
  "r": 1.0,
  "g": 1.0,
  "b": 1.0
},
"LayoutGroupSortIndex": 0,
"Value": 0,
"Locked": true,
"Grid": true,
"Snap": true,
"IgnoreFoW": false,
"MeasureMovement": false,
"DragSelectable": true,
"Autoraise": true,
"Sticky": true,
"Tooltip": true,
"GridProjection": false,
"HideWhenFaceDown": false,
"Hands": false,
"CustomMesh": {
  "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700191697866339/512A215790C3FB9D46B89208BDB234D98D8C3350/",
  "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794552248/6D9B9FB570E97EA80128D58CD4A0EB295F654306/",
  "NormalURL": "",
  "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912201570/3CFC9BAA671D43615F4A56A37B443F1819EA1672/",
  "Convex": true,
  "MaterialIndex": 1,
  "TypeIndex": 0,
  "CastShadows": true
},
"LuaScript": "\nBCBtype = \"terrain\"\n",
"LuaScriptState": "",
"XmlUI": "",
"States": {
  "2": {
    "GUID": "3b1728",
    "Name": "Custom_Model",
    "Transform": {
      "posX": 19.8520126,
      "posY": 0.97,
      "posZ": -10.4793749,
      "rotX": 0.0,
      "rotY": 43.0,
      "rotZ": 0.0,
      "scaleX": 1.0,
      "scaleY": 1.0,
      "scaleZ": 1.0
    },
    "Nickname": "TWO STOREY RUIN",
    "Description": "",
    "GMNotes": "",
    "AltLookAngle": {
      "x": 0.0,
      "y": 0.0,
      "z": 0.0
    },
    "ColorDiffuse": {
      "r": 1.0,
      "g": 1.0,
      "b": 1.0
    },
    "LayoutGroupSortIndex": 0,
    "Value": 0,
    "Locked": true,
    "Grid": true,
    "Snap": true,
    "IgnoreFoW": false,
    "MeasureMovement": false,
    "DragSelectable": true,
    "Autoraise": true,
    "Sticky": true,
    "Tooltip": true,
    "GridProjection": false,
    "HideWhenFaceDown": false,
    "Hands": false,
    "CustomMesh": {
      "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700191697866339/512A215790C3FB9D46B89208BDB234D98D8C3350/",
      "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794552248/6D9B9FB570E97EA80128D58CD4A0EB295F654306/",
      "NormalURL": "",
      "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912201570/3CFC9BAA671D43615F4A56A37B443F1819EA1672/",
      "Convex": true,
      "MaterialIndex": 1,
      "TypeIndex": 0,
      "CastShadows": true
    },
    "LuaScript": "",
    "LuaScriptState": "",
    "XmlUI": "",
    "ChildObjects": [
      {
        "GUID": "6452c2",
        "Name": "CardCustom",
        "Transform": {
          "posX": 2.13760066,
          "posY": 0.0,
          "posZ": -5.12226,
          "rotX": -0.000240696449,
          "rotY": 179.999969,
          "rotZ": 0.000153086949,
          "scaleX": 2.7929132,
          "scaleY": 0.065,
          "scaleZ": 3.91000128
        },
        "Nickname": "",
        "Description": "",
        "GMNotes": "",
        "AltLookAngle": {
          "x": 0.0,
          "y": 0.0,
          "z": 0.0
        },
        "ColorDiffuse": {
          "r": 0.713235259,
          "g": 0.713235259,
          "b": 0.713235259
        },
        "LayoutGroupSortIndex": 0,
        "Value": 0,
        "Locked": true,
        "Grid": true,
        "Snap": true,
        "IgnoreFoW": false,
        "MeasureMovement": false,
        "DragSelectable": true,
        "Autoraise": true,
        "Sticky": true,
        "Tooltip": true,
        "GridProjection": false,
        "HideWhenFaceDown": true,
        "Hands": true,
        "CardID": 30400,
        "SidewaysCard": false,
        "CustomDeck": {
          "304": {
            "FaceURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794548479/1334E2934F85878167A301C71EBDE0DD7AB39D9C/",
            "BackURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794548479/1334E2934F85878167A301C71EBDE0DD7AB39D9C/",
            "NumWidth": 1,
            "NumHeight": 1,
            "BackIsHidden": true,
            "UniqueBack": false,
            "Type": 0
          }
        },
        "LuaScript": "",
        "LuaScriptState": "",
        "XmlUI": ""
      }
    ]
  }
},
"ChildObjects": [
  {
    "GUID": "bfb4a7",
    "Name": "Custom_Model",
    "Transform": {
      "posX": 1.9836092,
      "posY": 3.21452641,
      "posZ": -1.94255877,
      "rotX": 359.992676,
      "rotY": 359.895325,
      "rotZ": 0.003873905,
      "scaleX": 1.0,
      "scaleY": 1.0,
      "scaleZ": 0.9999999
    },
    "Nickname": "",
    "Description": "",
    "GMNotes": "",
    "AltLookAngle": {
      "x": 0.0,
      "y": 0.0,
      "z": 0.0
    },
    "ColorDiffuse": {
      "r": 0.6627451,
      "g": 0.6627451,
      "b": 0.6627451
    },
    "LayoutGroupSortIndex": 0,
    "Value": 0,
    "Locked": true,
    "Grid": true,
    "Snap": true,
    "IgnoreFoW": false,
    "MeasureMovement": false,
    "DragSelectable": true,
    "Autoraise": true,
    "Sticky": true,
    "Tooltip": true,
    "GridProjection": false,
    "HideWhenFaceDown": false,
    "Hands": false,
    "CustomMesh": {
      "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2050876934859026362/8EDA2E480DFEC1B0B885AB4633074F004E96648D/",
      "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794554175/892D44213E132546A15A01E898CEE59F66ACFE5D/",
      "NormalURL": "",
      "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/2050876934859026362/8EDA2E480DFEC1B0B885AB4633074F004E96648D/",
      "Convex": false,
      "MaterialIndex": 1,
      "TypeIndex": 0,
      "CastShadows": true
    },
    "LuaScript": "",
    "LuaScriptState": "",
    "XmlUI": "",
    "PhysicsMaterial": {
      "StaticFriction": 1.0,
      "DynamicFriction": 0.7,
      "Bounciness": 0.0,
      "FrictionCombine": 0,
      "BounceCombine": 0
    },
    "Rigidbody": {
      "Mass": 1.0,
      "Drag": 0.1,
      "AngularDrag": 0.1,
      "UseGravity": true
    },
    "ChildObjects": [
      {
        "GUID": "3f2d4d",
        "Name": "CardCustom",
        "Transform": {
          "posX": -0.9610308,
          "posY": 0.0725631043,
          "posZ": 0.6029997,
          "rotX": -2.20303335E-07,
          "rotY": 90.08806,
          "rotZ": -2.3364754E-07,
          "scaleX": 0.9084988,
          "scaleY": 0.065,
          "scaleZ": 0.635936439
        },
        "Nickname": "",
        "Description": "",
        "GMNotes": "",
        "AltLookAngle": {
          "x": 0.0,
          "y": 0.0,
          "z": 0.0
        },
        "ColorDiffuse": {
          "r": 0.713235259,
          "g": 0.713235259,
          "b": 0.713235259
        },
        "LayoutGroupSortIndex": 0,
        "Value": 0,
        "Locked": false,
        "Grid": true,
        "Snap": true,
        "IgnoreFoW": false,
        "MeasureMovement": false,
        "DragSelectable": true,
        "Autoraise": true,
        "Sticky": true,
        "Tooltip": true,
        "GridProjection": false,
        "HideWhenFaceDown": true,
        "Hands": true,
        "CardID": 400,
        "SidewaysCard": false,
        "CustomDeck": {
          "4": {
            "FaceURL": "https://steamusercontent-a.akamaihd.net/ugc/2050876934859079198/D1FA4B09D02FEBA5BB9755137AAD285462824318/",
            "BackURL": "https://steamusercontent-a.akamaihd.net/ugc/2050876934859079198/D1FA4B09D02FEBA5BB9755137AAD285462824318/",
            "NumWidth": 1,
            "NumHeight": 1,
            "BackIsHidden": true,
            "UniqueBack": false,
            "Type": 1
          }
        },
        "LuaScript": "",
        "LuaScriptState": "",
        "XmlUI": ""
      }
    ]
  },
  {
    "GUID": "5bbf29",
    "Name": "CardCustom",
    "Transform": {
      "posX": 2.14234233,
      "posY": 0.0,
      "posZ": -5.122262,
      "rotX": -8.797401E-08,
      "rotY": 180.0,
      "rotZ": -3.280339E-07,
      "scaleX": 2.79291272,
      "scaleY": 0.065,
      "scaleZ": 3.91000056
    },
    "Nickname": "",
    "Description": "",
    "GMNotes": "",
    "AltLookAngle": {
      "x": 0.0,
      "y": 0.0,
      "z": 0.0
    },
    "ColorDiffuse": {
      "r": 0.713235259,
      "g": 0.713235259,
      "b": 0.713235259
    },
    "LayoutGroupSortIndex": 0,
    "Value": 0,
    "Locked": true,
    "Grid": true,
    "Snap": true,
    "IgnoreFoW": false,
    "MeasureMovement": false,
    "DragSelectable": true,
    "Autoraise": true,
    "Sticky": true,
    "Tooltip": true,
    "GridProjection": false,
    "HideWhenFaceDown": true,
    "Hands": true,
    "CardID": 30400,
    "SidewaysCard": false,
    "CustomDeck": {
      "304": {
        "FaceURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794548479/1334E2934F85878167A301C71EBDE0DD7AB39D9C/",
        "BackURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794548479/1334E2934F85878167A301C71EBDE0DD7AB39D9C/",
        "NumWidth": 1,
        "NumHeight": 1,
        "BackIsHidden": true,
        "UniqueBack": false,
        "Type": 0
      }
    },
    "LuaScript": "",
    "LuaScriptState": "",
    "XmlUI": ""
  }
]
}]],
[[{
"GUID": "f5e7ed",
"Name": "Custom_Model",
"Transform": {
  "posX": 19.84,
  "posY": 0.97,
  "posZ": 10.53,
  "rotX": 0.0,
  "rotY": 137.0,
  "rotZ": 0.0,
  "scaleX": 1.0,
  "scaleY": 1.0,
  "scaleZ": 1.0
},
"Nickname": "THREE STOREY RUIN",
"Description": "",
"GMNotes": "",
"AltLookAngle": {
  "x": 0.0,
  "y": 0.0,
  "z": 0.0
},
"ColorDiffuse": {
  "r": 1.0,
  "g": 1.0,
  "b": 1.0
},
"LayoutGroupSortIndex": 0,
"Value": 0,
"Locked": true,
"Grid": true,
"Snap": true,
"IgnoreFoW": false,
"MeasureMovement": false,
"DragSelectable": true,
"Autoraise": true,
"Sticky": true,
"Tooltip": true,
"GridProjection": false,
"HideWhenFaceDown": false,
"Hands": false,
"CustomMesh": {
  "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794615637/3243BEE6343D5C13E960186B86AC320A41183927/",
  "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794552248/6D9B9FB570E97EA80128D58CD4A0EB295F654306/",
  "NormalURL": "",
  "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912201570/3CFC9BAA671D43615F4A56A37B443F1819EA1672/",
  "Convex": true,
  "MaterialIndex": 1,
  "TypeIndex": 0,
  "CastShadows": true
},
"LuaScript": "",
"LuaScriptState": "",
"XmlUI": "",
"States": {
  "3": {
    "GUID": "c62e13",
    "Name": "Custom_Model",
    "Transform": {
      "posX": 15.0,
      "posY": 0.97,
      "posZ": 15.0,
      "rotX": 0.0,
      "rotY": 90.0,
      "rotZ": 0.0,
      "scaleX": 1.0,
      "scaleY": 1.0,
      "scaleZ": 1.0
    },
    "Nickname": "THREE STOREY RUIN",
    "Description": "",
    "GMNotes": "",
    "AltLookAngle": {
      "x": 0.0,
      "y": 0.0,
      "z": 0.0
    },
    "ColorDiffuse": {
      "r": 1.0,
      "g": 1.0,
      "b": 1.0
    },
    "LayoutGroupSortIndex": 0,
    "Value": 0,
    "Locked": true,
    "Grid": true,
    "Snap": true,
    "IgnoreFoW": false,
    "MeasureMovement": false,
    "DragSelectable": true,
    "Autoraise": true,
    "Sticky": true,
    "Tooltip": true,
    "GridProjection": false,
    "HideWhenFaceDown": false,
    "Hands": false,
    "CustomMesh": {
      "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794615637/3243BEE6343D5C13E960186B86AC320A41183927/",
      "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794552248/6D9B9FB570E97EA80128D58CD4A0EB295F654306/",
      "NormalURL": "",
      "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912201570/3CFC9BAA671D43615F4A56A37B443F1819EA1672/",
      "Convex": true,
      "MaterialIndex": 1,
      "TypeIndex": 0,
      "CastShadows": true
    },
    "LuaScript": "",
    "LuaScriptState": "",
    "XmlUI": "",
    "ChildObjects": [
      {
        "GUID": "6452c2",
        "Name": "CardCustom",
        "Transform": {
          "posX": -2.136197,
          "posY": -2.58482532E-06,
          "posZ": -5.054414,
          "rotX": 2.19344838E-05,
          "rotY": -0.00102452841,
          "rotZ": 0.000121076075,
          "scaleX": 2.792914,
          "scaleY": 0.065,
          "scaleZ": 3.91000152
        },
        "Nickname": "",
        "Description": "",
        "GMNotes": "",
        "AltLookAngle": {
          "x": 0.0,
          "y": 0.0,
          "z": 0.0
        },
        "ColorDiffuse": {
          "r": 0.713235259,
          "g": 0.713235259,
          "b": 0.713235259
        },
        "LayoutGroupSortIndex": 0,
        "Value": 0,
        "Locked": true,
        "Grid": true,
        "Snap": true,
        "IgnoreFoW": false,
        "MeasureMovement": false,
        "DragSelectable": true,
        "Autoraise": true,
        "Sticky": true,
        "Tooltip": true,
        "GridProjection": false,
        "HideWhenFaceDown": true,
        "Hands": true,
        "CardID": 30400,
        "SidewaysCard": false,
        "CustomDeck": {
          "304": {
            "FaceURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794548479/1334E2934F85878167A301C71EBDE0DD7AB39D9C/",
            "BackURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794548479/1334E2934F85878167A301C71EBDE0DD7AB39D9C/",
            "NumWidth": 1,
            "NumHeight": 1,
            "BackIsHidden": true,
            "UniqueBack": false,
            "Type": 0
          }
        },
        "LuaScript": "",
        "LuaScriptState": "",
        "XmlUI": ""
      }
    ]
  },
  "2": {
    "GUID": "5c2d0f",
    "Name": "Custom_Model",
    "Transform": {
      "posX": 15.0,
      "posY": 0.97,
      "posZ": 15.0,
      "rotX": 0.0,
      "rotY": 90.0,
      "rotZ": 0.0,
      "scaleX": 1.0,
      "scaleY": 1.0,
      "scaleZ": 1.0
    },
    "Nickname": "THREE STOREY RUIN",
    "Description": "",
    "GMNotes": "",
    "AltLookAngle": {
      "x": 0.0,
      "y": 0.0,
      "z": 0.0
    },
    "ColorDiffuse": {
      "r": 1.0,
      "g": 1.0,
      "b": 1.0
    },
    "LayoutGroupSortIndex": 0,
    "Value": 0,
    "Locked": true,
    "Grid": true,
    "Snap": true,
    "IgnoreFoW": false,
    "MeasureMovement": false,
    "DragSelectable": true,
    "Autoraise": true,
    "Sticky": true,
    "Tooltip": true,
    "GridProjection": false,
    "HideWhenFaceDown": false,
    "Hands": false,
    "CustomMesh": {
      "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794615637/3243BEE6343D5C13E960186B86AC320A41183927/",
      "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794552248/6D9B9FB570E97EA80128D58CD4A0EB295F654306/",
      "NormalURL": "",
      "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912201570/3CFC9BAA671D43615F4A56A37B443F1819EA1672/",
      "Convex": true,
      "MaterialIndex": 1,
      "TypeIndex": 0,
      "CastShadows": true
    },
    "LuaScript": "",
    "LuaScriptState": "",
    "XmlUI": "",
    "ChildObjects": [
      {
        "GUID": "a55a24",
        "Name": "Custom_Model",
        "Transform": {
          "posX": -0.009057048,
          "posY": 2.94,
          "posZ": 0.0138750086,
          "rotX": 359.983917,
          "rotY": 359.972229,
          "rotZ": -0.001307647,
          "scaleX": 0.9999999,
          "scaleY": 1.0,
          "scaleZ": 1.0
        },
        "Nickname": "THREE STOREY RUIN",
        "Description": "TERRAIN CATEGORY: [c6c930]Area terrain[-]\r\nTERRAIN TRAITS: [1F87FF]Scaleable, Breachable, Light cover, Defensible , Obscuring[-]",
        "GMNotes": "",
        "AltLookAngle": {
          "x": 0.0,
          "y": 0.0,
          "z": 0.0
        },
        "ColorDiffuse": {
          "r": 0.6602787,
          "g": 0.6602787,
          "b": 0.6602787
        },
        "LayoutGroupSortIndex": 0,
        "Value": 0,
        "Locked": true,
        "Grid": true,
        "Snap": true,
        "IgnoreFoW": false,
        "MeasureMovement": false,
        "DragSelectable": true,
        "Autoraise": true,
        "Sticky": true,
        "Tooltip": true,
        "GridProjection": false,
        "HideWhenFaceDown": false,
        "Hands": false,
        "CustomMesh": {
          "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912108869/1AFAF16694B0CBEF6CD222334144FCAA7581FBDA/",
          "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794554175/892D44213E132546A15A01E898CEE59F66ACFE5D/",
          "NormalURL": "",
          "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912108869/1AFAF16694B0CBEF6CD222334144FCAA7581FBDA/",
          "Convex": false,
          "MaterialIndex": 1,
          "TypeIndex": 0,
          "CastShadows": true
        },
        "LuaScript": "",
        "LuaScriptState": "",
        "XmlUI": ""
      },
      {
        "GUID": "1a6bd4",
        "Name": "CardCustom",
        "Transform": {
          "posX": -2.14004683,
          "posY": -6.198883E-06,
          "posZ": -5.049985,
          "rotX": -4.020952E-05,
          "rotY": 0.000525924552,
          "rotZ": 6.76622E-05,
          "scaleX": 2.79291344,
          "scaleY": 0.065,
          "scaleZ": 3.91000152
        },
        "Nickname": "",
        "Description": "",
        "GMNotes": "",
        "AltLookAngle": {
          "x": 0.0,
          "y": 0.0,
          "z": 0.0
        },
        "ColorDiffuse": {
          "r": 0.713235259,
          "g": 0.713235259,
          "b": 0.713235259
        },
        "LayoutGroupSortIndex": 0,
        "Value": 0,
        "Locked": true,
        "Grid": true,
        "Snap": true,
        "IgnoreFoW": false,
        "MeasureMovement": false,
        "DragSelectable": true,
        "Autoraise": true,
        "Sticky": true,
        "Tooltip": true,
        "GridProjection": false,
        "HideWhenFaceDown": true,
        "Hands": true,
        "CardID": 30400,
        "SidewaysCard": false,
        "CustomDeck": {
          "304": {
            "FaceURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794548479/1334E2934F85878167A301C71EBDE0DD7AB39D9C/",
            "BackURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794548479/1334E2934F85878167A301C71EBDE0DD7AB39D9C/",
            "NumWidth": 1,
            "NumHeight": 1,
            "BackIsHidden": true,
            "UniqueBack": false,
            "Type": 0
          }
        },
        "LuaScript": "",
        "LuaScriptState": "",
        "XmlUI": ""
      }
    ]
  }
},
"ChildObjects": [
  {
    "GUID": "44e827",
    "Name": "Custom_Model",
    "Transform": {
      "posX": -0.009095477,
      "posY": 2.93908525,
      "posZ": 0.0147003159,
      "rotX": 5.70142856E-06,
      "rotY": 359.971069,
      "rotZ": 3.73948278E-05,
      "scaleX": 1.0,
      "scaleY": 1.0,
      "scaleZ": 1.0
    },
    "Nickname": "THREE STOREY RUIN",
    "Description": "TERRAIN CATEGORY: [c6c930]Area terrain[-]\r\nTERRAIN TRAITS: [1F87FF]Scaleable, Breachable, Light cover, Defensible , Obscuring[-]",
    "GMNotes": "",
    "AltLookAngle": {
      "x": 0.0,
      "y": 0.0,
      "z": 0.0
    },
    "ColorDiffuse": {
      "r": 0.6602787,
      "g": 0.6602787,
      "b": 0.6602787
    },
    "LayoutGroupSortIndex": 0,
    "Value": 0,
    "Locked": true,
    "Grid": true,
    "Snap": true,
    "IgnoreFoW": false,
    "MeasureMovement": false,
    "DragSelectable": true,
    "Autoraise": true,
    "Sticky": true,
    "Tooltip": true,
    "GridProjection": false,
    "HideWhenFaceDown": false,
    "Hands": false,
    "CustomMesh": {
      "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912108869/1AFAF16694B0CBEF6CD222334144FCAA7581FBDA/",
      "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794554175/892D44213E132546A15A01E898CEE59F66ACFE5D/",
      "NormalURL": "",
      "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912108869/1AFAF16694B0CBEF6CD222334144FCAA7581FBDA/",
      "Convex": false,
      "MaterialIndex": 3,
      "TypeIndex": 0,
      "CustomShader": {
        "SpecularColor": {
          "r": 1.0,
          "g": 1.0,
          "b": 1.0
        },
        "SpecularIntensity": 0.0,
        "SpecularSharpness": 2.0,
        "FresnelStrength": 0.0
      },
      "CastShadows": true
    },
    "LuaScript": "",
    "LuaScriptState": "",
    "XmlUI": ""
  },
  {
    "GUID": "fe5571",
    "Name": "Custom_Model",
    "Transform": {
      "posX": 0.0031952688,
      "posY": -0.010915041,
      "posZ": -0.00828582,
      "rotX": -1.12302146E-07,
      "rotY": 359.986023,
      "rotZ": 4.90050879E-05,
      "scaleX": 1.00000012,
      "scaleY": 1.0,
      "scaleZ": 1.00000012
    },
    "Nickname": "THREE STOREY RUIN",
    "Description": "TERRAIN CATEGORY: [c6c930]Area terrain[-]\r\nTERRAIN TRAITS: [1F87FF]Scaleable, Breachable, Light cover, Defensible , Obscuring[-]",
    "GMNotes": "",
    "AltLookAngle": {
      "x": 0.0,
      "y": 0.0,
      "z": 0.0
    },
    "ColorDiffuse": {
      "r": 0.6602787,
      "g": 0.6602787,
      "b": 0.6602787
    },
    "LayoutGroupSortIndex": 0,
    "Value": 0,
    "Locked": true,
    "Grid": true,
    "Snap": true,
    "IgnoreFoW": false,
    "MeasureMovement": false,
    "DragSelectable": true,
    "Autoraise": true,
    "Sticky": true,
    "Tooltip": true,
    "GridProjection": false,
    "HideWhenFaceDown": false,
    "Hands": false,
    "CustomMesh": {
      "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938911722433/FB1384DC6E77D19E0DD0DD6B0FDAE370AE82B53C/",
      "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794554175/892D44213E132546A15A01E898CEE59F66ACFE5D/",
      "NormalURL": "",
      "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938911722433/FB1384DC6E77D19E0DD0DD6B0FDAE370AE82B53C/",
      "Convex": false,
      "MaterialIndex": 1,
      "TypeIndex": 0,
      "CastShadows": true
    },
    "LuaScript": "",
    "LuaScriptState": "",
    "XmlUI": ""
  },
  {
    "GUID": "1a6bd4",
    "Name": "CardCustom",
    "Transform": {
      "posX": -2.13999915,
      "posY": 0.0,
      "posZ": -5.05,
      "rotX": 1.0694115E-06,
      "rotY": -3.08322788E-15,
      "rotZ": -3.30379748E-07,
      "scaleX": 2.792913,
      "scaleY": 0.065,
      "scaleZ": 3.910001
    },
    "Nickname": "",
    "Description": "",
    "GMNotes": "",
    "AltLookAngle": {
      "x": 0.0,
      "y": 0.0,
      "z": 0.0
    },
    "ColorDiffuse": {
      "r": 0.713235259,
      "g": 0.713235259,
      "b": 0.713235259
    },
    "LayoutGroupSortIndex": 0,
    "Value": 0,
    "Locked": true,
    "Grid": true,
    "Snap": true,
    "IgnoreFoW": false,
    "MeasureMovement": false,
    "DragSelectable": true,
    "Autoraise": true,
    "Sticky": true,
    "Tooltip": true,
    "GridProjection": false,
    "HideWhenFaceDown": true,
    "Hands": true,
    "CardID": 30400,
    "SidewaysCard": false,
    "CustomDeck": {
      "304": {
        "FaceURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794548479/1334E2934F85878167A301C71EBDE0DD7AB39D9C/",
        "BackURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794548479/1334E2934F85878167A301C71EBDE0DD7AB39D9C/",
        "NumWidth": 1,
        "NumHeight": 1,
        "BackIsHidden": true,
        "UniqueBack": false,
        "Type": 0
      }
    },
    "LuaScript": "",
    "LuaScriptState": "",
    "XmlUI": ""
  }
]
}]],
[[{
"GUID": "9073f0",
"Name": "Custom_Model",
"Transform": {
  "posX": 14.83,
  "posY": 0.97,
  "posZ": 1.06,
  "rotX": 0.0,
  "rotY": 317.0,
  "rotZ": 0.0,
  "scaleX": 1.0,
  "scaleY": 1.0,
  "scaleZ": 1.0
},
"Nickname": "TWO STOREY RUIN",
"Description": "",
"GMNotes": "",
"AltLookAngle": {
  "x": 0.0,
  "y": 0.0,
  "z": 0.0
},
"ColorDiffuse": {
  "r": 1.0,
  "g": 1.0,
  "b": 1.0
},
"LayoutGroupSortIndex": 0,
"Value": 0,
"Locked": true,
"Grid": true,
"Snap": true,
"IgnoreFoW": false,
"MeasureMovement": false,
"DragSelectable": true,
"Autoraise": true,
"Sticky": true,
"Tooltip": true,
"GridProjection": false,
"HideWhenFaceDown": false,
"Hands": false,
"CustomMesh": {
  "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700191697866339/512A215790C3FB9D46B89208BDB234D98D8C3350/",
  "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794552248/6D9B9FB570E97EA80128D58CD4A0EB295F654306/",
  "NormalURL": "",
  "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912201570/3CFC9BAA671D43615F4A56A37B443F1819EA1672/",
  "Convex": true,
  "MaterialIndex": 1,
  "TypeIndex": 0,
  "CastShadows": true
},
"LuaScript": "\nBCBtype = \"terrain\"\n",
"LuaScriptState": "",
"XmlUI": "",
"States": {
  "2": {
    "GUID": "edabde",
    "Name": "Custom_Model",
    "Transform": {
      "posX": 18.380331,
      "posY": 0.994030356,
      "posZ": -2.32817388,
      "rotX": 0.0,
      "rotY": 270.0,
      "rotZ": 0.0,
      "scaleX": 1.0,
      "scaleY": 1.0,
      "scaleZ": 1.0
    },
    "Nickname": "TWO STOREY RUIN",
    "Description": "",
    "GMNotes": "",
    "AltLookAngle": {
      "x": 0.0,
      "y": 0.0,
      "z": 0.0
    },
    "ColorDiffuse": {
      "r": 1.0,
      "g": 1.0,
      "b": 1.0
    },
    "LayoutGroupSortIndex": 0,
    "Value": 0,
    "Locked": true,
    "Grid": true,
    "Snap": true,
    "IgnoreFoW": false,
    "MeasureMovement": false,
    "DragSelectable": true,
    "Autoraise": true,
    "Sticky": true,
    "Tooltip": true,
    "GridProjection": false,
    "HideWhenFaceDown": false,
    "Hands": false,
    "CustomMesh": {
      "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700191697866339/512A215790C3FB9D46B89208BDB234D98D8C3350/",
      "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794552248/6D9B9FB570E97EA80128D58CD4A0EB295F654306/",
      "NormalURL": "",
      "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912201570/3CFC9BAA671D43615F4A56A37B443F1819EA1672/",
      "Convex": true,
      "MaterialIndex": 1,
      "TypeIndex": 0,
      "CastShadows": true
    },
    "LuaScript": "",
    "LuaScriptState": "",
    "XmlUI": "",
    "ChildObjects": [
      {
        "GUID": "6452c2",
        "Name": "CardCustom",
        "Transform": {
          "posX": 2.13760066,
          "posY": 0.0,
          "posZ": -5.12226,
          "rotX": -0.000240696449,
          "rotY": 179.999969,
          "rotZ": 0.000153086949,
          "scaleX": 2.7929132,
          "scaleY": 0.065,
          "scaleZ": 3.91000128
        },
        "Nickname": "",
        "Description": "",
        "GMNotes": "",
        "AltLookAngle": {
          "x": 0.0,
          "y": 0.0,
          "z": 0.0
        },
        "ColorDiffuse": {
          "r": 0.713235259,
          "g": 0.713235259,
          "b": 0.713235259
        },
        "LayoutGroupSortIndex": 0,
        "Value": 0,
        "Locked": true,
        "Grid": true,
        "Snap": true,
        "IgnoreFoW": false,
        "MeasureMovement": false,
        "DragSelectable": true,
        "Autoraise": true,
        "Sticky": true,
        "Tooltip": true,
        "GridProjection": false,
        "HideWhenFaceDown": true,
        "Hands": true,
        "CardID": 30400,
        "SidewaysCard": false,
        "CustomDeck": {
          "304": {
            "FaceURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794548479/1334E2934F85878167A301C71EBDE0DD7AB39D9C/",
            "BackURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794548479/1334E2934F85878167A301C71EBDE0DD7AB39D9C/",
            "NumWidth": 1,
            "NumHeight": 1,
            "BackIsHidden": true,
            "UniqueBack": false,
            "Type": 0
          }
        },
        "LuaScript": "",
        "LuaScriptState": "",
        "XmlUI": ""
      }
    ]
  }
},
"ChildObjects": [
  {
    "GUID": "bfb4a7",
    "Name": "Custom_Model",
    "Transform": {
      "posX": 1.9836092,
      "posY": 3.21452641,
      "posZ": -1.94255877,
      "rotX": 359.992676,
      "rotY": 359.895325,
      "rotZ": 0.003873905,
      "scaleX": 1.0,
      "scaleY": 1.0,
      "scaleZ": 0.9999999
    },
    "Nickname": "",
    "Description": "",
    "GMNotes": "",
    "AltLookAngle": {
      "x": 0.0,
      "y": 0.0,
      "z": 0.0
    },
    "ColorDiffuse": {
      "r": 0.6627451,
      "g": 0.6627451,
      "b": 0.6627451
    },
    "LayoutGroupSortIndex": 0,
    "Value": 0,
    "Locked": true,
    "Grid": true,
    "Snap": true,
    "IgnoreFoW": false,
    "MeasureMovement": false,
    "DragSelectable": true,
    "Autoraise": true,
    "Sticky": true,
    "Tooltip": true,
    "GridProjection": false,
    "HideWhenFaceDown": false,
    "Hands": false,
    "CustomMesh": {
      "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2050876934859026362/8EDA2E480DFEC1B0B885AB4633074F004E96648D/",
      "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794554175/892D44213E132546A15A01E898CEE59F66ACFE5D/",
      "NormalURL": "",
      "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/2050876934859026362/8EDA2E480DFEC1B0B885AB4633074F004E96648D/",
      "Convex": false,
      "MaterialIndex": 1,
      "TypeIndex": 0,
      "CastShadows": true
    },
    "LuaScript": "",
    "LuaScriptState": "",
    "XmlUI": "",
    "PhysicsMaterial": {
      "StaticFriction": 1.0,
      "DynamicFriction": 0.7,
      "Bounciness": 0.0,
      "FrictionCombine": 0,
      "BounceCombine": 0
    },
    "Rigidbody": {
      "Mass": 1.0,
      "Drag": 0.1,
      "AngularDrag": 0.1,
      "UseGravity": true
    },
    "ChildObjects": [
      {
        "GUID": "3f2d4d",
        "Name": "CardCustom",
        "Transform": {
          "posX": -0.9610308,
          "posY": 0.0725631043,
          "posZ": 0.6029997,
          "rotX": -2.20303335E-07,
          "rotY": 90.08806,
          "rotZ": -2.3364754E-07,
          "scaleX": 0.9084988,
          "scaleY": 0.065,
          "scaleZ": 0.635936439
        },
        "Nickname": "",
        "Description": "",
        "GMNotes": "",
        "AltLookAngle": {
          "x": 0.0,
          "y": 0.0,
          "z": 0.0
        },
        "ColorDiffuse": {
          "r": 0.713235259,
          "g": 0.713235259,
          "b": 0.713235259
        },
        "LayoutGroupSortIndex": 0,
        "Value": 0,
        "Locked": false,
        "Grid": true,
        "Snap": true,
        "IgnoreFoW": false,
        "MeasureMovement": false,
        "DragSelectable": true,
        "Autoraise": true,
        "Sticky": true,
        "Tooltip": true,
        "GridProjection": false,
        "HideWhenFaceDown": true,
        "Hands": true,
        "CardID": 400,
        "SidewaysCard": false,
        "CustomDeck": {
          "4": {
            "FaceURL": "https://steamusercontent-a.akamaihd.net/ugc/2050876934859079198/D1FA4B09D02FEBA5BB9755137AAD285462824318/",
            "BackURL": "https://steamusercontent-a.akamaihd.net/ugc/2050876934859079198/D1FA4B09D02FEBA5BB9755137AAD285462824318/",
            "NumWidth": 1,
            "NumHeight": 1,
            "BackIsHidden": true,
            "UniqueBack": false,
            "Type": 1
          }
        },
        "LuaScript": "",
        "LuaScriptState": "",
        "XmlUI": ""
      }
    ]
  },
  {
    "GUID": "5bbf29",
    "Name": "CardCustom",
    "Transform": {
      "posX": 2.14234233,
      "posY": 0.0,
      "posZ": -5.122262,
      "rotX": -8.797401E-08,
      "rotY": 180.0,
      "rotZ": -3.280339E-07,
      "scaleX": 2.79291272,
      "scaleY": 0.065,
      "scaleZ": 3.91000056
    },
    "Nickname": "",
    "Description": "",
    "GMNotes": "",
    "AltLookAngle": {
      "x": 0.0,
      "y": 0.0,
      "z": 0.0
    },
    "ColorDiffuse": {
      "r": 0.713235259,
      "g": 0.713235259,
      "b": 0.713235259
    },
    "LayoutGroupSortIndex": 0,
    "Value": 0,
    "Locked": true,
    "Grid": true,
    "Snap": true,
    "IgnoreFoW": false,
    "MeasureMovement": false,
    "DragSelectable": true,
    "Autoraise": true,
    "Sticky": true,
    "Tooltip": true,
    "GridProjection": false,
    "HideWhenFaceDown": true,
    "Hands": true,
    "CardID": 30400,
    "SidewaysCard": false,
    "CustomDeck": {
      "304": {
        "FaceURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794548479/1334E2934F85878167A301C71EBDE0DD7AB39D9C/",
        "BackURL": "https://steamusercontent-a.akamaihd.net/ugc/2281700278794548479/1334E2934F85878167A301C71EBDE0DD7AB39D9C/",
        "NumWidth": 1,
        "NumHeight": 1,
        "BackIsHidden": true,
        "UniqueBack": false,
        "Type": 0
      }
    },
    "LuaScript": "",
    "LuaScriptState": "",
    "XmlUI": ""
  }
]
}]],

}

