#!/usr/bin/env python3
import argparse
import os
import subprocess
import sys
import time
from pathlib import Path


def iter_lua_files(root: Path):
    stack = [root]
    seen_dirs: set[str] = set()

    while stack:
        current = stack.pop()
        real_dir = os.path.realpath(current)
        if real_dir in seen_dirs:
            continue
        seen_dirs.add(real_dir)

        try:
            with os.scandir(current) as it:
                entries = list(it)
        except FileNotFoundError:
            continue

        for entry in entries:
            try:
                if entry.is_dir(follow_symlinks=True):
                    stack.append(Path(entry.path))
                elif entry.is_file(follow_symlinks=True):
                    if entry.name.endswith((".ttslua", ".lua")):
                        yield Path(entry.path)
            except FileNotFoundError:
                continue


def iter_json_files(root: Path):
    stack = [root]
    seen_dirs: set[str] = set()

    while stack:
        current = stack.pop()
        real_dir = os.path.realpath(current)
        if real_dir in seen_dirs:
            continue
        seen_dirs.add(real_dir)

        try:
            with os.scandir(current) as it:
                entries = list(it)
        except FileNotFoundError:
            continue

        for entry in entries:
            try:
                if entry.is_dir(follow_symlinks=True):
                    stack.append(Path(entry.path))
                elif entry.is_file(follow_symlinks=True) and entry.name.endswith(".json"):
                    yield Path(entry.path)
            except FileNotFoundError:
                continue


def snapshot(lua_root: Path, json_root: Path) -> dict[str, tuple[int, int]]:
    files: dict[str, tuple[int, int]] = {}

    for lua_file in iter_lua_files(lua_root):
        try:
            st = lua_file.stat()
        except FileNotFoundError:
            continue
        files[str(lua_file.resolve())] = (st.st_mtime_ns, st.st_size)

    for json_file in iter_json_files(json_root):
        try:
            st = json_file.stat()
        except FileNotFoundError:
            continue
        files[str(json_file.resolve())] = (st.st_mtime_ns, st.st_size)

    return files


def run_compile(
    compiler_dir: Path,
    copy_to_saves: bool,
    save_and_play: bool,
    compiled_json: str,
    tts_host: str,
    tts_port: int,
) -> bool:
    cmd = [str(compiler_dir / "compile_linux.sh")]
    if copy_to_saves:
        cmd.append("--test")

    print(f"\n[{time.strftime('%H:%M:%S')}] Compiling...")
    proc = subprocess.run(cmd, cwd=compiler_dir)
    ok = proc.returncode == 0

    if ok:
        print(f"[{time.strftime('%H:%M:%S')}] Compile OK")
        if save_and_play:
            save_and_play_cmd = [
                sys.executable,
                str(compiler_dir / "tts_save_and_play.py"),
                "--compiled-json",
                str(compiler_dir / compiled_json),
                "--host",
                tts_host,
                "--port",
                str(tts_port),
            ]
            sap = subprocess.run(save_and_play_cmd, cwd=compiler_dir)
            if sap.returncode == 0:
                print(f"[{time.strftime('%H:%M:%S')}] SaveAndPlay OK")
            else:
                print(
                    f"[{time.strftime('%H:%M:%S')}] SaveAndPlay FAILED (exit {sap.returncode})"
                )
    else:
        print(f"[{time.strftime('%H:%M:%S')}] Compile FAILED (exit {proc.returncode})")

    return ok


def _is_json_path(path: str) -> bool:
    return path.lower().endswith(".json")


def main() -> int:
    parser = argparse.ArgumentParser(description="Watch HutberLua and auto-run compile_linux.sh on save.")
    parser.add_argument("--interval", type=float, default=0.6, help="Polling interval in seconds.")
    parser.add_argument("--debounce", type=float, default=0.8, help="Delay after last change before compile.")
    parser.add_argument("--no-copy", action="store_true", help="Do not pass --test (skip auto-copy to TTS saves).")
    parser.add_argument("--skip-initial", action="store_true", help="Do not compile once when watcher starts.")
    parser.add_argument(
        "--no-save-and-play",
        action="store_true",
        help="Compile only, do not send SaveAndPlay to TTS.",
    )
    parser.add_argument(
        "--compiled-json",
        default="hutber_CA_2025_compiled.json",
        help="Compiled JSON filename generated by compile_linux.sh.",
    )
    parser.add_argument("--tts-host", default="127.0.0.1", help="TTS External Editor host.")
    parser.add_argument("--tts-port", type=int, default=39999, help="TTS External Editor port.")
    args = parser.parse_args()

    compiler_dir = Path(__file__).resolve().parent
    repo_root = compiler_dir.parent
    lua_root = repo_root / "HutberLua"
    json_root = repo_root / "BASEJSON"
    json_file = json_root / "hutber_base.json"

    if not lua_root.exists():
        print(f"ERROR: Lua folder not found: {lua_root}", file=sys.stderr)
        return 1

    if not json_file.exists():
        print(f"ERROR: JSON file not found: {json_file}", file=sys.stderr)
        return 1

    print(f"Watching: {lua_root}")
    print(f"Watching: {json_root}/*.json")
    print(f"Mode: {'copy to TTS saves' if not args.no_copy else 'compile only'}")
    print(
        "SaveAndPlay: "
        + ("enabled" if not args.no_save_and_play else "disabled")
        + f" ({args.tts_host}:{args.tts_port})"
    )

    if not args.skip_initial:
        run_compile(
            compiler_dir,
            copy_to_saves=not args.no_copy,
            save_and_play=not args.no_save_and_play,
            compiled_json=args.compiled_json,
            tts_host=args.tts_host,
            tts_port=args.tts_port,
        )

    previous = snapshot(lua_root, json_root)
    pending = False
    pending_has_json = False
    last_change_ts = 0.0

    try:
        while True:
            time.sleep(max(0.1, args.interval))
            current = snapshot(lua_root, json_root)

            if current != previous:
                pending = True
                last_change_ts = time.time()

                prev_keys = set(previous.keys())
                curr_keys = set(current.keys())
                added = curr_keys - prev_keys
                removed = prev_keys - curr_keys
                common = prev_keys & curr_keys
                changed = {k for k in common if previous[k] != current[k]}
                touched_count = len(added) + len(removed) + len(changed)
                changed_paths = added | removed | changed
                if any(_is_json_path(p) for p in changed_paths):
                    pending_has_json = True

                print(f"[{time.strftime('%H:%M:%S')}] Change detected ({touched_count} file(s))")
                previous = current

            if pending and (time.time() - last_change_ts) >= args.debounce:
                should_save_and_play = (not args.no_save_and_play) and (not pending_has_json)
                run_compile(
                    compiler_dir,
                    copy_to_saves=not args.no_copy,
                    save_and_play=should_save_and_play,
                    compiled_json=args.compiled_json,
                    tts_host=args.tts_host,
                    tts_port=args.tts_port,
                )
                if pending_has_json and not args.no_save_and_play:
                    print(
                        f"[{time.strftime('%H:%M:%S')}] JSON/ObjectState change detected; "
                        "full save reload is required in TTS (SaveAndPlay updates scripts/UI only)."
                    )
                pending = False
                pending_has_json = False

    except KeyboardInterrupt:
        print("\nWatcher stopped.")
        return 0


if __name__ == "__main__":
    raise SystemExit(main())
