-- FTC-GUID: fa3db4,abd07a

    function onLoad()
        self.createButton({
            label = "Load Map",
            font_size = 115,
            color = {0, 1, 0,},
            position = {-0.96, 0.5, 0},
            rotation = {0, 90, 0},
            scale = {1.3, 1, .7},
            width = 570,
            height = 160,
            click_function = "loadMap",
            function_owner = self,
        })

        self.createButton({
            label = "Clear Map",
            font_size = 100,
            position = {1, 0.5, 0},
            rotation = {0, 90, 0},
            scale = {.6, .6, .4},
            width = 530,
            height = 130,
            color = {1, 0, 0},
            click_function = "clearMap",
            function_owner = self,
        })
    end

    -------------------
    -- Prepares the terrain saved into the card from Map Saver tool
    string.split = function(s, delimiter)
        local result = { }
        local from  = 1
        local delim_from, delim_to = string.find( s, delimiter, from  )
        while delim_from do
            table.insert( result, string.sub( s, from , delim_from-1 ) )
            from  = delim_to + 1
            delim_from, delim_to = string.find( s, delimiter, from  )
        end
        table.insert( result, string.sub( s, from  ) )
        return result
    end

	function scriptzoneCallback(zone) --This deletes everything except the things listed, when the scripting zone is briefly spawned.

        local objects = zone.getObjects()

        for i, obj in ipairs(objects) do
            if obj.getGUID() ~= "e7ca6e" --Exclude Map Buidler Table
                and
                obj.getGUID() ~= "6012bf" --...and ForceOrg Table...
                and
                obj.getGUID() ~= "4ee1f2" --...and FTC board matObjSurface
                and
                obj.getGUID() ~= "948ce5" --...and FTC Table
                and
                obj.getGUID() ~= "28865a" --...and FTC Felt Surface
                then
                obj.destruct()
            end
        end
        zone.destruct()
    end
    function loadMap(objectClicked, clickerColor, altClickUsed)
        -------------------
        -- Spawn the scripting zone, which uses the callback above that deletes everything then deletes itself.
        local scriptzoneParams = {                  -- Define the parameters for the scripting zone
            position = {x=0, y=26, z=0},
            --scale = {x=30.15, y=73, z=22.03}, --Kill Team Size
            --scale = {x=30.15, y=73, z=44.04}, --Incursion and Combat Patrol Size
            scale = {x=60.12, y=73, z=44.04}, --Strike Force Size
            --scale = {x=90.07, y=73, z=44.04}, --Onslaught Size
            type = 'ScriptingTrigger',              -- Use the ScriptingTrigger type to spawn a Scripting Zone
            callback_function = scriptzoneCallback, -- Specify the function to call when the zone is created
            callback_owner = self,
            }

		spawnObject(scriptzoneParams)
		-- Then Sspawn the objects stored in the card

        Wait.time(
        function()
            for _, objectJSON in ipairs(objectJSONs) do
                -- Spawn the map from the JSON data
                spawnObjectJSON({
                    json = objectJSON
                })
            end
        end, .5)
    end

    -----------------------------------------------------------------------------------------------------------------
    -- This function runs when the Clear Map button is clicked on the Map Card
    function clearMap(objectClicked, clickerColor, altClickUsed)

        local scriptzoneParams = {                  -- Define the parameters for the scripting zone
            position = {x=0, y=26, z=0},
            --scale = {x=30.15, y=73, z=22.03}, --Kill Team Size
            --scale = {x=30.15, y=73, z=44.04}, --Incursion and Combat Patrol Size
            scale = {x=60.12, y=73, z=44.04}, --Strike Force Size
            --scale = {x=90.07, y=73, z=44.04}, --Onslaught Size
            type = 'ScriptingTrigger',              -- Use the ScriptingTrigger type to spawn a Scripting Zone
            callback_function = scriptzoneCallback, -- Specify the function to call when the zone is created
            callback_owner = self,
            }

    spawnObject(scriptzoneParams)

    end


objectJSONs = {
    [[{
      "GUID": "f1fab4",
      "Name": "BlockSquare",
      "Transform": {
        "posX": 15.0002909,
        "posY": 1.03038812,
        "posZ": -15.9589224,
        "rotX": 1.40255088E-08,
        "rotY": 90.01535,
        "rotZ": -4.329652E-07,
        "scaleX": 4.0,
        "scaleY": 0.1,
        "scaleZ": 6.0
      },
      "Nickname": "Ruin (2\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 0.2322883,
        "g": 0.226622909,
        "b": 0.351262718
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "5465db",
          "Name": "Custom_Model",
          "Transform": {
            "posX": 0.05186952,
            "posY": -0.9508598,
            "posZ": 0.424282759,
            "rotX": 0.0241138525,
            "rotY": 90.00001,
            "rotZ": -2.22614815E-07,
            "scaleX": 0.158333316,
            "scaleY": 9.499966,
            "scaleZ": 0.14669925
          },
          "Nickname": "prison wall 3",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1852681510007517842/A49F5DB08B4B726084948D1FD79B7D625F24EE07/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1829033806572958162/ADFC131F71CC6446077F60F87C980A9B9DCF7C12/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1852681510007517842/A49F5DB08B4B726084948D1FD79B7D625F24EE07/",
            "Convex": false,
            "MaterialIndex": 3,
            "TypeIndex": 4,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        },
        {
          "GUID": "3b8767",
          "Name": "Custom_Model",
          "Transform": {
            "posX": -0.3898291,
            "posY": -0.7396576,
            "posZ": -0.00557935238,
            "rotX": -2.2365154E-07,
            "rotY": 2.11742186E-15,
            "rotZ": -1.084896E-06,
            "scaleX": 0.237500012,
            "scaleY": 9.5,
            "scaleZ": 0.158333346
          },
          "Nickname": "prison wall 3",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1852681510007517842/A49F5DB08B4B726084948D1FD79B7D625F24EE07/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1829033806572958162/ADFC131F71CC6446077F60F87C980A9B9DCF7C12/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1852681510007517842/A49F5DB08B4B726084948D1FD79B7D625F24EE07/",
            "Convex": false,
            "MaterialIndex": 3,
            "TypeIndex": 4,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        }
      ]
    }]],
    [[{
      "GUID": "804aea",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": 15.3977623,
        "posY": 1.07984936,
        "posZ": -4.237103,
        "rotX": 0.000225428972,
        "rotY": 155.520233,
        "rotZ": -4.415337E-05,
        "scaleX": 2.1296494,
        "scaleY": 3.50000548,
        "scaleZ": 1.0000093
      },
      "Nickname": "Ruin (9\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "12f429",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": 1.7423991,
            "posY": 3.09745587E-06,
            "posZ": 1.60632765,
            "rotX": 0.000293263525,
            "rotY": 269.6391,
            "rotZ": 0.000230568316,
            "scaleX": 0.999945939,
            "scaleY": 0.9999999,
            "scaleZ": 0.469575137
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": "",
          "ChildObjects": [
            {
              "GUID": "5cc9a0",
              "Name": "Custom_Assetbundle",
              "Transform": {
                "posX": 1.49492633,
                "posY": 0.008888452,
                "posZ": 0.0140595315,
                "rotX": 4.759174E-05,
                "rotY": 359.299316,
                "rotZ": -0.000981894,
                "scaleX": 0.800000131,
                "scaleY": 0.9999984,
                "scaleZ": 0.7999926
              },
              "Nickname": "",
              "Description": "",
              "GMNotes": "",
              "AltLookAngle": {
                "x": 0.0,
                "y": 0.0,
                "z": 0.0
              },
              "ColorDiffuse": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "LayoutGroupSortIndex": 0,
              "Value": 0,
              "Locked": true,
              "Grid": true,
              "Snap": true,
              "IgnoreFoW": false,
              "MeasureMovement": false,
              "DragSelectable": true,
              "Autoraise": true,
              "Sticky": true,
              "Tooltip": true,
              "GridProjection": false,
              "HideWhenFaceDown": false,
              "Hands": false,
              "CustomAssetbundle": {
                "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
                "AssetbundleSecondaryURL": "",
                "MaterialIndex": 2,
                "TypeIndex": 1,
                "LoopingEffectIndex": 0
              },
              "LuaScript": "",
              "LuaScriptState": "",
              "XmlUI": "",
              "ChildObjects": [
                {
                  "GUID": "7ba0f2",
                  "Name": "Custom_Assetbundle",
                  "Transform": {
                    "posX": -3.88075447,
                    "posY": -1.63020541E-05,
                    "posZ": 0.08409618,
                    "rotX": -0.001445235,
                    "rotY": 90.54133,
                    "rotZ": 0.0008072965,
                    "scaleX": 0.9999997,
                    "scaleY": 1.0,
                    "scaleZ": 0.9999996
                  },
                  "Nickname": "",
                  "Description": "",
                  "GMNotes": "",
                  "AltLookAngle": {
                    "x": 0.0,
                    "y": 0.0,
                    "z": 0.0
                  },
                  "ColorDiffuse": {
                    "r": 1.0,
                    "g": 1.0,
                    "b": 1.0
                  },
                  "LayoutGroupSortIndex": 0,
                  "Value": 0,
                  "Locked": true,
                  "Grid": true,
                  "Snap": true,
                  "IgnoreFoW": false,
                  "MeasureMovement": false,
                  "DragSelectable": true,
                  "Autoraise": true,
                  "Sticky": true,
                  "Tooltip": true,
                  "GridProjection": false,
                  "HideWhenFaceDown": false,
                  "Hands": false,
                  "CustomAssetbundle": {
                    "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
                    "AssetbundleSecondaryURL": "",
                    "MaterialIndex": 2,
                    "TypeIndex": 1,
                    "LoopingEffectIndex": 0
                  },
                  "LuaScript": "",
                  "LuaScriptState": "",
                  "XmlUI": "",
                  "ChildObjects": [
                    {
                      "GUID": "f0f588",
                      "Name": "Custom_Assetbundle",
                      "Transform": {
                        "posX": -9.115003,
                        "posY": 5.31046644E-05,
                        "posZ": 0.0971415,
                        "rotX": -0.00451679062,
                        "rotY": 358.773,
                        "rotZ": -0.000749370141,
                        "scaleX": 1.0,
                        "scaleY": 0.9999999,
                        "scaleZ": 1.0
                      },
                      "Nickname": "",
                      "Description": "",
                      "GMNotes": "",
                      "AltLookAngle": {
                        "x": 0.0,
                        "y": 0.0,
                        "z": 0.0
                      },
                      "ColorDiffuse": {
                        "r": 1.0,
                        "g": 1.0,
                        "b": 1.0
                      },
                      "LayoutGroupSortIndex": 0,
                      "Value": 0,
                      "Locked": true,
                      "Grid": true,
                      "Snap": true,
                      "IgnoreFoW": false,
                      "MeasureMovement": false,
                      "DragSelectable": true,
                      "Autoraise": true,
                      "Sticky": true,
                      "Tooltip": true,
                      "GridProjection": false,
                      "HideWhenFaceDown": false,
                      "Hands": false,
                      "CustomAssetbundle": {
                        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
                        "AssetbundleSecondaryURL": "",
                        "MaterialIndex": 2,
                        "TypeIndex": 1,
                        "LoopingEffectIndex": 0
                      },
                      "LuaScript": "",
                      "LuaScriptState": "",
                      "XmlUI": "",
                      "ChildObjects": [
                        {
                          "GUID": "9c41f8",
                          "Name": "BlockSquare",
                          "Transform": {
                            "posX": 2.15232825,
                            "posY": -0.0232538041,
                            "posZ": 3.14037466,
                            "rotX": 0.004969741,
                            "rotY": 1.74724543,
                            "rotZ": -0.000221229639,
                            "scaleX": 15.1010466,
                            "scaleY": 0.02857143,
                            "scaleZ": 7.500001
                          },
                          "Nickname": "Ruin (9\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
                          "Description": "",
                          "GMNotes": "",
                          "AltLookAngle": {
                            "x": 0.0,
                            "y": 0.0,
                            "z": 0.0
                          },
                          "ColorDiffuse": {
                            "r": 0.232399821,
                            "g": 0.2239998,
                            "b": 0.349999845
                          },
                          "LayoutGroupSortIndex": 0,
                          "Value": 0,
                          "Locked": true,
                          "Grid": true,
                          "Snap": true,
                          "IgnoreFoW": false,
                          "MeasureMovement": false,
                          "DragSelectable": true,
                          "Autoraise": true,
                          "Sticky": true,
                          "Tooltip": true,
                          "GridProjection": false,
                          "HideWhenFaceDown": false,
                          "Hands": false,
                          "LuaScript": "\nBCBtype = \"terrain\"\n",
                          "LuaScriptState": "",
                          "XmlUI": ""
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    }]],
    [[{
      "GUID": "336080",
      "Name": "Custom_Model",
      "Transform": {
        "posX": 27.03334,
        "posY": 1.00376642,
        "posZ": 3.99029756,
        "rotX": 0.0243235584,
        "rotY": 270.004181,
        "rotZ": 359.70047,
        "scaleX": 0.9500003,
        "scaleY": 0.95,
        "scaleZ": 0.9500004
      },
      "Nickname": "Ruin (2\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomMesh": {
        "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1852681510007517842/A49F5DB08B4B726084948D1FD79B7D625F24EE07/",
        "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1829033806572958162/ADFC131F71CC6446077F60F87C980A9B9DCF7C12/",
        "NormalURL": "",
        "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1852681510007517842/A49F5DB08B4B726084948D1FD79B7D625F24EE07/",
        "Convex": false,
        "MaterialIndex": 3,
        "TypeIndex": 4,
        "CustomShader": {
          "SpecularColor": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "SpecularIntensity": 0.0,
          "SpecularSharpness": 2.0,
          "FresnelStrength": 0.0
        },
        "CastShadows": true
      },
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "524973",
          "Name": "BlockSquare",
          "Transform": {
            "posX": 0.0124565065,
            "posY": 0.07785879,
            "posZ": 0.0352382064,
            "rotX": -5.336085E-07,
            "rotY": -5.2180965E-15,
            "rotZ": 1.12057785E-06,
            "scaleX": 4.210525,
            "scaleY": 0.105263166,
            "scaleZ": 6.315787
          },
          "Nickname": "Ruin (2\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 0.23228848,
            "g": 0.226623088,
            "b": 0.3512629
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "LuaScript": "\nBCBtype = \"terrain\"\n",
          "LuaScriptState": "",
          "XmlUI": ""
        },
        {
          "GUID": "5465db",
          "Name": "Custom_Model",
          "Transform": {
            "posX": -0.006412663,
            "posY": -0.0381458141,
            "posZ": 2.89757037,
            "rotX": 0.140613526,
            "rotY": 89.98819,
            "rotZ": 0.275799572,
            "scaleX": 0.999999344,
            "scaleY": 1.00000346,
            "scaleZ": 0.617680848
          },
          "Nickname": "prison wall 3",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1852681510007517842/A49F5DB08B4B726084948D1FD79B7D625F24EE07/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1829033806572958162/ADFC131F71CC6446077F60F87C980A9B9DCF7C12/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1852681510007517842/A49F5DB08B4B726084948D1FD79B7D625F24EE07/",
            "Convex": false,
            "MaterialIndex": 3,
            "TypeIndex": 4,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        }
      ]
    }]],
    [[{
      "GUID": "3b8767",
      "Name": "Custom_Model",
      "Transform": {
        "posX": -27.03296,
        "posY": 1.00521779,
        "posZ": -3.9882133,
        "rotX": 0.0208967514,
        "rotY": 90.00466,
        "rotZ": 359.417664,
        "scaleX": 0.9500003,
        "scaleY": 0.95,
        "scaleZ": 0.9500004
      },
      "Nickname": "Ruin (2\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomMesh": {
        "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1852681510007517842/A49F5DB08B4B726084948D1FD79B7D625F24EE07/",
        "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1829033806572958162/ADFC131F71CC6446077F60F87C980A9B9DCF7C12/",
        "NormalURL": "",
        "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1852681510007517842/A49F5DB08B4B726084948D1FD79B7D625F24EE07/",
        "Convex": false,
        "MaterialIndex": 3,
        "TypeIndex": 4,
        "CustomShader": {
          "SpecularColor": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "SpecularIntensity": 0.0,
          "SpecularSharpness": 2.0,
          "FresnelStrength": 0.0
        },
        "CastShadows": true
      },
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "524973",
          "Name": "BlockSquare",
          "Transform": {
            "posX": 0.0124565065,
            "posY": 0.07785879,
            "posZ": 0.0352382064,
            "rotX": -5.336085E-07,
            "rotY": -5.2180965E-15,
            "rotZ": 1.12057785E-06,
            "scaleX": 4.210525,
            "scaleY": 0.105263166,
            "scaleZ": 6.315787
          },
          "Nickname": "Ruin (2\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 0.23228848,
            "g": 0.226623088,
            "b": 0.3512629
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "LuaScript": "\nBCBtype = \"terrain\"\n",
          "LuaScriptState": "",
          "XmlUI": ""
        },
        {
          "GUID": "5465db",
          "Name": "Custom_Model",
          "Transform": {
            "posX": -0.006412663,
            "posY": -0.0381458141,
            "posZ": 2.89757037,
            "rotX": 0.140613526,
            "rotY": 89.98819,
            "rotZ": 0.275799572,
            "scaleX": 0.999999344,
            "scaleY": 1.00000346,
            "scaleZ": 0.617680848
          },
          "Nickname": "prison wall 3",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1852681510007517842/A49F5DB08B4B726084948D1FD79B7D625F24EE07/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1829033806572958162/ADFC131F71CC6446077F60F87C980A9B9DCF7C12/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1852681510007517842/A49F5DB08B4B726084948D1FD79B7D625F24EE07/",
            "Convex": false,
            "MaterialIndex": 3,
            "TypeIndex": 4,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        }
      ]
    }]],
    [[{
      "GUID": "cf3166",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": -15.3977623,
        "posY": 1.08039558,
        "posZ": 4.237103,
        "rotX": 0.000226123913,
        "rotY": 335.5202,
        "rotZ": -4.37370982E-05,
        "scaleX": 2.1296494,
        "scaleY": 3.50000548,
        "scaleZ": 1.0000093
      },
      "Nickname": "Ruin (9\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "12f429",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": 1.7423991,
            "posY": 3.09745587E-06,
            "posZ": 1.60632765,
            "rotX": 0.000293263525,
            "rotY": 269.6391,
            "rotZ": 0.000230568316,
            "scaleX": 0.999945939,
            "scaleY": 0.9999999,
            "scaleZ": 0.469575137
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": "",
          "ChildObjects": [
            {
              "GUID": "5cc9a0",
              "Name": "Custom_Assetbundle",
              "Transform": {
                "posX": 1.49492633,
                "posY": 0.008888452,
                "posZ": 0.0140595315,
                "rotX": 4.759174E-05,
                "rotY": 359.299316,
                "rotZ": -0.000981894,
                "scaleX": 0.800000131,
                "scaleY": 0.9999984,
                "scaleZ": 0.7999926
              },
              "Nickname": "",
              "Description": "",
              "GMNotes": "",
              "AltLookAngle": {
                "x": 0.0,
                "y": 0.0,
                "z": 0.0
              },
              "ColorDiffuse": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "LayoutGroupSortIndex": 0,
              "Value": 0,
              "Locked": true,
              "Grid": true,
              "Snap": true,
              "IgnoreFoW": false,
              "MeasureMovement": false,
              "DragSelectable": true,
              "Autoraise": true,
              "Sticky": true,
              "Tooltip": true,
              "GridProjection": false,
              "HideWhenFaceDown": false,
              "Hands": false,
              "CustomAssetbundle": {
                "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
                "AssetbundleSecondaryURL": "",
                "MaterialIndex": 2,
                "TypeIndex": 1,
                "LoopingEffectIndex": 0
              },
              "LuaScript": "",
              "LuaScriptState": "",
              "XmlUI": "",
              "ChildObjects": [
                {
                  "GUID": "7ba0f2",
                  "Name": "Custom_Assetbundle",
                  "Transform": {
                    "posX": -3.88075447,
                    "posY": -1.63020541E-05,
                    "posZ": 0.08409618,
                    "rotX": -0.001445235,
                    "rotY": 90.54133,
                    "rotZ": 0.0008072965,
                    "scaleX": 0.9999997,
                    "scaleY": 1.0,
                    "scaleZ": 0.9999996
                  },
                  "Nickname": "",
                  "Description": "",
                  "GMNotes": "",
                  "AltLookAngle": {
                    "x": 0.0,
                    "y": 0.0,
                    "z": 0.0
                  },
                  "ColorDiffuse": {
                    "r": 1.0,
                    "g": 1.0,
                    "b": 1.0
                  },
                  "LayoutGroupSortIndex": 0,
                  "Value": 0,
                  "Locked": true,
                  "Grid": true,
                  "Snap": true,
                  "IgnoreFoW": false,
                  "MeasureMovement": false,
                  "DragSelectable": true,
                  "Autoraise": true,
                  "Sticky": true,
                  "Tooltip": true,
                  "GridProjection": false,
                  "HideWhenFaceDown": false,
                  "Hands": false,
                  "CustomAssetbundle": {
                    "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
                    "AssetbundleSecondaryURL": "",
                    "MaterialIndex": 2,
                    "TypeIndex": 1,
                    "LoopingEffectIndex": 0
                  },
                  "LuaScript": "",
                  "LuaScriptState": "",
                  "XmlUI": "",
                  "ChildObjects": [
                    {
                      "GUID": "f0f588",
                      "Name": "Custom_Assetbundle",
                      "Transform": {
                        "posX": -9.115003,
                        "posY": 5.31046644E-05,
                        "posZ": 0.0971415,
                        "rotX": -0.00451679062,
                        "rotY": 358.773,
                        "rotZ": -0.000749370141,
                        "scaleX": 1.0,
                        "scaleY": 0.9999999,
                        "scaleZ": 1.0
                      },
                      "Nickname": "",
                      "Description": "",
                      "GMNotes": "",
                      "AltLookAngle": {
                        "x": 0.0,
                        "y": 0.0,
                        "z": 0.0
                      },
                      "ColorDiffuse": {
                        "r": 1.0,
                        "g": 1.0,
                        "b": 1.0
                      },
                      "LayoutGroupSortIndex": 0,
                      "Value": 0,
                      "Locked": true,
                      "Grid": true,
                      "Snap": true,
                      "IgnoreFoW": false,
                      "MeasureMovement": false,
                      "DragSelectable": true,
                      "Autoraise": true,
                      "Sticky": true,
                      "Tooltip": true,
                      "GridProjection": false,
                      "HideWhenFaceDown": false,
                      "Hands": false,
                      "CustomAssetbundle": {
                        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
                        "AssetbundleSecondaryURL": "",
                        "MaterialIndex": 2,
                        "TypeIndex": 1,
                        "LoopingEffectIndex": 0
                      },
                      "LuaScript": "",
                      "LuaScriptState": "",
                      "XmlUI": "",
                      "ChildObjects": [
                        {
                          "GUID": "9c41f8",
                          "Name": "BlockSquare",
                          "Transform": {
                            "posX": 2.15232825,
                            "posY": -0.0232538041,
                            "posZ": 3.14037466,
                            "rotX": 0.004969741,
                            "rotY": 1.74724543,
                            "rotZ": -0.000221229639,
                            "scaleX": 15.1010466,
                            "scaleY": 0.02857143,
                            "scaleZ": 7.500001
                          },
                          "Nickname": "Ruin (9\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
                          "Description": "",
                          "GMNotes": "",
                          "AltLookAngle": {
                            "x": 0.0,
                            "y": 0.0,
                            "z": 0.0
                          },
                          "ColorDiffuse": {
                            "r": 0.232399821,
                            "g": 0.2239998,
                            "b": 0.349999845
                          },
                          "LayoutGroupSortIndex": 0,
                          "Value": 0,
                          "Locked": true,
                          "Grid": true,
                          "Snap": true,
                          "IgnoreFoW": false,
                          "MeasureMovement": false,
                          "DragSelectable": true,
                          "Autoraise": true,
                          "Sticky": true,
                          "Tooltip": true,
                          "GridProjection": false,
                          "HideWhenFaceDown": false,
                          "Hands": false,
                          "LuaScript": "\nBCBtype = \"terrain\"\n",
                          "LuaScriptState": "",
                          "XmlUI": ""
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    }]],
    [[{
      "GUID": "524973",
      "Name": "BlockSquare",
      "Transform": {
        "posX": -14.9999733,
        "posY": 1.088496,
        "posZ": 15.9588728,
        "rotX": 359.7237,
        "rotY": 270.015259,
        "rotZ": 0.100142315,
        "scaleX": 4.0,
        "scaleY": 0.1,
        "scaleZ": 6.0
      },
      "Nickname": "Ruin (2\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 0.232288331,
        "g": 0.226622939,
        "b": 0.351262748
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "5465db",
          "Name": "Custom_Model",
          "Transform": {
            "posX": 0.05186952,
            "posY": -0.9508598,
            "posZ": 0.424282759,
            "rotX": 0.0241138525,
            "rotY": 90.00001,
            "rotZ": -2.22614815E-07,
            "scaleX": 0.158333316,
            "scaleY": 9.499966,
            "scaleZ": 0.14669925
          },
          "Nickname": "prison wall 3",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1852681510007517842/A49F5DB08B4B726084948D1FD79B7D625F24EE07/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1829033806572958162/ADFC131F71CC6446077F60F87C980A9B9DCF7C12/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1852681510007517842/A49F5DB08B4B726084948D1FD79B7D625F24EE07/",
            "Convex": false,
            "MaterialIndex": 3,
            "TypeIndex": 4,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        },
        {
          "GUID": "3b8767",
          "Name": "Custom_Model",
          "Transform": {
            "posX": -0.3898291,
            "posY": -0.7396576,
            "posZ": -0.00557935238,
            "rotX": -2.2365154E-07,
            "rotY": 2.11742186E-15,
            "rotZ": -1.084896E-06,
            "scaleX": 0.237500012,
            "scaleY": 9.5,
            "scaleZ": 0.158333346
          },
          "Nickname": "prison wall 3",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1852681510007517842/A49F5DB08B4B726084948D1FD79B7D625F24EE07/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1829033806572958162/ADFC131F71CC6446077F60F87C980A9B9DCF7C12/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1852681510007517842/A49F5DB08B4B726084948D1FD79B7D625F24EE07/",
            "Convex": false,
            "MaterialIndex": 3,
            "TypeIndex": 4,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        }
      ]
    }]],
    [[{
      "GUID": "43121c",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": -4.5,
        "posY": 1.07426035,
        "posZ": -4.5,
        "rotX": 0.0,
        "rotY": 90.0,
        "rotZ": 0.0,
        "scaleX": 1.14682209,
        "scaleY": 3.50000548,
        "scaleZ": 1.00000978
      },
      "Nickname": "Ruin (9\")  [sup]Barricade parts of this terrain feature are considered as 2\" high. Models may only be placed on the bottom level of this terrain feature[/sup]",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "648368",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": 1.82001734,
            "posY": 0.008893557,
            "posZ": 0.0297400448,
            "rotX": 0.000479145383,
            "rotY": 180.004181,
            "rotZ": -0.00104916352,
            "scaleX": 0.697580159,
            "scaleY": 0.9999984,
            "scaleZ": 0.79999274
          },
          "Nickname": "Ruin",
          "Description": "You can NOT draw line of sight between the gaps in walls",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "\nBCBtype = \"terrain\"\n",
          "LuaScriptState": "",
          "XmlUI": "",
          "ChildObjects": [
            {
              "GUID": "3c9aee",
              "Name": "Custom_Assetbundle",
              "Transform": {
                "posX": 5.29024124,
                "posY": -0.008868753,
                "posZ": 3.48390365,
                "rotX": -0.0007774373,
                "rotY": 89.99856,
                "rotZ": -0.000260690722,
                "scaleX": 1.859146,
                "scaleY": 1.00000143,
                "scaleZ": 1.25001061
              },
              "Nickname": "",
              "Description": "",
              "GMNotes": "",
              "AltLookAngle": {
                "x": 0.0,
                "y": 0.0,
                "z": 0.0
              },
              "ColorDiffuse": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "LayoutGroupSortIndex": 0,
              "Value": 0,
              "Locked": true,
              "Grid": true,
              "Snap": true,
              "IgnoreFoW": false,
              "MeasureMovement": false,
              "DragSelectable": true,
              "Autoraise": true,
              "Sticky": true,
              "Tooltip": true,
              "GridProjection": false,
              "HideWhenFaceDown": false,
              "Hands": false,
              "CustomAssetbundle": {
                "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
                "AssetbundleSecondaryURL": "",
                "MaterialIndex": 2,
                "TypeIndex": 1,
                "LoopingEffectIndex": 0
              },
              "LuaScript": "",
              "LuaScriptState": "",
              "XmlUI": "",
              "ChildObjects": [
                {
                  "GUID": "a1337a",
                  "Name": "Custom_Assetbundle",
                  "Transform": {
                    "posX": 1.87392545,
                    "posY": 0.00508192275,
                    "posZ": -0.0590358973,
                    "rotX": -0.000246554235,
                    "rotY": 0.00144787412,
                    "rotZ": 3.34857141E-05,
                    "scaleX": 0.537881255,
                    "scaleY": 0.9999982,
                    "scaleZ": 0.7999932
                  },
                  "Nickname": "Ruin",
                  "Description": "You can NOT draw line of sight between the gaps in walls",
                  "GMNotes": "",
                  "AltLookAngle": {
                    "x": 0.0,
                    "y": 0.0,
                    "z": 0.0
                  },
                  "ColorDiffuse": {
                    "r": 1.0,
                    "g": 1.0,
                    "b": 1.0
                  },
                  "LayoutGroupSortIndex": 0,
                  "Value": 0,
                  "Locked": true,
                  "Grid": true,
                  "Snap": true,
                  "IgnoreFoW": false,
                  "MeasureMovement": false,
                  "DragSelectable": true,
                  "Autoraise": true,
                  "Sticky": true,
                  "Tooltip": true,
                  "GridProjection": false,
                  "HideWhenFaceDown": false,
                  "Hands": false,
                  "CustomAssetbundle": {
                    "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
                    "AssetbundleSecondaryURL": "",
                    "MaterialIndex": 2,
                    "TypeIndex": 1,
                    "LoopingEffectIndex": 0
                  },
                  "LuaScript": "\nBCBtype = \"terrain\"\n",
                  "LuaScriptState": "",
                  "XmlUI": "",
                  "ChildObjects": [
                    {
                      "GUID": "2ff768",
                      "Name": "Custom_Assetbundle",
                      "Transform": {
                        "posX": -6.87500143,
                        "posY": -1.25813173E-07,
                        "posZ": -2.14164766E-06,
                        "rotX": 1.987824E-16,
                        "rotY": 8.33763336E-10,
                        "rotZ": -2.73204441E-05,
                        "scaleX": 0.9999999,
                        "scaleY": 1.0,
                        "scaleZ": 1.00000012
                      },
                      "Nickname": "Ruin",
                      "Description": "You can NOT draw line of sight between the gaps in walls",
                      "GMNotes": "",
                      "AltLookAngle": {
                        "x": 0.0,
                        "y": 0.0,
                        "z": 0.0
                      },
                      "ColorDiffuse": {
                        "r": 1.0,
                        "g": 1.0,
                        "b": 1.0
                      },
                      "LayoutGroupSortIndex": 0,
                      "Value": 0,
                      "Locked": true,
                      "Grid": true,
                      "Snap": true,
                      "IgnoreFoW": false,
                      "MeasureMovement": false,
                      "DragSelectable": true,
                      "Autoraise": true,
                      "Sticky": true,
                      "Tooltip": true,
                      "GridProjection": false,
                      "HideWhenFaceDown": false,
                      "Hands": false,
                      "CustomAssetbundle": {
                        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
                        "AssetbundleSecondaryURL": "",
                        "MaterialIndex": 2,
                        "TypeIndex": 1,
                        "LoopingEffectIndex": 0
                      },
                      "LuaScript": "\nBCBtype = \"terrain\"\n",
                      "LuaScriptState": "",
                      "XmlUI": "",
                      "ChildObjects": [
                        {
                          "GUID": "a811d0",
                          "Name": "Custom_Model",
                          "Transform": {
                            "posX": -4.743625,
                            "posY": -0.008482325,
                            "posZ": -2.527363,
                            "rotX": 0.0251975227,
                            "rotY": 270.021484,
                            "rotZ": 359.755859,
                            "scaleX": 2.062373,
                            "scaleY": 0.471435159,
                            "scaleZ": 0.999999
                          },
                          "Nickname": "",
                          "Description": "",
                          "GMNotes": "",
                          "AltLookAngle": {
                            "x": 0.0,
                            "y": 0.0,
                            "z": 0.0
                          },
                          "ColorDiffuse": {
                            "r": 0.4441419,
                            "g": 0.4441419,
                            "b": 0.4441419
                          },
                          "LayoutGroupSortIndex": 0,
                          "Value": 0,
                          "Locked": true,
                          "Grid": true,
                          "Snap": true,
                          "IgnoreFoW": false,
                          "MeasureMovement": false,
                          "DragSelectable": true,
                          "Autoraise": true,
                          "Sticky": true,
                          "Tooltip": true,
                          "GridProjection": false,
                          "HideWhenFaceDown": false,
                          "Hands": false,
                          "CustomMesh": {
                            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009293027/95A2286D63E1AF7BB7CE9B8E33B5F27F9E975DDA/",
                            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009292144/9153E2B34BFF806C0F4E7EEFCD0594B21623FDC3/",
                            "NormalURL": "",
                            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009293027/95A2286D63E1AF7BB7CE9B8E33B5F27F9E975DDA/",
                            "Convex": false,
                            "MaterialIndex": 3,
                            "TypeIndex": 0,
                            "CustomShader": {
                              "SpecularColor": {
                                "r": 1.0,
                                "g": 1.0,
                                "b": 1.0
                              },
                              "SpecularIntensity": 0.0,
                              "SpecularSharpness": 2.0,
                              "FresnelStrength": 0.0
                            },
                            "CastShadows": true
                          },
                          "LuaScript": "",
                          "LuaScriptState": "",
                          "XmlUI": "",
                          "ChildObjects": [
                            {
                              "GUID": "698925",
                              "Name": "BlockSquare",
                              "Transform": {
                                "posX": -0.0462520532,
                                "posY": -0.0283369515,
                                "posZ": -5.92009354,
                                "rotX": -3.557538E-05,
                                "rotY": 269.9783,
                                "rotZ": -0.0010104531,
                                "scaleX": 12.5052595,
                                "scaleY": 0.060606055,
                                "scaleZ": 3.03030562
                              },
                              "Nickname": "Ruin (9\")  [sup]Barricade parts of this terrain feature are considered as 2\" high. Models may only be placed on the bottom level of this terrain feature[/sup]",
                              "Description": "",
                              "GMNotes": "",
                              "AltLookAngle": {
                                "x": 0.0,
                                "y": 0.0,
                                "z": 0.0
                              },
                              "ColorDiffuse": {
                                "r": 0.232399732,
                                "g": 0.223999709,
                                "b": 0.349999756
                              },
                              "LayoutGroupSortIndex": 0,
                              "Value": 0,
                              "Locked": true,
                              "Grid": true,
                              "Snap": true,
                              "IgnoreFoW": false,
                              "MeasureMovement": false,
                              "DragSelectable": true,
                              "Autoraise": true,
                              "Sticky": true,
                              "Tooltip": true,
                              "GridProjection": false,
                              "HideWhenFaceDown": false,
                              "Hands": false,
                              "LuaScript": "\nBCBtype = \"terrain\"\n",
                              "LuaScriptState": "",
                              "XmlUI": ""
                            }
                          ]
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    }]],
    [[{
      "GUID": "4272e5",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": 4.5,
        "posY": 1.076783,
        "posZ": 4.5,
        "rotX": 0.0,
        "rotY": 270.0,
        "rotZ": 0.0,
        "scaleX": 1.14682209,
        "scaleY": 3.50000548,
        "scaleZ": 1.00000978
      },
      "Nickname": "Ruin (9\")  [sup]Barricade parts of this terrain feature are considered as 2\" high. Models may only be placed on the bottom level of this terrain feature[/sup]",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "648368",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": 1.82001734,
            "posY": 0.008893557,
            "posZ": 0.0297400448,
            "rotX": 0.000479145383,
            "rotY": 180.004181,
            "rotZ": -0.00104916352,
            "scaleX": 0.697580159,
            "scaleY": 0.9999984,
            "scaleZ": 0.79999274
          },
          "Nickname": "Ruin",
          "Description": "You can NOT draw line of sight between the gaps in walls",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "\nBCBtype = \"terrain\"\n",
          "LuaScriptState": "",
          "XmlUI": "",
          "ChildObjects": [
            {
              "GUID": "3c9aee",
              "Name": "Custom_Assetbundle",
              "Transform": {
                "posX": 5.29024124,
                "posY": -0.008868753,
                "posZ": 3.48390365,
                "rotX": -0.0007774373,
                "rotY": 89.99856,
                "rotZ": -0.000260690722,
                "scaleX": 1.859146,
                "scaleY": 1.00000143,
                "scaleZ": 1.25001061
              },
              "Nickname": "",
              "Description": "",
              "GMNotes": "",
              "AltLookAngle": {
                "x": 0.0,
                "y": 0.0,
                "z": 0.0
              },
              "ColorDiffuse": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "LayoutGroupSortIndex": 0,
              "Value": 0,
              "Locked": true,
              "Grid": true,
              "Snap": true,
              "IgnoreFoW": false,
              "MeasureMovement": false,
              "DragSelectable": true,
              "Autoraise": true,
              "Sticky": true,
              "Tooltip": true,
              "GridProjection": false,
              "HideWhenFaceDown": false,
              "Hands": false,
              "CustomAssetbundle": {
                "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
                "AssetbundleSecondaryURL": "",
                "MaterialIndex": 2,
                "TypeIndex": 1,
                "LoopingEffectIndex": 0
              },
              "LuaScript": "",
              "LuaScriptState": "",
              "XmlUI": "",
              "ChildObjects": [
                {
                  "GUID": "a1337a",
                  "Name": "Custom_Assetbundle",
                  "Transform": {
                    "posX": 1.87392545,
                    "posY": 0.00508192275,
                    "posZ": -0.0590358973,
                    "rotX": -0.000246554235,
                    "rotY": 0.00144787412,
                    "rotZ": 3.34857141E-05,
                    "scaleX": 0.537881255,
                    "scaleY": 0.9999982,
                    "scaleZ": 0.7999932
                  },
                  "Nickname": "Ruin",
                  "Description": "You can NOT draw line of sight between the gaps in walls",
                  "GMNotes": "",
                  "AltLookAngle": {
                    "x": 0.0,
                    "y": 0.0,
                    "z": 0.0
                  },
                  "ColorDiffuse": {
                    "r": 1.0,
                    "g": 1.0,
                    "b": 1.0
                  },
                  "LayoutGroupSortIndex": 0,
                  "Value": 0,
                  "Locked": true,
                  "Grid": true,
                  "Snap": true,
                  "IgnoreFoW": false,
                  "MeasureMovement": false,
                  "DragSelectable": true,
                  "Autoraise": true,
                  "Sticky": true,
                  "Tooltip": true,
                  "GridProjection": false,
                  "HideWhenFaceDown": false,
                  "Hands": false,
                  "CustomAssetbundle": {
                    "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
                    "AssetbundleSecondaryURL": "",
                    "MaterialIndex": 2,
                    "TypeIndex": 1,
                    "LoopingEffectIndex": 0
                  },
                  "LuaScript": "\nBCBtype = \"terrain\"\n",
                  "LuaScriptState": "",
                  "XmlUI": "",
                  "ChildObjects": [
                    {
                      "GUID": "2ff768",
                      "Name": "Custom_Assetbundle",
                      "Transform": {
                        "posX": -6.87500143,
                        "posY": -1.25813173E-07,
                        "posZ": -2.14164766E-06,
                        "rotX": 1.987824E-16,
                        "rotY": 8.33763336E-10,
                        "rotZ": -2.73204441E-05,
                        "scaleX": 0.9999999,
                        "scaleY": 1.0,
                        "scaleZ": 1.00000012
                      },
                      "Nickname": "Ruin",
                      "Description": "You can NOT draw line of sight between the gaps in walls",
                      "GMNotes": "",
                      "AltLookAngle": {
                        "x": 0.0,
                        "y": 0.0,
                        "z": 0.0
                      },
                      "ColorDiffuse": {
                        "r": 1.0,
                        "g": 1.0,
                        "b": 1.0
                      },
                      "LayoutGroupSortIndex": 0,
                      "Value": 0,
                      "Locked": true,
                      "Grid": true,
                      "Snap": true,
                      "IgnoreFoW": false,
                      "MeasureMovement": false,
                      "DragSelectable": true,
                      "Autoraise": true,
                      "Sticky": true,
                      "Tooltip": true,
                      "GridProjection": false,
                      "HideWhenFaceDown": false,
                      "Hands": false,
                      "CustomAssetbundle": {
                        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
                        "AssetbundleSecondaryURL": "",
                        "MaterialIndex": 2,
                        "TypeIndex": 1,
                        "LoopingEffectIndex": 0
                      },
                      "LuaScript": "\nBCBtype = \"terrain\"\n",
                      "LuaScriptState": "",
                      "XmlUI": "",
                      "ChildObjects": [
                        {
                          "GUID": "a811d0",
                          "Name": "Custom_Model",
                          "Transform": {
                            "posX": -4.743625,
                            "posY": -0.008482325,
                            "posZ": -2.527363,
                            "rotX": 0.0251975227,
                            "rotY": 270.021484,
                            "rotZ": 359.755859,
                            "scaleX": 2.062373,
                            "scaleY": 0.471435159,
                            "scaleZ": 0.999999
                          },
                          "Nickname": "",
                          "Description": "",
                          "GMNotes": "",
                          "AltLookAngle": {
                            "x": 0.0,
                            "y": 0.0,
                            "z": 0.0
                          },
                          "ColorDiffuse": {
                            "r": 0.4441419,
                            "g": 0.4441419,
                            "b": 0.4441419
                          },
                          "LayoutGroupSortIndex": 0,
                          "Value": 0,
                          "Locked": true,
                          "Grid": true,
                          "Snap": true,
                          "IgnoreFoW": false,
                          "MeasureMovement": false,
                          "DragSelectable": true,
                          "Autoraise": true,
                          "Sticky": true,
                          "Tooltip": true,
                          "GridProjection": false,
                          "HideWhenFaceDown": false,
                          "Hands": false,
                          "CustomMesh": {
                            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009293027/95A2286D63E1AF7BB7CE9B8E33B5F27F9E975DDA/",
                            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009292144/9153E2B34BFF806C0F4E7EEFCD0594B21623FDC3/",
                            "NormalURL": "",
                            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009293027/95A2286D63E1AF7BB7CE9B8E33B5F27F9E975DDA/",
                            "Convex": false,
                            "MaterialIndex": 3,
                            "TypeIndex": 0,
                            "CustomShader": {
                              "SpecularColor": {
                                "r": 1.0,
                                "g": 1.0,
                                "b": 1.0
                              },
                              "SpecularIntensity": 0.0,
                              "SpecularSharpness": 2.0,
                              "FresnelStrength": 0.0
                            },
                            "CastShadows": true
                          },
                          "LuaScript": "",
                          "LuaScriptState": "",
                          "XmlUI": "",
                          "ChildObjects": [
                            {
                              "GUID": "698925",
                              "Name": "BlockSquare",
                              "Transform": {
                                "posX": -0.0462520532,
                                "posY": -0.0283369515,
                                "posZ": -5.92009354,
                                "rotX": -3.557538E-05,
                                "rotY": 269.9783,
                                "rotZ": -0.0010104531,
                                "scaleX": 12.5052595,
                                "scaleY": 0.060606055,
                                "scaleZ": 3.03030562
                              },
                              "Nickname": "Ruin (9\")  [sup]Barricade parts of this terrain feature are considered as 2\" high. Models may only be placed on the bottom level of this terrain feature[/sup]",
                              "Description": "",
                              "GMNotes": "",
                              "AltLookAngle": {
                                "x": 0.0,
                                "y": 0.0,
                                "z": 0.0
                              },
                              "ColorDiffuse": {
                                "r": 0.232399732,
                                "g": 0.223999709,
                                "b": 0.349999756
                              },
                              "LayoutGroupSortIndex": 0,
                              "Value": 0,
                              "Locked": true,
                              "Grid": true,
                              "Snap": true,
                              "IgnoreFoW": false,
                              "MeasureMovement": false,
                              "DragSelectable": true,
                              "Autoraise": true,
                              "Sticky": true,
                              "Tooltip": true,
                              "GridProjection": false,
                              "HideWhenFaceDown": false,
                              "Hands": false,
                              "LuaScript": "\nBCBtype = \"terrain\"\n",
                              "LuaScriptState": "",
                              "XmlUI": ""
                            }
                          ]
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    }]],
    [[{
      "GUID": "26d257",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": 7.457722E-09,
        "posY": 0.99630785,
        "posZ": -12.4,
        "rotX": 0.0173734743,
        "rotY": 0.0445708558,
        "rotZ": 0.7419824,
        "scaleX": 1.99489665,
        "scaleY": 3.527635,
        "scaleZ": 1.00002432
      },
      "Nickname": "Ruin (9\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "0d1b87",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": 1.76267076,
            "posY": -0.000449319079,
            "posZ": -0.01457209,
            "rotX": 0.000112515983,
            "rotY": 180.213272,
            "rotZ": 2.12263944E-06,
            "scaleX": 0.40102616,
            "scaleY": 1.0,
            "scaleZ": 0.7999697
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": "",
          "ChildObjects": [
            {
              "GUID": "f321f4",
              "Name": "Custom_Assetbundle",
              "Transform": {
                "posX": -0.0138203735,
                "posY": -0.008904007,
                "posZ": 1.91282463,
                "rotX": 2.52710084E-08,
                "rotY": 89.99715,
                "rotZ": -3.0327833E-06,
                "scaleX": 1.25001657,
                "scaleY": 0.9999999,
                "scaleZ": 1.25002515
              },
              "Nickname": "",
              "Description": "",
              "GMNotes": "",
              "AltLookAngle": {
                "x": 0.0,
                "y": 0.0,
                "z": 0.0
              },
              "ColorDiffuse": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "LayoutGroupSortIndex": 0,
              "Value": 0,
              "Locked": true,
              "Grid": true,
              "Snap": true,
              "IgnoreFoW": false,
              "MeasureMovement": false,
              "DragSelectable": true,
              "Autoraise": true,
              "Sticky": true,
              "Tooltip": true,
              "GridProjection": false,
              "HideWhenFaceDown": false,
              "Hands": false,
              "CustomAssetbundle": {
                "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
                "AssetbundleSecondaryURL": "",
                "MaterialIndex": 2,
                "TypeIndex": 1,
                "LoopingEffectIndex": 0
              },
              "LuaScript": "",
              "LuaScriptState": "",
              "XmlUI": "",
              "ChildObjects": [
                {
                  "GUID": "49d9cf",
                  "Name": "Custom_Assetbundle",
                  "Transform": {
                    "posX": -1.46976483,
                    "posY": 0.008956638,
                    "posZ": -0.0437401868,
                    "rotX": 359.7561,
                    "rotY": 180.0035,
                    "rotZ": -1.2685734E-05,
                    "scaleX": 0.7999891,
                    "scaleY": 1.00001287,
                    "scaleZ": 0.7999471
                  },
                  "Nickname": "",
                  "Description": "",
                  "GMNotes": "",
                  "AltLookAngle": {
                    "x": 0.0,
                    "y": 0.0,
                    "z": 0.0
                  },
                  "ColorDiffuse": {
                    "r": 1.0,
                    "g": 1.0,
                    "b": 1.0
                  },
                  "LayoutGroupSortIndex": 0,
                  "Value": 0,
                  "Locked": true,
                  "Grid": true,
                  "Snap": true,
                  "IgnoreFoW": false,
                  "MeasureMovement": false,
                  "DragSelectable": true,
                  "Autoraise": true,
                  "Sticky": true,
                  "Tooltip": true,
                  "GridProjection": false,
                  "HideWhenFaceDown": false,
                  "Hands": false,
                  "CustomAssetbundle": {
                    "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
                    "AssetbundleSecondaryURL": "",
                    "MaterialIndex": 2,
                    "TypeIndex": 1,
                    "LoopingEffectIndex": 0
                  },
                  "LuaScript": "",
                  "LuaScriptState": "",
                  "XmlUI": ""
                }
              ]
            }
          ]
        },
        {
          "GUID": "aa4e95",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": -1.81088126,
            "posY": 0.01569178,
            "posZ": 0.037571,
            "rotX": 5.44979E-06,
            "rotY": 269.499969,
            "rotZ": 0.0022164823,
            "scaleX": 0.7999201,
            "scaleY": 0.9999999,
            "scaleZ": 0.401038647
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": "",
          "ChildObjects": [
            {
              "GUID": "2d4667",
              "Name": "Custom_Assetbundle",
              "Transform": {
                "posX": -1.94005382,
                "posY": -0.0366984,
                "posZ": 0.0241482537,
                "rotX": -2.60551053E-10,
                "rotY": 4.798938E-15,
                "rotZ": -0.002110595,
                "scaleX": 1.25001729,
                "scaleY": 1.0,
                "scaleZ": 1.25002539
              },
              "Nickname": "",
              "Description": "",
              "GMNotes": "",
              "AltLookAngle": {
                "x": 0.0,
                "y": 0.0,
                "z": 0.0
              },
              "ColorDiffuse": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "LayoutGroupSortIndex": 0,
              "Value": 0,
              "Locked": true,
              "Grid": true,
              "Snap": true,
              "IgnoreFoW": false,
              "MeasureMovement": false,
              "DragSelectable": true,
              "Autoraise": true,
              "Sticky": true,
              "Tooltip": true,
              "GridProjection": false,
              "HideWhenFaceDown": false,
              "Hands": false,
              "CustomAssetbundle": {
                "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
                "AssetbundleSecondaryURL": "",
                "MaterialIndex": 2,
                "TypeIndex": 1,
                "LoopingEffectIndex": 0
              },
              "LuaScript": "",
              "LuaScriptState": "",
              "XmlUI": "",
              "ChildObjects": [
                {
                  "GUID": "f2635d",
                  "Name": "Custom_Assetbundle",
                  "Transform": {
                    "posX": -1.4476639,
                    "posY": 0.0367337279,
                    "posZ": 0.0714720041,
                    "rotX": -3.90826572E-11,
                    "rotY": -1.1715962E-17,
                    "rotZ": 3.4351564E-05,
                    "scaleX": 0.799989,
                    "scaleY": 1.0,
                    "scaleZ": 0.7999835
                  },
                  "Nickname": "",
                  "Description": "",
                  "GMNotes": "",
                  "AltLookAngle": {
                    "x": 0.0,
                    "y": 0.0,
                    "z": 0.0
                  },
                  "ColorDiffuse": {
                    "r": 1.0,
                    "g": 1.0,
                    "b": 1.0
                  },
                  "LayoutGroupSortIndex": 0,
                  "Value": 0,
                  "Locked": true,
                  "Grid": true,
                  "Snap": true,
                  "IgnoreFoW": false,
                  "MeasureMovement": false,
                  "DragSelectable": true,
                  "Autoraise": true,
                  "Sticky": true,
                  "Tooltip": true,
                  "GridProjection": false,
                  "HideWhenFaceDown": false,
                  "Hands": false,
                  "CustomAssetbundle": {
                    "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
                    "AssetbundleSecondaryURL": "",
                    "MaterialIndex": 2,
                    "TypeIndex": 1,
                    "LoopingEffectIndex": 0
                  },
                  "LuaScript": "",
                  "LuaScriptState": "",
                  "XmlUI": ""
                }
              ]
            }
          ]
        },
        {
          "GUID": "e35bfc",
          "Name": "BlockSquare",
          "Transform": {
            "posX": 0.00368750119,
            "posY": -0.0051049157,
            "posZ": -2.59992743,
            "rotX": 359.5802,
            "rotY": 269.8327,
            "rotZ": 0.00140524248,
            "scaleX": 5.999804,
            "scaleY": 0.0283482671,
            "scaleZ": 6.015127
          },
          "Nickname": "Ruin (9\")  [sup]Barricade parts of this terrain feature are considered as 2\" high. Models may only be placed on the bottom level of this terrain feature[/sup]",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 0.2323997,
            "g": 0.223999679,
            "b": 0.349999726
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "LuaScript": "\nBCBtype = \"terrain\"\n",
          "LuaScriptState": "",
          "XmlUI": ""
        }
      ]
    }]],
    [[{
      "GUID": "c9b0da",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": 0.0,
        "posY": 1.00144231,
        "posZ": 12.4,
        "rotX": -0.000852864934,
        "rotY": 180.0,
        "rotZ": 0.650000036,
        "scaleX": 1.99489665,
        "scaleY": 3.527635,
        "scaleZ": 1.00002432
      },
      "Nickname": "Ruin (9\")  [sup]Models may only be placed on the bottom level of this terrain feature[/sup]",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "0d1b87",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": 1.76267076,
            "posY": -0.000449319079,
            "posZ": -0.01457209,
            "rotX": 0.000112515983,
            "rotY": 180.213272,
            "rotZ": 2.12263944E-06,
            "scaleX": 0.40102616,
            "scaleY": 1.0,
            "scaleZ": 0.7999697
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": "",
          "ChildObjects": [
            {
              "GUID": "f321f4",
              "Name": "Custom_Assetbundle",
              "Transform": {
                "posX": -0.0138203735,
                "posY": -0.008904007,
                "posZ": 1.91282463,
                "rotX": 2.52710084E-08,
                "rotY": 89.99715,
                "rotZ": -3.0327833E-06,
                "scaleX": 1.25001657,
                "scaleY": 0.9999999,
                "scaleZ": 1.25002515
              },
              "Nickname": "",
              "Description": "",
              "GMNotes": "",
              "AltLookAngle": {
                "x": 0.0,
                "y": 0.0,
                "z": 0.0
              },
              "ColorDiffuse": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "LayoutGroupSortIndex": 0,
              "Value": 0,
              "Locked": true,
              "Grid": true,
              "Snap": true,
              "IgnoreFoW": false,
              "MeasureMovement": false,
              "DragSelectable": true,
              "Autoraise": true,
              "Sticky": true,
              "Tooltip": true,
              "GridProjection": false,
              "HideWhenFaceDown": false,
              "Hands": false,
              "CustomAssetbundle": {
                "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
                "AssetbundleSecondaryURL": "",
                "MaterialIndex": 2,
                "TypeIndex": 1,
                "LoopingEffectIndex": 0
              },
              "LuaScript": "",
              "LuaScriptState": "",
              "XmlUI": "",
              "ChildObjects": [
                {
                  "GUID": "49d9cf",
                  "Name": "Custom_Assetbundle",
                  "Transform": {
                    "posX": -1.46976483,
                    "posY": 0.008956638,
                    "posZ": -0.0437401868,
                    "rotX": 359.7561,
                    "rotY": 180.0035,
                    "rotZ": -1.2685734E-05,
                    "scaleX": 0.7999891,
                    "scaleY": 1.00001287,
                    "scaleZ": 0.7999471
                  },
                  "Nickname": "",
                  "Description": "",
                  "GMNotes": "",
                  "AltLookAngle": {
                    "x": 0.0,
                    "y": 0.0,
                    "z": 0.0
                  },
                  "ColorDiffuse": {
                    "r": 1.0,
                    "g": 1.0,
                    "b": 1.0
                  },
                  "LayoutGroupSortIndex": 0,
                  "Value": 0,
                  "Locked": true,
                  "Grid": true,
                  "Snap": true,
                  "IgnoreFoW": false,
                  "MeasureMovement": false,
                  "DragSelectable": true,
                  "Autoraise": true,
                  "Sticky": true,
                  "Tooltip": true,
                  "GridProjection": false,
                  "HideWhenFaceDown": false,
                  "Hands": false,
                  "CustomAssetbundle": {
                    "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
                    "AssetbundleSecondaryURL": "",
                    "MaterialIndex": 2,
                    "TypeIndex": 1,
                    "LoopingEffectIndex": 0
                  },
                  "LuaScript": "",
                  "LuaScriptState": "",
                  "XmlUI": ""
                }
              ]
            }
          ]
        },
        {
          "GUID": "aa4e95",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": -1.81088126,
            "posY": 0.01569178,
            "posZ": 0.037571,
            "rotX": 5.44979E-06,
            "rotY": 269.499969,
            "rotZ": 0.0022164823,
            "scaleX": 0.7999201,
            "scaleY": 0.9999999,
            "scaleZ": 0.401038647
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": "",
          "ChildObjects": [
            {
              "GUID": "2d4667",
              "Name": "Custom_Assetbundle",
              "Transform": {
                "posX": -1.94005382,
                "posY": -0.0366984,
                "posZ": 0.0241482537,
                "rotX": -2.60551053E-10,
                "rotY": 4.798938E-15,
                "rotZ": -0.002110595,
                "scaleX": 1.25001729,
                "scaleY": 1.0,
                "scaleZ": 1.25002539
              },
              "Nickname": "",
              "Description": "",
              "GMNotes": "",
              "AltLookAngle": {
                "x": 0.0,
                "y": 0.0,
                "z": 0.0
              },
              "ColorDiffuse": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "LayoutGroupSortIndex": 0,
              "Value": 0,
              "Locked": true,
              "Grid": true,
              "Snap": true,
              "IgnoreFoW": false,
              "MeasureMovement": false,
              "DragSelectable": true,
              "Autoraise": true,
              "Sticky": true,
              "Tooltip": true,
              "GridProjection": false,
              "HideWhenFaceDown": false,
              "Hands": false,
              "CustomAssetbundle": {
                "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
                "AssetbundleSecondaryURL": "",
                "MaterialIndex": 2,
                "TypeIndex": 1,
                "LoopingEffectIndex": 0
              },
              "LuaScript": "",
              "LuaScriptState": "",
              "XmlUI": "",
              "ChildObjects": [
                {
                  "GUID": "f2635d",
                  "Name": "Custom_Assetbundle",
                  "Transform": {
                    "posX": -1.4476639,
                    "posY": 0.0367337279,
                    "posZ": 0.0714720041,
                    "rotX": -3.90826572E-11,
                    "rotY": -1.1715962E-17,
                    "rotZ": 3.4351564E-05,
                    "scaleX": 0.799989,
                    "scaleY": 1.0,
                    "scaleZ": 0.7999835
                  },
                  "Nickname": "",
                  "Description": "",
                  "GMNotes": "",
                  "AltLookAngle": {
                    "x": 0.0,
                    "y": 0.0,
                    "z": 0.0
                  },
                  "ColorDiffuse": {
                    "r": 1.0,
                    "g": 1.0,
                    "b": 1.0
                  },
                  "LayoutGroupSortIndex": 0,
                  "Value": 0,
                  "Locked": true,
                  "Grid": true,
                  "Snap": true,
                  "IgnoreFoW": false,
                  "MeasureMovement": false,
                  "DragSelectable": true,
                  "Autoraise": true,
                  "Sticky": true,
                  "Tooltip": true,
                  "GridProjection": false,
                  "HideWhenFaceDown": false,
                  "Hands": false,
                  "CustomAssetbundle": {
                    "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
                    "AssetbundleSecondaryURL": "",
                    "MaterialIndex": 2,
                    "TypeIndex": 1,
                    "LoopingEffectIndex": 0
                  },
                  "LuaScript": "",
                  "LuaScriptState": "",
                  "XmlUI": ""
                }
              ]
            }
          ]
        },
        {
          "GUID": "e35bfc",
          "Name": "BlockSquare",
          "Transform": {
            "posX": 0.00368750119,
            "posY": -0.0051049157,
            "posZ": -2.59992743,
            "rotX": 359.5802,
            "rotY": 269.8327,
            "rotZ": 0.00140524248,
            "scaleX": 5.999804,
            "scaleY": 0.0283482671,
            "scaleZ": 6.015127
          },
          "Nickname": "Ruin (9\")  [sup]Barricade parts of this terrain feature are considered as 2\" high. Models may only be placed on the bottom level of this terrain feature[/sup]",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 0.2323997,
            "g": 0.223999679,
            "b": 0.349999726
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "LuaScript": "\nBCBtype = \"terrain\"\n",
          "LuaScriptState": "",
          "XmlUI": ""
        }
      ]
    }]],
    [[{
      "GUID": "f2a7d0",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": -24.4,
        "posY": 1.09815264,
        "posZ": -12.15,
        "rotX": -0.0008131572,
        "rotY": 300.0,
        "rotZ": -0.00124480925,
        "scaleX": 0.80000037,
        "scaleY": 3.49999976,
        "scaleZ": 0.80000025
      },
      "Nickname": "Ruin (9\")  [sup]Barricade parts of this terrain feature are considered as 2\" high. Models may only be placed on the bottom level of this terrain feature[/sup]",
      "Description": "You can NOT draw line of sight between the gaps in walls",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "fb9714",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": 1.84597969,
            "posY": -0.00506283529,
            "posZ": 0.007711645,
            "rotX": 0.000260726461,
            "rotY": 359.760651,
            "rotZ": -1.775535E-05,
            "scaleX": 1.25104427,
            "scaleY": 1.00000167,
            "scaleZ": 1.25004959
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        },
        {
          "GUID": "1ec7ad",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": 4.00453663,
            "posY": 4.55494228E-05,
            "posZ": 0.0167295262,
            "rotX": 0.000428200932,
            "rotY": 269.760651,
            "rotZ": -0.00206655473,
            "scaleX": 1.00000024,
            "scaleY": 1.0,
            "scaleZ": 0.9999999
          },
          "Nickname": "Ruin (9\")  [sup]Barricade parts of this terrain feature are considered as 2\" high. Models may only be placed on the bottom level of this terrain feature[/sup]",
          "Description": "You can NOT draw line of sight between the gaps in walls",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "\nBCBtype = \"terrain\"\n",
          "LuaScriptState": "",
          "XmlUI": ""
        },
        {
          "GUID": "b21c07",
          "Name": "Custom_Model",
          "Transform": {
            "posX": 2.37973738,
            "posY": -0.00602689059,
            "posZ": -12.6467237,
            "rotX": -0.00179939822,
            "rotY": 141.729065,
            "rotZ": -0.0005392424,
            "scaleX": 2.288874,
            "scaleY": 0.52317065,
            "scaleZ": 1.65139675
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 0.444141448,
            "g": 0.444141448,
            "b": 0.444141448
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009293027/95A2286D63E1AF7BB7CE9B8E33B5F27F9E975DDA/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009292144/9153E2B34BFF806C0F4E7EEFCD0594B21623FDC3/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009293027/95A2286D63E1AF7BB7CE9B8E33B5F27F9E975DDA/",
            "Convex": false,
            "MaterialIndex": 3,
            "TypeIndex": 0,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        },
        {
          "GUID": "ae2897",
          "Name": "BlockSquare",
          "Transform": {
            "posX": 0.8115834,
            "posY": -0.0193347167,
            "posZ": -6.95213556,
            "rotX": 0.001241394,
            "rotY": 269.7605,
            "rotZ": -0.000818422355,
            "scaleX": 15.0003748,
            "scaleY": 0.02857143,
            "scaleZ": 7.499996
          },
          "Nickname": "Ruin (9\")  [sup]Barricade parts of this terrain feature are considered as 2\" high. Models may only be placed on the bottom level of this terrain feature[/sup]",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 0.232399434,
            "g": 0.223999411,
            "b": 0.349999428
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "LuaScript": "\nBCBtype = \"terrain\"\n",
          "LuaScriptState": "",
          "XmlUI": "",
          "ChildObjects": [
            {
              "GUID": "84487a",
              "Name": "Custom_Assetbundle",
              "Transform": {
                "posX": 0.165266827,
                "posY": 0.499278754,
                "posZ": -0.4296064,
                "rotX": 0.00151213771,
                "rotY": 0.000163924546,
                "rotZ": -0.0008445443,
                "scaleX": 0.170753315,
                "scaleY": 35.00005,
                "scaleZ": 0.166671842
              },
              "Nickname": "",
              "Description": "",
              "GMNotes": "",
              "AltLookAngle": {
                "x": 0.0,
                "y": 0.0,
                "z": 0.0
              },
              "ColorDiffuse": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "LayoutGroupSortIndex": 0,
              "Value": 0,
              "Locked": true,
              "Grid": true,
              "Snap": true,
              "IgnoreFoW": false,
              "MeasureMovement": false,
              "DragSelectable": true,
              "Autoraise": true,
              "Sticky": true,
              "Tooltip": true,
              "GridProjection": false,
              "HideWhenFaceDown": false,
              "Hands": false,
              "CustomAssetbundle": {
                "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
                "AssetbundleSecondaryURL": "",
                "MaterialIndex": 2,
                "TypeIndex": 1,
                "LoopingEffectIndex": 0
              },
              "LuaScript": "",
              "LuaScriptState": "",
              "XmlUI": "",
              "ChildObjects": [
                {
                  "GUID": "648368",
                  "Name": "Custom_Assetbundle",
                  "Transform": {
                    "posX": -1.71452427,
                    "posY": 0.00887796748,
                    "posZ": -2.08441952E-06,
                    "rotX": -0.00254509854,
                    "rotY": -3.750643E-08,
                    "rotZ": 0.000634715369,
                    "scaleX": 0.390417129,
                    "scaleY": 0.9999982,
                    "scaleZ": 0.7999757
                  },
                  "Nickname": "Ruin",
                  "Description": "You can NOT draw line of sight between the gaps in walls",
                  "GMNotes": "",
                  "AltLookAngle": {
                    "x": 0.0,
                    "y": 0.0,
                    "z": 0.0
                  },
                  "ColorDiffuse": {
                    "r": 1.0,
                    "g": 1.0,
                    "b": 1.0
                  },
                  "LayoutGroupSortIndex": 0,
                  "Value": 0,
                  "Locked": true,
                  "Grid": true,
                  "Snap": true,
                  "IgnoreFoW": false,
                  "MeasureMovement": false,
                  "DragSelectable": true,
                  "Autoraise": true,
                  "Sticky": true,
                  "Tooltip": true,
                  "GridProjection": false,
                  "HideWhenFaceDown": false,
                  "Hands": false,
                  "CustomAssetbundle": {
                    "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
                    "AssetbundleSecondaryURL": "",
                    "MaterialIndex": 2,
                    "TypeIndex": 1,
                    "LoopingEffectIndex": 0
                  },
                  "LuaScript": "\nBCBtype = \"terrain\"\n",
                  "LuaScriptState": "",
                  "XmlUI": ""
                }
              ]
            }
          ]
        }
      ]
    }]],
    [[{
      "GUID": "cbaf57",
      "Name": "Custom_Assetbundle",
      "Transform": {
        "posX": 24.4,
        "posY": 1.09815276,
        "posZ": 12.1492729,
        "rotX": -0.0008137112,
        "rotY": 120.000015,
        "rotZ": -0.00124546466,
        "scaleX": 0.80000037,
        "scaleY": 3.49999976,
        "scaleZ": 0.80000025
      },
      "Nickname": "Ruin (9\")  [sup]Barricade parts of this terrain feature are considered as 2\" high. Models may only be placed on the bottom level of this terrain feature[/sup]",
      "Description": "You can NOT draw line of sight between the gaps in walls",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomAssetbundle": {
        "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
        "AssetbundleSecondaryURL": "",
        "MaterialIndex": 2,
        "TypeIndex": 1,
        "LoopingEffectIndex": 0
      },
      "LuaScript": "\nBCBtype = \"terrain\"\n",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "fb9714",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": 1.84597969,
            "posY": -0.00506283529,
            "posZ": 0.007711645,
            "rotX": 0.000260726461,
            "rotY": 359.760651,
            "rotZ": -1.775535E-05,
            "scaleX": 1.25104427,
            "scaleY": 1.00000167,
            "scaleZ": 1.25004959
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        },
        {
          "GUID": "1ec7ad",
          "Name": "Custom_Assetbundle",
          "Transform": {
            "posX": 4.00453663,
            "posY": 4.55494228E-05,
            "posZ": 0.0167295262,
            "rotX": 0.000428200932,
            "rotY": 269.760651,
            "rotZ": -0.00206655473,
            "scaleX": 1.00000024,
            "scaleY": 1.0,
            "scaleZ": 0.9999999
          },
          "Nickname": "Ruin (9\")  [sup]Barricade parts of this terrain feature are considered as 2\" high. Models may only be placed on the bottom level of this terrain feature[/sup]",
          "Description": "You can NOT draw line of sight between the gaps in walls",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomAssetbundle": {
            "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
            "AssetbundleSecondaryURL": "",
            "MaterialIndex": 2,
            "TypeIndex": 1,
            "LoopingEffectIndex": 0
          },
          "LuaScript": "\nBCBtype = \"terrain\"\n",
          "LuaScriptState": "",
          "XmlUI": ""
        },
        {
          "GUID": "b21c07",
          "Name": "Custom_Model",
          "Transform": {
            "posX": 2.37973738,
            "posY": -0.00602689059,
            "posZ": -12.6467237,
            "rotX": -0.00179939822,
            "rotY": 141.729065,
            "rotZ": -0.0005392424,
            "scaleX": 2.288874,
            "scaleY": 0.52317065,
            "scaleZ": 1.65139675
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 0.444141448,
            "g": 0.444141448,
            "b": 0.444141448
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009293027/95A2286D63E1AF7BB7CE9B8E33B5F27F9E975DDA/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009292144/9153E2B34BFF806C0F4E7EEFCD0594B21623FDC3/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1689399684009293027/95A2286D63E1AF7BB7CE9B8E33B5F27F9E975DDA/",
            "Convex": false,
            "MaterialIndex": 3,
            "TypeIndex": 0,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        },
        {
          "GUID": "ae2897",
          "Name": "BlockSquare",
          "Transform": {
            "posX": 0.8115834,
            "posY": -0.0193347167,
            "posZ": -6.95213556,
            "rotX": 0.001241394,
            "rotY": 269.7605,
            "rotZ": -0.000818422355,
            "scaleX": 15.0003748,
            "scaleY": 0.02857143,
            "scaleZ": 7.499996
          },
          "Nickname": "Ruin (9\")  [sup]Barricade parts of this terrain feature are considered as 2\" high. Models may only be placed on the bottom level of this terrain feature[/sup]",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 0.232399434,
            "g": 0.223999411,
            "b": 0.349999428
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "LuaScript": "\nBCBtype = \"terrain\"\n",
          "LuaScriptState": "",
          "XmlUI": "",
          "ChildObjects": [
            {
              "GUID": "84487a",
              "Name": "Custom_Assetbundle",
              "Transform": {
                "posX": 0.165266827,
                "posY": 0.499278754,
                "posZ": -0.4296064,
                "rotX": 0.00151213771,
                "rotY": 0.000163924546,
                "rotZ": -0.0008445443,
                "scaleX": 0.170753315,
                "scaleY": 35.00005,
                "scaleZ": 0.166671842
              },
              "Nickname": "",
              "Description": "",
              "GMNotes": "",
              "AltLookAngle": {
                "x": 0.0,
                "y": 0.0,
                "z": 0.0
              },
              "ColorDiffuse": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "LayoutGroupSortIndex": 0,
              "Value": 0,
              "Locked": true,
              "Grid": true,
              "Snap": true,
              "IgnoreFoW": false,
              "MeasureMovement": false,
              "DragSelectable": true,
              "Autoraise": true,
              "Sticky": true,
              "Tooltip": true,
              "GridProjection": false,
              "HideWhenFaceDown": false,
              "Hands": false,
              "CustomAssetbundle": {
                "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1814409791276862663/C2C86C4F97C6EB4F9A2209ACAE21CE4CC1FD3B30/",
                "AssetbundleSecondaryURL": "",
                "MaterialIndex": 2,
                "TypeIndex": 1,
                "LoopingEffectIndex": 0
              },
              "LuaScript": "",
              "LuaScriptState": "",
              "XmlUI": "",
              "ChildObjects": [
                {
                  "GUID": "648368",
                  "Name": "Custom_Assetbundle",
                  "Transform": {
                    "posX": -1.71452427,
                    "posY": 0.00887796748,
                    "posZ": -2.08441952E-06,
                    "rotX": -0.00254509854,
                    "rotY": -3.750643E-08,
                    "rotZ": 0.000634715369,
                    "scaleX": 0.390417129,
                    "scaleY": 0.9999982,
                    "scaleZ": 0.7999757
                  },
                  "Nickname": "Ruin",
                  "Description": "You can NOT draw line of sight between the gaps in walls",
                  "GMNotes": "",
                  "AltLookAngle": {
                    "x": 0.0,
                    "y": 0.0,
                    "z": 0.0
                  },
                  "ColorDiffuse": {
                    "r": 1.0,
                    "g": 1.0,
                    "b": 1.0
                  },
                  "LayoutGroupSortIndex": 0,
                  "Value": 0,
                  "Locked": true,
                  "Grid": true,
                  "Snap": true,
                  "IgnoreFoW": false,
                  "MeasureMovement": false,
                  "DragSelectable": true,
                  "Autoraise": true,
                  "Sticky": true,
                  "Tooltip": true,
                  "GridProjection": false,
                  "HideWhenFaceDown": false,
                  "Hands": false,
                  "CustomAssetbundle": {
                    "AssetbundleURL": "https://steamusercontent-a.akamaihd.net/ugc/1833549455346803391/EE73153AEE143847EBBFFDABEC00294AE66CBCAD/",
                    "AssetbundleSecondaryURL": "",
                    "MaterialIndex": 2,
                    "TypeIndex": 1,
                    "LoopingEffectIndex": 0
                  },
                  "LuaScript": "\nBCBtype = \"terrain\"\n",
                  "LuaScriptState": "",
                  "XmlUI": ""
                }
              ]
            }
          ]
        }
      ]
    }]],

    [[{
      "GUID": "7f414f",
      "Name": "Custom_Model",
      "Transform": {
        "posX": 0.0,
        "posY": -10.13,
        "posZ": 0.0,
        "rotX": 0.0,
        "rotY": 0.0,
        "rotZ": 0.0,
        "scaleX": 1.666,
        "scaleY": 1.06,
        "scaleZ": 1.2206
      },
      "Nickname": "",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": true,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomMesh": {
        "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/879750610978796176/4A5A65543B98BCFBF57E910D06EC984208223D38/",
        "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2044114931095280776/E1E5945811D1F5CE79E1A0B1580133658FC2A9AE/",
        "NormalURL": "",
        "ColliderURL": "",
        "Convex": true,
        "MaterialIndex": 3,
        "TypeIndex": 4,
        "CustomShader": {
          "SpecularColor": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "SpecularIntensity": 0.0,
          "SpecularSharpness": 2.0,
          "FresnelStrength": 0.0
        },
        "CastShadows": true
      },
      "LuaScript": "\nBCBtype = \"terrain\"\nfunction onload() \r\n    self.interactable = false\r\n    self.gizmo_selectable = true\r\nend",
      "LuaScriptState": "",
      "XmlUI": ""
    }]],
}

